export const EMERGENCY_API_TIMEOUT_MS = 10_000;
export const EMERGENCY_LIST_PAGE_SIZE = 20;
export const EMERGENCY_CACHE_TTL_MS = 60_000;
export const EMERGENCY_LOOKUP_CACHE_TTL_MS = 5 * 60_000;
export const EMERGENCY_ATTENDANCE_CACHE_TTL_MS = 30_000;

export const EMERGENCY_DISABLE_DASHBOARD_AUTO_REFRESH = true;
export const EMERGENCY_DISABLE_HEAVY_BACKGROUND_JOBS = true;

// Phase 1 — connection-pool protection
export const EMERGENCY_DISABLE_REALTIME = true;
export const EMERGENCY_DISABLE_AUTO_PRELOAD = true;
export const EMERGENCY_MAX_IDLE_CONNECTION_MS = 5_000;
