export const EMERGENCY_API_TIMEOUT_MS = 10_000;
export const EMERGENCY_LIST_PAGE_SIZE = 20;
export const EMERGENCY_CACHE_TTL_MS = 60_000;
export const EMERGENCY_LOOKUP_CACHE_TTL_MS = 5 * 60_000;
export const EMERGENCY_ATTENDANCE_CACHE_TTL_MS = 30_000;

export const EMERGENCY_DISABLE_DASHBOARD_AUTO_REFRESH = true;
export const EMERGENCY_DISABLE_HEAVY_BACKGROUND_JOBS = true;
