import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<string, Record<Language, string>> = {
  'app.title': { en: 'HR Management System', ar: 'نظام إدارة الموارد البشرية' },
  'nav.dashboard': { en: 'Dashboard', ar: 'لوحة التحكم' },
  'nav.employees': { en: 'Employees', ar: 'الموظفين' },
  'nav.departments': { en: 'Departments', ar: 'الأقسام' },
  'nav.attendance': { en: 'Attendance', ar: 'الحضور والانصراف' },
  'nav.missions': { en: 'Mission Requests', ar: 'طلبات المأمورية' },
  'nav.leaves': { en: 'Leaves Permissions Missions', ar: 'الإجازات الأذونات المأموريات' },
  'nav.permissions': { en: 'Permissions', ar: 'الأذونات' },
  'nav.salaries': { en: 'Salaries', ar: 'الرواتب' },
  'nav.salaryReports': { en: 'Salary Reports', ar: 'تقارير الرواتب' },
  'nav.loans': { en: 'Loans', ar: 'القروض' },
  'nav.recruitment': { en: 'Recruitment', ar: 'التوظيف' },
  'nav.performance': { en: 'Performance', ar: 'تقييم الأداء' },
  'nav.assets': { en: 'Assets', ar: 'الأصول' },
  'nav.uniforms': { en: 'Uniforms', ar: 'يونيفورم الموظفين' },
  'nav.documents': { en: 'Documents', ar: 'المستندات' },
  'nav.reports': { en: 'Reports', ar: 'التقارير' },
  'nav.training': { en: 'Training', ar: 'التدريب' },
  'nav.configurations': { en: 'CONFIGURATIONS', ar: 'الإعدادات' },
  'nav.users': { en: 'Users', ar: 'المستخدمين' },
  'nav.groups': { en: 'Groups', ar: 'المجموعات' },
  'nav.roles': { en: 'Roles', ar: 'الأدوار' },
  'nav.settings': { en: 'Site Settings', ar: 'إعدادات الموقع' },
  'nav.employeePortal': { en: 'Employee Portal', ar: 'بوابة الموظف' },
  'dashboard.title': { en: 'Dashboard', ar: 'لوحة التحكم' },
  'dashboard.totalEmployees': { en: 'Total Employees', ar: 'إجمالي الموظفين' },
  'dashboard.activeEmployees': { en: 'Active Employees', ar: 'موظفين نشطين' },
  'dashboard.departments': { en: 'Departments', ar: 'الأقسام' },
  'dashboard.todayAttendance': { en: 'Today Attendance', ar: 'الحضور اليوم' },
  'dashboard.openPositions': { en: 'Open Positions', ar: 'الوظائف المفتوحة' },
  'dashboard.pendingLeaves': { en: 'Pending Leave Requests', ar: 'طلبات الإجازة المعلقة' },
  'dashboard.assignedAssets': { en: 'Assigned Assets', ar: 'الأصول المعينة' },
  'dashboard.avgPerformance': { en: 'Avg Performance', ar: 'متوسط تقييم الأداء' },
  'chart.reportsStats': { en: 'Reports & Statistics', ar: 'التقارير والإحصائيات' },
  'chart.employeeGrowth': { en: 'Employee Growth (Last 6 Months)', ar: 'نمو الموظفين (آخر 6 أشهر)' },
  'chart.departmentDist': { en: 'Employees by Department', ar: 'توزيع الموظفين حسب القسم' },
  'chart.weeklyAttendance': { en: 'Weekly Attendance & Performance', ar: 'الحضور والأداء الأسبوعي' },
  'chart.advancedReports': { en: 'Advanced Reports', ar: 'لوحة التقارير المتقدمة' },
  'chart.refresh': { en: 'Refresh', ar: 'تحديث' },
  'dept.it': { en: 'IT', ar: 'تقنية المعلومات' },
  'dept.hr': { en: 'HR', ar: 'الموارد البشرية' },
  'dept.finance': { en: 'Finance', ar: 'المالية' },
  'dept.sales': { en: 'Sales', ar: 'المبيعات' },
  'dept.marketing': { en: 'Marketing', ar: 'التسويق' },
  'dept.operations': { en: 'Operations', ar: 'العمليات' },
  'legend.attendance': { en: 'Attendance', ar: 'الحضور' },
  'legend.completed': { en: 'Completed Tasks', ar: 'التقييمات المكتملة' },
  'legend.late': { en: 'Late', ar: 'التأخير' },
  'month.jan': { en: 'Jan', ar: 'يناير' },
  'month.feb': { en: 'Feb', ar: 'فبراير' },
  'month.mar': { en: 'Mar', ar: 'مارس' },
  'month.apr': { en: 'Apr', ar: 'أبريل' },
  'month.may': { en: 'May', ar: 'مايو' },
  'month.jun': { en: 'Jun', ar: 'يونيو' },
  // Employees page
  'employees.title': { en: 'Employee Management', ar: 'إدارة الموظفين' },
  'employees.search': { en: 'Search for employee...', ar: 'ابحث عن موظف...' },
  'employees.addEmployee': { en: 'Add Employee', ar: 'إضافة موظف' },
  'employees.refresh': { en: 'Refresh', ar: 'تحديث' },
  'employees.editEmployee': { en: 'Edit Employee', ar: 'تعديل الموظف' },
  'employees.save': { en: 'Save', ar: 'حفظ' },
  'employees.cancel': { en: 'Cancel', ar: 'إلغاء' },
  'employees.select': { en: 'Select', ar: 'اختر' },
  'employees.selectDepartment': { en: 'Select Department', ar: 'اختر القسم' },
  'employees.selectDegree': { en: 'Select Degree', ar: 'اختر الدرجة' },
  'employees.selectContractType': { en: 'Select Contract Type', ar: 'اختر نوع العقد' },
  'employees.addNewDepartment': { en: 'Add New Department', ar: 'إضافة قسم جديد' },
  'employees.clickToUpload': { en: 'Click on camera to upload photo', ar: 'انقر على أيقونة الكاميرا لتحميل صورة' },
  'employees.table.photo': { en: 'Photo', ar: 'الصورة' },
  'employees.table.employeeId': { en: 'Employee ID', ar: 'رقم الموظف' },
  'employees.table.name': { en: 'Name', ar: 'الاسم' },
  'employees.table.department': { en: 'Department', ar: 'القسم' },
  'employees.table.jobTitle': { en: 'Job Title', ar: 'المسمى الوظيفي' },
  'employees.table.phone': { en: 'Phone', ar: 'الهاتف' },
  'employees.table.status': { en: 'Status', ar: 'الحالة' },
  'employees.table.actions': { en: 'Actions', ar: 'الإجراءات' },
  'employees.status.active': { en: 'Active', ar: 'نشط' },
  'employees.status.inactive': { en: 'Inactive', ar: 'غير نشط' },
  'employees.status.resigned': { en: 'Resigned', ar: 'مستقيل' },
  'employees.tabs.basicInfo': { en: 'Basic Info', ar: 'معلومات أساسية' },
  'employees.tabs.contactInfo': { en: 'Contact Info', ar: 'معلومات الاتصال' },
  'employees.tabs.identity': { en: 'Identity & Documents', ar: 'الهوية والوثائق' },
  'employees.tabs.jobInfo': { en: 'Job Info', ar: 'معلومات الوظيفة' },
  'employees.tabs.insurance': { en: 'Insurance', ar: 'التأمينات' },
  'employees.tabs.permits': { en: 'Permits', ar: 'التصاريح' },
  'employees.tabs.certificates': { en: 'Certificates', ar: 'الشهادات والوثائق' },
  'employees.tabs.departments': { en: 'Departments', ar: 'الأقسام' },
  'employees.tabs.other': { en: 'Other', ar: 'أخرى' },
  'employees.tabs.leaveBalance': { en: 'Leave Balance', ar: 'رصيد الإجازات' },
  'employees.tabs.salary': { en: 'Salary & Allowances', ar: 'الرواتب والبدلات' },
  'employees.fields.employeeId': { en: 'Employee ID', ar: 'رقم الموظف' },
  'employees.fields.stationLocation': { en: 'Station/Location', ar: 'المحطة/الموقع' },
  'employees.fields.enterStation': { en: 'Enter Station', ar: 'ادخل المحطة' },
  'employees.fields.fullNameAr': { en: 'Full Name (Arabic)', ar: 'الاسم الكامل بالعربية' },
  'employees.fields.fullNameEn': { en: 'Full Name (English)', ar: 'الاسم الكامل بالإنجليزية' },
  'employees.fields.firstName': { en: 'First Name', ar: 'الاسم الأول' },
  'employees.fields.fatherName': { en: 'Father Name', ar: 'اسم الأب' },
  'employees.fields.familyName': { en: 'Family Name', ar: 'اسم العائلة' },
  'employees.fields.birthDate': { en: 'Birth Date', ar: 'تاريخ الميلاد' },
  'employees.fields.birthPlace': { en: 'Birth Place', ar: 'مكان الميلاد' },
  'employees.fields.birthGovernorate': { en: 'Birth Governorate', ar: 'محافظة الميلاد' },
  'employees.fields.gender': { en: 'Gender', ar: 'النوع' },
  'employees.fields.religion': { en: 'Religion', ar: 'الديانة' },
  'employees.fields.nationality': { en: 'Nationality', ar: 'الجنسية' },
  'employees.fields.maritalStatus': { en: 'Marital Status', ar: 'الحالة الاجتماعية' },
  'employees.fields.childrenCount': { en: 'Number of Children', ar: 'عدد الأطفال' },
  'employees.fields.educationAr': { en: 'Education (Arabic)', ar: 'المؤهل الدراسي بالعربية' },
  'employees.fields.graduationYear': { en: 'Graduation Year', ar: 'سنة التخرج' },
  'employees.fields.email': { en: 'Email', ar: 'البريد الإلكتروني' },
  'employees.fields.homePhone': { en: 'Home Phone', ar: 'هاتف المنزل' },
  'employees.fields.mobile': { en: 'Mobile', ar: 'الهاتف المحمول' },
  'employees.fields.address': { en: 'Address', ar: 'العنوان' },
  'employees.fields.city': { en: 'City', ar: 'المدينة' },
  'employees.fields.governorate': { en: 'Governorate', ar: 'المحافظة' },
  'employees.fields.nationalId': { en: 'National ID / Passport', ar: 'الرقم القومي/رقم جواز السفر' },
  'employees.fields.idIssueDate': { en: 'ID Issue Date', ar: 'تاريخ إصدار البطاقة' },
  'employees.fields.idExpiryDate': { en: 'ID Expiry Date', ar: 'تاريخ انتهاء البطاقة' },
  'employees.fields.issuingAuthority': { en: 'Issuing Authority', ar: 'جهة الإصدار' },
  'employees.fields.issuingGovernorate': { en: 'Issuing Governorate', ar: 'محافظة الإصدار' },
  'employees.fields.militaryStatus': { en: 'Military Status', ar: 'الحالة العسكرية' },
  'employees.fields.department': { en: 'Department', ar: 'القسم' },
  'employees.fields.jobTitleAr': { en: 'Job Title (Arabic)', ar: 'المسمى الوظيفي بالعربية' },
  'employees.fields.jobTitleEn': { en: 'Job Title (English)', ar: 'المسمى الوظيفي بالإنجليزية' },
  'employees.fields.jobLevel': { en: 'Job Level', ar: 'مستوى الوظيفة' },
  'employees.fields.jobDegree': { en: 'Job Degree', ar: 'الدرجة الوظيفية' },
  'employees.fields.hireDate': { en: 'Hire Date', ar: 'تاريخ التعيين' },
  'employees.fields.recruitedBy': { en: 'Recruited By', ar: 'طلب التوظيف بواسطة' },
  'employees.fields.employmentStatus': { en: 'Employment Status', ar: 'الحالة' },
  'employees.fields.resigned': { en: 'Resigned', ar: 'مستقيل' },
  'employees.fields.resignationDate': { en: 'Resignation Date', ar: 'تاريخ الاستقالة' },
  'employees.fields.resignationReason': { en: 'Resignation Reason', ar: 'سبب الاستقالة' },
  'employees.fields.socialInsuranceNo': { en: 'Social Insurance No.', ar: 'رقم التأمين الاجتماعي' },
  'employees.fields.socialInsuranceStartDate': { en: 'Social Insurance Start Date', ar: 'تاريخ بدء التأمين الاجتماعي' },
  'employees.fields.socialInsuranceEndDate': { en: 'Social Insurance End Date', ar: 'تاريخ انتهاء التأمين الاجتماعي' },
  'employees.fields.healthInsuranceCardNo': { en: 'Health Insurance Card No.', ar: 'رقم بطاقة التأمين الصحي' },
  'employees.fields.healthInsurance': { en: 'Health Insurance', ar: 'التأمين الصحي' },
  'employees.fields.govHealthInsurance': { en: 'Government Health Insurance', ar: 'التأمين الصحي الحكومي' },
  'employees.fields.socialInsurance': { en: 'Social Insurance', ar: 'التأمين الاجتماعي' },
  'employees.fields.contractType': { en: 'Contract Type', ar: 'نوع العقد' },
  'employees.fields.cairoAirportTempPermit': { en: 'Cairo Airport Temp Permit', ar: 'تصريح مطار القاهرة المؤقت' },
  'employees.fields.cairoAirportAnnualPermit': { en: 'Cairo Airport Annual Permit', ar: 'تصريح مطار القاهرة السنوي' },
  'employees.fields.tempPermitNo': { en: 'Temp Permit No.', ar: 'رقم التصريح المؤقت' },
  'employees.fields.annualPermitNo': { en: 'Annual Permit No.', ar: 'رقم التصريح السنوي' },
  'employees.fields.airportsTempPermit': { en: 'Airports Temp Permit', ar: 'تصريح المطارات المؤقت' },
  'employees.fields.airportsAnnualPermit': { en: 'Airports Annual Permit', ar: 'تصريح المطارات السنوي' },
  'employees.fields.airportsTempPermitNo': { en: 'Airports Temp Permit No.', ar: 'رقم تصريح المطارات المؤقت' },
  'employees.fields.airportsAnnualPermitNo': { en: 'Airports Annual Permit No.', ar: 'رقم تصريح المطارات السنوي' },
  'employees.fields.airportsPermitType': { en: 'Airports Permit Type', ar: 'نوع تصاريح المطارات' },
  'employees.fields.permitNameEn': { en: 'Permit Name (English)', ar: 'المسمى في التصريح بالإنجليزية' },
  'employees.fields.permitNameAr': { en: 'Permit Name (Arabic)', ar: 'المسمى في التصريح بالعربية' },
  'employees.fields.qualificationCert': { en: 'Qualification Certificate', ar: 'شهادة المؤهل' },
  'employees.fields.militaryServiceCert': { en: 'Military Service Certificate', ar: 'شهادة الخدمة العسكرية' },
  'employees.fields.birthCert': { en: 'Birth Certificate', ar: 'شهادة الميلاد' },
  'employees.fields.idCopy': { en: 'ID Copy', ar: 'صورة البطاقة' },
  'employees.fields.pledge': { en: 'Pledge', ar: 'التعهد' },
  'employees.fields.contract': { en: 'Contract', ar: 'العقد' },
  'employees.fields.receipt': { en: 'Receipt', ar: 'الفيش' },
  'employees.fields.attachments': { en: 'Attachments', ar: 'المرفقات' },
  'employees.fields.notes': { en: 'Notes', ar: 'ملاحظات' },
  'employees.fields.notesPlaceholder': { en: 'Enter any additional notes...', ar: 'أدخل أي ملاحظات إضافية...' },
  'employees.fields.annualLeaveBalance': { en: 'Annual Leave Balance', ar: 'رصيد الإجازات السنوية' },
  'employees.fields.sickLeaveBalance': { en: 'Sick Leave Balance', ar: 'رصيد الإجازات المرضية' },
  'employees.fields.casualLeaveBalance': { en: 'Casual Leave Balance', ar: 'رصيد الإجازات العارضة' },
  'employees.fields.usedLeave': { en: 'Used Leave', ar: 'الإجازات المستخدمة' },
  'employees.fields.basicSalary': { en: 'Basic Salary', ar: 'الراتب الأساسي' },
  'employees.fields.allowances': { en: 'Allowances', ar: 'البدلات' },
  'employees.fields.transportAllowance': { en: 'Transport Allowance', ar: 'بدل المواصلات' },
  'employees.fields.housingAllowance': { en: 'Housing Allowance', ar: 'بدل السكن' },
  'employees.fields.mealAllowance': { en: 'Meal Allowance', ar: 'بدل الوجبات' },
  'employees.fields.otherAllowances': { en: 'Other Allowances', ar: 'بدلات أخرى' },
  'employees.fields.deductions': { en: 'Deductions', ar: 'الاستقطاعات' },
  'employees.fields.netSalary': { en: 'Net Salary', ar: 'صافي الراتب' },
  'employees.gender.male': { en: 'Male', ar: 'ذكر' },
  'employees.gender.female': { en: 'Female', ar: 'أنثى' },
  'employees.religion.muslim': { en: 'Muslim', ar: 'مسلم' },
  'employees.religion.christian': { en: 'Christian', ar: 'مسيحي' },
  'employees.maritalStatus.single': { en: 'Single', ar: 'أعزب' },
  'employees.maritalStatus.married': { en: 'Married', ar: 'متزوج' },
  'employees.maritalStatus.divorced': { en: 'Divorced', ar: 'مطلق' },
  'employees.maritalStatus.widowed': { en: 'Widowed', ar: 'أرمل' },
  'employees.military.completed': { en: 'Completed', ar: 'أدى الخدمة' },
  'employees.military.exempt': { en: 'Exempt', ar: 'معفى' },
  'employees.military.postponed': { en: 'Postponed', ar: 'مؤجل' },
  'employees.military.notApplicable': { en: 'Not Applicable', ar: 'لا ينطبق' },
  'employees.contract.permanent': { en: 'Permanent', ar: 'دائم' },
  'employees.contract.sixMonths': { en: '6 Months', ar: 'ستة أشهر' },
  'employees.contract.oneYear': { en: '1 Year', ar: 'سنة' },
  'employees.contract.fourYears': { en: '4 Years', ar: '4 سنوات' },
  'employees.contract.temporary': { en: 'Temporary', ar: 'مؤقت' },
  'employees.contract.parttime': { en: 'Part-time', ar: 'جزئي' },
  'employees.jobLevel.junior': { en: 'Junior', ar: 'Junior' },
  'employees.jobLevel.mid': { en: 'Med Level', ar: 'Med Level' },
  'employees.jobLevel.senior': { en: 'Senior', ar: 'Senior' },
  'employees.jobLevel.shiftLeader': { en: 'Shift Leader', ar: 'Shift Leader' },
  'employees.jobLevel.supervisor': { en: 'Supervisor', ar: 'Supervisor' },
  'employees.jobLevel.manager': { en: 'Manager', ar: 'Manager' },
  'employees.jobLevel.director': { en: 'Director', ar: 'Director' },
  'employees.importExcel': { en: 'Import Excel', ar: 'استيراد Excel' },
  'employees.exportExcel': { en: 'Export Excel', ar: 'تصدير Excel' },
  'employees.stats.total': { en: 'Total Employees', ar: 'إجمالي الموظفين' },
  'employees.stats.active': { en: 'Active', ar: 'نشط' },
  'employees.stats.departments': { en: 'Departments', ar: 'الأقسام' },
  'employees.stats.newThisMonth': { en: 'New This Month', ar: 'موظفون جدد (هذا الشهر)' },
  'employees.searchAdvanced': { en: 'Search by name, number, department, or job title...', ar: 'ابحث فوراً بالاسم، الرقم، القسم، أو المسمى الوظيفي...' },
  'employees.filter.all': { en: 'All', ar: 'الكل' },
  'employees.filter.active': { en: 'Active', ar: 'نشط' },
  'employees.filter.inactive': { en: 'Inactive', ar: 'غير نشط' },
  'employees.filter.suspended': { en: 'Suspended', ar: 'موقوف' },
  'employees.status.suspended': { en: 'Suspended', ar: 'موقوف' },
  'employees.status.undefined': { en: 'Undefined', ar: 'غير محدد' },
  'employees.details.title': { en: 'Employee Details', ar: 'تفاصيل الموظف' },
  'employees.details.backToList': { en: 'Back to List', ar: 'العودة للقائمة' },
  'employees.details.nameAr': { en: 'Name (Arabic)', ar: 'الاسم بالعربية' },
  'employees.details.nameEn': { en: 'Name (English)', ar: 'الاسم بالإنجليزية' },
  'employees.tabs.attendanceRecord': { en: 'Attendance Record', ar: 'سجل الحضور' },
  'employees.tabs.leaveRecord': { en: 'Leave & Permissions Record', ar: 'سجل الإجازات والأذونات' },
  'employees.tabs.missionRecord': { en: 'Mission Record', ar: 'سجل المأموريات' },
  'employees.tabs.evaluations': { en: 'Evaluations', ar: 'التقييمات' },
  'employees.tabs.violations': { en: 'Violations & Penalties', ar: 'المخالفات والجزاءات' },
  'employees.tabs.documents': { en: 'Documents', ar: 'المستندات' },
  'employees.tabs.salaryRecord': { en: 'Salary Record', ar: 'سجل الرواتب' },
  'employees.tabs.loansAdvances': { en: 'Advances & Loans', ar: 'السلف والقروض' },
  'employees.tabs.training': { en: 'Training & Development', ar: 'التدريب والتطوير' },
  'employees.tabs.notes': { en: 'Notes', ar: 'الملاحظات' },
  // Leaves module
  'leaves.title': { en: 'Leave & Requests Management', ar: 'إدارة الإجازات والطلبات' },
  'leaves.subtitle': { en: 'Manage leaves, permissions, missions and overtime', ar: 'إدارة الإجازات والأذونات والمأموريات والإضافات' },
  'leaves.tabs.leaves': { en: 'Leaves', ar: 'الإجازات' },
  'leaves.tabs.permissions': { en: 'Permissions', ar: 'الأذونات' },
  'leaves.tabs.missions': { en: 'Missions', ar: 'المأموريات' },
  'leaves.tabs.overtime': { en: 'Overtime', ar: 'الإضافات' },
  'leaves.tabs.requests': { en: 'All Requests', ar: 'جميع الطلبات' },
  'leaves.tabs.newRequest': { en: 'New Request', ar: 'طلب جديد' },
  'leaves.tabs.approvals': { en: 'Approvals', ar: 'الموافقات' },
  'leaves.tabs.balance': { en: 'Balance', ar: 'الأرصدة' },
  'leaves.tabs.calendar': { en: 'Calendar', ar: 'التقويم' },
  'leaves.days': { en: 'days', ar: 'أيام' },
  'leaves.types.annual': { en: 'Annual', ar: 'سنوية' },
  'leaves.types.sick': { en: 'Sick', ar: 'مرضية' },
  'leaves.types.casual': { en: 'Casual', ar: 'عارضة' },
  'leaves.types.unpaid': { en: 'Unpaid', ar: 'بدون راتب' },
  'leaves.types.maternity': { en: 'Maternity', ar: 'أمومة' },
  'leaves.types.paternity': { en: 'Paternity', ar: 'أبوة' },
  'leaves.status.pending': { en: 'Pending', ar: 'معلقة' },
  'leaves.status.approved': { en: 'Approved', ar: 'موافق عليه' },
  'leaves.status.rejected': { en: 'Rejected', ar: 'مرفوض' },
  // Leave form
  'leaves.form.title': { en: 'Submit Leave Request', ar: 'تقديم طلب إجازة' },
  'leaves.form.leaveType': { en: 'Leave Type', ar: 'نوع الإجازة' },
  'leaves.form.selectType': { en: 'Select leave type', ar: 'اختر نوع الإجازة' },
  'leaves.form.startDate': { en: 'Start Date', ar: 'تاريخ البداية' },
  'leaves.form.endDate': { en: 'End Date', ar: 'تاريخ النهاية' },
  'leaves.form.totalDays': { en: 'Total Days', ar: 'إجمالي الأيام' },
  'leaves.form.reason': { en: 'Reason', ar: 'السبب' },
  'leaves.form.reasonPlaceholder': { en: 'Enter reason for leave...', ar: 'أدخل سبب الإجازة...' },
  'leaves.form.pickDate': { en: 'Pick a date', ar: 'اختر تاريخ' },
  'leaves.form.submit': { en: 'Submit Request', ar: 'إرسال الطلب' },
  'leaves.form.error': { en: 'Error', ar: 'خطأ' },
  'leaves.form.fillAllFields': { en: 'Please fill all required fields', ar: 'يرجى ملء جميع الحقول المطلوبة' },
  'leaves.form.success': { en: 'Success', ar: 'نجاح' },
  'leaves.form.requestSubmitted': { en: 'Leave request submitted successfully', ar: 'تم تقديم طلب الإجازة بنجاح' },
  'leaves.list.title': { en: 'Leave Requests', ar: 'طلبات الإجازات' },
  'leaves.list.employee': { en: 'Employee', ar: 'الموظف' },
  'leaves.list.department': { en: 'Department', ar: 'القسم' },
  'leaves.list.type': { en: 'Type', ar: 'النوع' },
  'leaves.list.startDate': { en: 'Start Date', ar: 'تاريخ البداية' },
  'leaves.list.endDate': { en: 'End Date', ar: 'تاريخ النهاية' },
  'leaves.list.days': { en: 'Days', ar: 'الأيام' },
  'leaves.list.status': { en: 'Status', ar: 'الحالة' },
  'leaves.list.noRequests': { en: 'No leave requests found', ar: 'لا توجد طلبات إجازة' },
  'leaves.approvals.title': { en: 'Pending Approvals', ar: 'الموافقات المعلقة' },
  'leaves.approvals.noPending': { en: 'No pending requests to approve', ar: 'لا توجد طلبات معلقة للموافقة' },
  'leaves.approvals.approve': { en: 'Approve', ar: 'موافقة' },
  'leaves.approvals.reject': { en: 'Reject', ar: 'رفض' },
  'leaves.approvals.approved': { en: 'Approved', ar: 'تمت الموافقة' },
  'leaves.approvals.approvedMessage': { en: 'Leave request has been approved', ar: 'تمت الموافقة على طلب الإجازة' },
  'leaves.approvals.rejected': { en: 'Rejected', ar: 'تم الرفض' },
  'leaves.approvals.rejectedMessage': { en: 'Leave request has been rejected', ar: 'تم رفض طلب الإجازة' },
  'leaves.approvals.rejectTitle': { en: 'Reject Leave Request', ar: 'رفض طلب الإجازة' },
  'leaves.approvals.rejectReasonPlaceholder': { en: 'Enter reason for rejection...', ar: 'أدخل سبب الرفض...' },
  'leaves.approvals.confirmReject': { en: 'Confirm Rejection', ar: 'تأكيد الرفض' },
  'leaves.balance.annualLeave': { en: 'Annual Leave', ar: 'الإجازة السنوية' },
  'leaves.balance.sickLeave': { en: 'Sick Leave', ar: 'الإجازة المرضية' },
  'leaves.balance.casualLeave': { en: 'Casual Leave', ar: 'الإجازة العارضة' },
  'leaves.balance.used': { en: 'Used', ar: 'مستخدم' },
  'leaves.balance.remaining': { en: 'Remaining', ar: 'المتبقي' },
  'leaves.balance.detailedBalance': { en: 'Detailed Leave Balance', ar: 'تفاصيل رصيد الإجازات' },
  'leaves.balance.employee': { en: 'Employee', ar: 'الموظف' },
  'leaves.balance.department': { en: 'Department', ar: 'القسم' },
  'leaves.calendar.title': { en: 'Team Absence Calendar', ar: 'تقويم غياب الفريق' },
  'leaves.calendar.more': { en: 'more', ar: 'المزيد' },
  // New Request Form
  'leaves.newRequest.title': { en: 'New Request', ar: 'طلب جديد' },
  'leaves.newRequest.leaveTab': { en: 'Leave', ar: 'إجازة' },
  'leaves.newRequest.permissionTab': { en: 'Permission', ar: 'إذن' },
  'leaves.newRequest.missionTab': { en: 'Mission', ar: 'مأمورية' },
  'leaves.newRequest.overtimeTab': { en: 'Overtime', ar: 'إضافة' },
  'leaves.newRequest.employee': { en: 'Employee', ar: 'الموظف' },
  'leaves.newRequest.selectEmployee': { en: 'Select employee', ar: 'اختر الموظف' },
  'leaves.newRequest.searchEmployee': { en: 'Search employee...', ar: 'ابحث عن موظف...' },
  'leaves.newRequest.noEmployeeFound': { en: 'No employee found', ar: 'لم يتم العثور على موظف' },
  'leaves.newRequest.saveRequest': { en: 'Save Request', ar: 'حفظ الطلب' },
  // Permission types
  'leaves.permTypes.early_leave': { en: 'Early Leave', ar: 'انصراف مبكر' },
  'leaves.permTypes.late_arrival': { en: 'Late Arrival', ar: 'حضور متأخر' },
  'leaves.permTypes.personal': { en: 'Personal', ar: 'شخصي' },
  'leaves.permTypes.medical': { en: 'Medical', ar: 'طبي' },
  'leaves.permissions.listTitle': { en: 'Permission Requests', ar: 'طلبات الأذونات' },
  'leaves.permissions.type': { en: 'Permission Type', ar: 'نوع الإذن' },
  'leaves.permissions.selectType': { en: 'Select permission type', ar: 'اختر نوع الإذن' },
  'leaves.permissions.date': { en: 'Date', ar: 'التاريخ' },
  'leaves.permissions.fromTime': { en: 'From Time', ar: 'من الساعة' },
  'leaves.permissions.toTime': { en: 'To Time', ar: 'إلى الساعة' },
  'leaves.permissions.duration': { en: 'Duration', ar: 'المدة' },
  'leaves.permissions.noRequests': { en: 'No permission requests found', ar: 'لا توجد طلبات أذونات' },
  'leaves.permissions.reasonPlaceholder': { en: 'Enter reason for permission...', ar: 'أدخل سبب الإذن...' },
  'leaves.permissions.requestSubmitted': { en: 'Permission request submitted successfully', ar: 'تم تقديم طلب الإذن بنجاح' },
  // Mission types
  'leaves.missionTypes.internal': { en: 'Internal', ar: 'داخلية' },
  'leaves.missionTypes.external': { en: 'External', ar: 'خارجية' },
  'leaves.missionTypes.training': { en: 'Training', ar: 'تدريبية' },
  'leaves.missionTypes.meeting': { en: 'Meeting', ar: 'اجتماع' },
  'leaves.missionTypes.client_visit': { en: 'Client Visit', ar: 'زيارة عميل' },
  'leaves.missions.listTitle': { en: 'Mission Requests', ar: 'طلبات المأموريات' },
  'leaves.missions.type': { en: 'Mission Type', ar: 'نوع المأمورية' },
  'leaves.missions.selectType': { en: 'Select mission type', ar: 'اختر نوع المأمورية' },
  'leaves.missions.date': { en: 'Mission Date', ar: 'تاريخ المأمورية' },
  'leaves.missions.destination': { en: 'Destination', ar: 'الوجهة' },
  'leaves.missions.destinationPlaceholder': { en: 'Enter destination...', ar: 'أدخل الوجهة...' },
  'leaves.missions.reason': { en: 'Mission Reason', ar: 'سبب المأمورية' },
  'leaves.missions.reasonPlaceholder': { en: 'Please describe the mission reason in detail...', ar: 'الرجاء ذكر سبب المأمورية بالتفصيل...' },
  'leaves.missions.noRequests': { en: 'No mission requests found', ar: 'لا توجد طلبات مأموريات' },
  'leaves.missions.requestSubmitted': { en: 'Mission request submitted successfully', ar: 'تم تقديم طلب المأمورية بنجاح' },
  // Overtime types
  'leaves.overtimeTypes.regular': { en: 'Regular', ar: 'عادي' },
  'leaves.overtimeTypes.holiday': { en: 'Holiday', ar: 'إجازة رسمية' },
  'leaves.overtimeTypes.weekend': { en: 'Weekend', ar: 'عطلة أسبوعية' },
  'leaves.overtime.listTitle': { en: 'Overtime Requests', ar: 'طلبات الإضافات' },
  'leaves.overtime.type': { en: 'Overtime Type', ar: 'نوع الإضافة' },
  'leaves.overtime.selectType': { en: 'Select overtime type', ar: 'اختر نوع الإضافة' },
  'leaves.overtime.date': { en: 'Date', ar: 'التاريخ' },
  'leaves.overtime.hours': { en: 'Hours', ar: 'الساعات' },
  'leaves.overtime.reason': { en: 'Reason', ar: 'السبب' },
  'leaves.overtime.reasonPlaceholder': { en: 'Enter reason for overtime...', ar: 'أدخل سبب الإضافة...' },
  'leaves.overtime.noRequests': { en: 'No overtime requests found', ar: 'لا توجد طلبات إضافات' },
  'leaves.overtime.requestSubmitted': { en: 'Overtime request submitted successfully', ar: 'تم تقديم طلب الإضافة بنجاح' },
  // Attendance module
  'attendance.title': { en: 'Attendance Management', ar: 'إدارة الحضور والانصراف' },
  'attendance.subtitle': { en: 'Track employee check-ins, check-outs, and attendance reports', ar: 'تتبع حضور وانصراف الموظفين والتقارير' },
  'attendance.tabs.checkInOut': { en: 'Check In/Out', ar: 'تسجيل الحضور' },
  'attendance.tabs.records': { en: 'Records', ar: 'السجلات' },
  'attendance.tabs.lateArrivals': { en: 'Late Arrivals', ar: 'التأخيرات' },
  'attendance.tabs.reports': { en: 'Reports', ar: 'التقارير' },
  'attendance.checkin.button': { en: 'Check In', ar: 'تسجيل الحضور' },
  'attendance.checkout.button': { en: 'Check Out', ar: 'تسجيل الانصراف' },
  'attendance.checkin.time': { en: 'Check In Time', ar: 'وقت الحضور' },
  'attendance.checkout.time': { en: 'Check Out Time', ar: 'وقت الانصراف' },
  'attendance.workDuration': { en: 'Work Duration', ar: 'مدة العمل' },
  'attendance.todayStatus': { en: "Today's Status", ar: 'حالة اليوم' },
  'attendance.completed': { en: 'Day Completed', ar: 'تم الانتهاء' },
  'attendance.checkin.success': { en: 'Checked In', ar: 'تم تسجيل الحضور' },
  'attendance.checkin.successMessage': { en: 'You have successfully checked in', ar: 'تم تسجيل حضورك بنجاح' },
  'attendance.checkout.success': { en: 'Checked Out', ar: 'تم تسجيل الانصراف' },
  'attendance.checkout.successMessage': { en: 'You have successfully checked out', ar: 'تم تسجيل انصرافك بنجاح' },
  'attendance.checkin.confirm': { en: 'Confirm Check In', ar: 'تأكيد تسجيل الحضور' },
  'attendance.checkout.confirm': { en: 'Confirm Check Out', ar: 'تأكيد تسجيل الانصراف' },
  'attendance.allEmployeesCheckedIn': { en: 'All employees have checked in today', ar: 'جميع الموظفين سجلوا حضورهم اليوم' },
  'attendance.noEmployeesToCheckOut': { en: 'No employees to check out', ar: 'لا يوجد موظفين لتسجيل انصرافهم' },
  'attendance.recentActivity': { en: 'Recent Activity', ar: 'النشاط الأخير' },
  'attendance.lateBy': { en: 'Late by', ar: 'تأخير بمقدار' },
  'attendance.status.present': { en: 'Present', ar: 'حاضر' },
  'attendance.status.absent': { en: 'Absent', ar: 'غائب' },
  'attendance.status.late': { en: 'Late', ar: 'متأخر' },
  'attendance.status.early-leave': { en: 'Early Leave', ar: 'انصراف مبكر' },
  'attendance.status.on-leave': { en: 'On Leave', ar: 'في إجازة' },
  'attendance.list.title': { en: 'Attendance Records', ar: 'سجلات الحضور' },
  'attendance.list.search': { en: 'Search employees...', ar: 'ابحث عن موظف...' },
  'attendance.list.filterStatus': { en: 'Filter by status', ar: 'تصفية حسب الحالة' },
  'attendance.list.allStatuses': { en: 'All Statuses', ar: 'جميع الحالات' },
  'attendance.list.pickDate': { en: 'Pick a date', ar: 'اختر تاريخ' },
  'attendance.list.clearDate': { en: 'Clear', ar: 'مسح' },
  'attendance.list.date': { en: 'Date', ar: 'التاريخ' },
  'attendance.list.employee': { en: 'Employee', ar: 'الموظف' },
  'attendance.list.department': { en: 'Department', ar: 'القسم' },
  'attendance.list.checkIn': { en: 'Check In', ar: 'الحضور' },
  'attendance.list.checkOut': { en: 'Check Out', ar: 'الانصراف' },
  'attendance.list.workHours': { en: 'Work Hours', ar: 'ساعات العمل' },
  'attendance.list.overtime': { en: 'Overtime', ar: 'إضافي' },
  'attendance.list.status': { en: 'Status', ar: 'الحالة' },
  'attendance.list.noRecords': { en: 'No attendance records found', ar: 'لا توجد سجلات حضور' },
  'attendance.late.today': { en: 'Late Today', ar: 'المتأخرون اليوم' },
  'attendance.late.thisWeek': { en: 'Late This Week', ar: 'متأخرون هذا الأسبوع' },
  'attendance.late.frequentOffenders': { en: 'Frequent Offenders', ar: 'المتأخرون بشكل متكرر' },
  'attendance.late.todayList': { en: "Today's Late Arrivals", ar: 'المتأخرون اليوم' },
  'attendance.late.noReason': { en: 'No reason provided', ar: 'لم يتم تقديم سبب' },
  'attendance.late.frequentTitle': { en: 'Frequent Late Arrivals', ar: 'التأخيرات المتكررة' },
  'attendance.late.noLateArrivals': { en: 'No late arrivals recorded', ar: 'لا توجد تأخيرات مسجلة' },
  'attendance.late.lateCount': { en: 'Late Count', ar: 'عدد التأخيرات' },
  'attendance.late.avgLateTime': { en: 'Avg. Late Time', ar: 'متوسط وقت التأخير' },
  'attendance.late.severity': { en: 'Severity', ar: 'الخطورة' },
  'attendance.late.times': { en: 'times', ar: 'مرات' },
  'attendance.late.severity.low': { en: 'Low', ar: 'منخفض' },
  'attendance.late.severity.medium': { en: 'Medium', ar: 'متوسط' },
  'attendance.late.severity.high': { en: 'High', ar: 'عالي' },
  'attendance.reports.attendanceRate': { en: 'Attendance Rate', ar: 'معدل الحضور' },
  'attendance.reports.punctualityRate': { en: 'Punctuality Rate', ar: 'معدل الالتزام بالوقت' },
  'attendance.reports.totalWorkHours': { en: 'Total Work Hours', ar: 'إجمالي ساعات العمل' },
  'attendance.reports.totalOvertime': { en: 'Total Overtime', ar: 'إجمالي الإضافي' },
  'attendance.reports.statusDistribution': { en: 'Status Distribution', ar: 'توزيع الحالات' },
  'attendance.reports.weeklyTrend': { en: 'Weekly Trend', ar: 'الاتجاه الأسبوعي' },
  'attendance.reports.totalAttendance': { en: 'Total Attendance', ar: 'إجمالي الحضور' },
  'attendance.reports.departmentWise': { en: 'Department-wise Attendance', ar: 'الحضور حسب القسم' },
  // Attendance - Shifts Management
  'attendance.tabs.shifts': { en: 'Shifts', ar: 'الورديات' },
  'attendance.tabs.rules': { en: 'Rules', ar: 'القواعد' },
  'attendance.tabs.locations': { en: 'Locations', ar: 'المواقع' },
  'attendance.tabs.assignment': { en: 'Assignment', ar: 'التعيينات' },
  'attendance.shifts.title': { en: 'Shift Management', ar: 'إدارة الورديات' },
  'attendance.shifts.subtitle': { en: 'Configure 24/7 shift patterns for airport operations', ar: 'تكوين أنماط الورديات على مدار الساعة لعمليات المطار' },
  'attendance.shifts.addShift': { en: 'Add Shift', ar: 'إضافة وردية' },
  'attendance.shifts.nameEn': { en: 'Name (English)', ar: 'الاسم (إنجليزي)' },
  'attendance.shifts.nameAr': { en: 'Name (Arabic)', ar: 'الاسم (عربي)' },
  'attendance.shifts.startTime': { en: 'Start Time', ar: 'وقت البداية' },
  'attendance.shifts.endTime': { en: 'End Time', ar: 'وقت النهاية' },
  'attendance.shifts.location': { en: 'Location', ar: 'الموقع' },
  'attendance.shifts.selectLocation': { en: 'Select location', ar: 'اختر الموقع' },
  'attendance.shifts.breakDuration': { en: 'Break (min)', ar: 'الاستراحة (دقيقة)' },
  'attendance.shifts.color': { en: 'Color', ar: 'اللون' },
  'attendance.shifts.overnight': { en: 'Overnight Shift', ar: 'وردية ليلية' },
  'attendance.shifts.save': { en: 'Save Shift', ar: 'حفظ الوردية' },
  'attendance.shifts.filterByLocation': { en: 'Filter by Location', ar: 'تصفية حسب الموقع' },
  'attendance.shifts.allLocations': { en: 'All Locations', ar: 'جميع المواقع' },
  'attendance.shifts.time': { en: 'Time', ar: 'الوقت' },
  'attendance.shifts.duration': { en: 'Duration', ar: 'المدة' },
  'attendance.shifts.break': { en: 'Break', ar: 'الاستراحة' },
  'attendance.shifts.overnightShift': { en: 'Overnight', ar: 'ليلية' },
  'attendance.shifts.scheduleOverview': { en: 'Shift Schedule Overview', ar: 'نظرة عامة على جدول الورديات' },
  'attendance.shifts.scheduleDesc': { en: 'View all configured shifts and their assignments', ar: 'عرض جميع الورديات المكونة وتعييناتها' },
  'attendance.shifts.shift': { en: 'Shift', ar: 'الوردية' },
  'attendance.shifts.employees': { en: 'Employees', ar: 'الموظفين' },
  'attendance.shifts.status': { en: 'Status', ar: 'الحالة' },
  'attendance.shifts.active': { en: 'Active', ar: 'نشط' },
  // Attendance - Rules Management
  'attendance.rules.title': { en: 'Attendance Rules', ar: 'قواعد الحضور' },
  'attendance.rules.subtitle': { en: 'Configure attendance policies for different schedule types', ar: 'تكوين سياسات الحضور لأنواع الجداول المختلفة' },
  'attendance.rules.addRule': { en: 'Add Rule', ar: 'إضافة قاعدة' },
  'attendance.rules.fixed': { en: 'Fixed', ar: 'ثابت' },
  'attendance.rules.flexible': { en: 'Flexible', ar: 'مرن' },
  'attendance.rules.shift': { en: 'Shift', ar: 'ورديات' },
  'attendance.rules.nameEn': { en: 'Name (English)', ar: 'الاسم (إنجليزي)' },
  'attendance.rules.nameAr': { en: 'Name (Arabic)', ar: 'الاسم (عربي)' },
  'attendance.rules.description': { en: 'Description', ar: 'الوصف' },
  'attendance.rules.fixedSettings': { en: 'Fixed Schedule Settings', ar: 'إعدادات الدوام الثابت' },
  'attendance.rules.flexibleSettings': { en: 'Flexible Schedule Settings', ar: 'إعدادات الدوام المرن' },
  'attendance.rules.shiftSettings': { en: 'Shift Schedule Settings', ar: 'إعدادات نظام الورديات' },
  'attendance.rules.startTime': { en: 'Start Time', ar: 'وقت البداية' },
  'attendance.rules.endTime': { en: 'End Time', ar: 'وقت النهاية' },
  'attendance.rules.gracePeriod': { en: 'Grace Period', ar: 'فترة السماح' },
  'attendance.rules.earlyLeave': { en: 'Early Leave Tolerance', ar: 'تسامح الانصراف المبكر' },
  'attendance.rules.minutes': { en: 'min', ar: 'دقيقة' },
  'attendance.rules.arrivalStart': { en: 'Arrival Window Start', ar: 'بداية نافذة الحضور' },
  'attendance.rules.arrivalEnd': { en: 'Arrival Window End', ar: 'نهاية نافذة الحضور' },
  'attendance.rules.minWorkHours': { en: 'Minimum Work Hours', ar: 'الحد الأدنى لساعات العمل' },
  'attendance.rules.coreStart': { en: 'Core Hours Start', ar: 'بداية الساعات الأساسية' },
  'attendance.rules.coreEnd': { en: 'Core Hours End', ar: 'نهاية الساعات الأساسية' },
  'attendance.rules.shiftTemplate': { en: 'Shift Template', ar: 'قالب الورديات' },
  'attendance.rules.threeShift': { en: '3-Shift Pattern (8 hours each)', ar: 'نظام 3 ورديات (8 ساعات لكل وردية)' },
  'attendance.rules.fourShift': { en: '4-Shift Pattern (6 hours each)', ar: 'نظام 4 ورديات (6 ساعات لكل وردية)' },
  'attendance.rules.allowSwap': { en: 'Allow Shift Swap', ar: 'السماح بتبديل الورديات' },
  'attendance.rules.nightAllowance': { en: 'Night Shift Allowance', ar: 'بدل الوردية الليلية' },
  'attendance.rules.commonSettings': { en: 'Common Settings', ar: 'الإعدادات العامة' },
  'attendance.rules.maxDailyOT': { en: 'Max Daily Overtime (hours)', ar: 'الحد الأقصى للإضافي اليومي (ساعات)' },
  'attendance.rules.maxWeeklyOT': { en: 'Max Weekly Overtime (hours)', ar: 'الحد الأقصى للإضافي الأسبوعي (ساعات)' },
  'attendance.rules.save': { en: 'Save Rule', ar: 'حفظ القاعدة' },
  'attendance.rules.fixedRules': { en: 'Fixed Rules', ar: 'قواعد ثابتة' },
  'attendance.rules.flexibleRules': { en: 'Flexible Rules', ar: 'قواعد مرنة' },
  'attendance.rules.shiftRules': { en: 'Shift Rules', ar: 'قواعد ورديات' },
  'attendance.rules.assignedEmployees': { en: 'Assigned Employees', ar: 'موظفين معينين' },
  'attendance.rules.viewDetails': { en: 'View Details', ar: 'عرض التفاصيل' },
  'attendance.rules.workingHours': { en: 'Working Hours', ar: 'ساعات العمل' },
  'attendance.rules.arrivalWindow': { en: 'Arrival Window', ar: 'نافذة الحضور' },
  'attendance.rules.allowed': { en: 'Allowed', ar: 'مسموح' },
  'attendance.rules.notAllowed': { en: 'Not Allowed', ar: 'غير مسموح' },
  'attendance.rules.yes': { en: 'Yes', ar: 'نعم' },
  'attendance.rules.no': { en: 'No', ar: 'لا' },
  'attendance.rules.workDays': { en: 'Work Days', ar: 'أيام العمل' },
  'attendance.rules.daysPerWeek': { en: 'days/week', ar: 'يوم/أسبوع' },
  // Attendance - Locations Management
  'attendance.locations.title': { en: 'Location Management', ar: 'إدارة المواقع' },
  'attendance.locations.subtitle': { en: 'Configure headquarters and airport locations', ar: 'تكوين مواقع المقر الرئيسي والمطارات' },
  'attendance.locations.addLocation': { en: 'Add Location', ar: 'إضافة موقع' },
  'attendance.locations.nameEn': { en: 'Name (English)', ar: 'الاسم (إنجليزي)' },
  'attendance.locations.nameAr': { en: 'Name (Arabic)', ar: 'الاسم (عربي)' },
  'attendance.locations.code': { en: 'Code', ar: 'الرمز' },
  'attendance.locations.type': { en: 'Type', ar: 'النوع' },
  'attendance.locations.headquarters': { en: 'Headquarters', ar: 'المقر الرئيسي' },
  'attendance.locations.airport': { en: 'Airport', ar: 'مطار' },
  'attendance.locations.airports': { en: 'Airports', ar: 'المطارات' },
  'attendance.locations.address': { en: 'Address', ar: 'العنوان' },
  'attendance.locations.timezone': { en: 'Timezone', ar: 'المنطقة الزمنية' },
  'attendance.locations.save': { en: 'Save Location', ar: 'حفظ الموقع' },
  'attendance.locations.activeLocations': { en: 'Active Locations', ar: 'مواقع نشطة' },
  'attendance.locations.employees': { en: 'employees', ar: 'موظف' },
  'attendance.locations.24hours': { en: '24/7 Operations', ar: 'عمليات على مدار الساعة' },
  'attendance.locations.geofence': { en: 'Geofence Radius', ar: 'نطاق السياج الجغرافي' },
  'attendance.locations.editLocation': { en: 'Edit Location', ar: 'تعديل الموقع' },
  // Attendance - Employee Assignment
  'attendance.assignment.title': { en: 'Employee Attendance Assignment', ar: 'تعيين حضور الموظفين' },
  'attendance.assignment.subtitle': { en: 'Assign attendance rules and shifts to employees', ar: 'تعيين قواعد الحضور والورديات للموظفين' },
  'attendance.assignment.assignEmployee': { en: 'Assign Employee', ar: 'تعيين موظف' },
  'attendance.assignment.employee': { en: 'Employee', ar: 'الموظف' },
  'attendance.assignment.selectEmployee': { en: 'Select employee', ar: 'اختر الموظف' },
  'attendance.assignment.attendanceRule': { en: 'Attendance Rule', ar: 'قاعدة الحضور' },
  'attendance.assignment.selectRule': { en: 'Select rule', ar: 'اختر القاعدة' },
  'attendance.assignment.location': { en: 'Location', ar: 'الموقع' },
  'attendance.assignment.selectLocation': { en: 'Select location', ar: 'اختر الموقع' },
  'attendance.assignment.shift': { en: 'Shift', ar: 'الوردية' },
  'attendance.assignment.selectShift': { en: 'Select shift (for shift workers)', ar: 'اختر الوردية (لعمال الورديات)' },
  'attendance.assignment.noShift': { en: 'No Shift (HQ employees)', ar: 'بدون وردية (موظفي المقر)' },
  'attendance.assignment.effectiveFrom': { en: 'Effective From', ar: 'ساري من تاريخ' },
  'attendance.assignment.save': { en: 'Save Assignment', ar: 'حفظ التعيين' },
  'attendance.assignment.search': { en: 'Search employees...', ar: 'ابحث عن موظف...' },
  'attendance.assignment.allLocations': { en: 'All Locations', ar: 'جميع المواقع' },
  'attendance.assignment.allRules': { en: 'All Rules', ar: 'جميع القواعد' },
  'attendance.assignment.employeeAssignments': { en: 'Employee Assignments', ar: 'تعيينات الموظفين' },
  'attendance.assignment.employees': { en: 'employees', ar: 'موظف' },
  'attendance.assignment.department': { en: 'Department', ar: 'القسم' },
  'attendance.assignment.actions': { en: 'Actions', ar: 'الإجراءات' },
  // Performance module
  'performance.title': { en: 'Performance Evaluation', ar: 'تقييم الأداء' },
  'performance.subtitle': { en: 'Quarterly employee performance reviews and tracking', ar: 'تقييمات الأداء الربع سنوية ومتابعة الموظفين' },
  'performance.tabs.dashboard': { en: 'Dashboard', ar: 'لوحة التحكم' },
  'performance.tabs.reviews': { en: 'Reviews', ar: 'التقييمات' },
  'performance.tabs.newReview': { en: 'New Review', ar: 'تقييم جديد' },
  'performance.tabs.reports': { en: 'Reports', ar: 'التقارير' },
  'performance.stats.avgScore': { en: 'Average Score', ar: 'متوسط التقييم' },
  'performance.stats.totalReviews': { en: 'Total Reviews', ar: 'إجمالي التقييمات' },
  'performance.stats.pendingReviews': { en: 'Pending Reviews', ar: 'تقييمات معلقة' },
  'performance.stats.completionRate': { en: 'Completion Rate', ar: 'معدل الإكمال' },
  'performance.charts.distribution': { en: 'Performance Distribution', ar: 'توزيع التقييمات' },
  'performance.charts.quarterlyTrend': { en: 'Quarterly Trend', ar: 'الاتجاه الربع سنوي' },
  'performance.topPerformers': { en: 'Top Performers', ar: 'أفضل الموظفين أداءً' },
  'performance.metrics.average': { en: 'Average Score', ar: 'متوسط التقييم' },
  'performance.metrics.completed': { en: 'Completed Reviews', ar: 'التقييمات المكتملة' },
  'performance.metrics.actualScore': { en: 'Actual Score', ar: 'التقييم الفعلي' },
  'performance.metrics.target': { en: 'Target', ar: 'المستهدف' },
  'performance.score.excellent': { en: 'Excellent', ar: 'ممتاز' },
  'performance.score.veryGood': { en: 'Very Good', ar: 'جيد جداً' },
  'performance.score.good': { en: 'Good', ar: 'جيد' },
  'performance.score.acceptable': { en: 'Acceptable', ar: 'مقبول' },
  'performance.score.poor': { en: 'Poor', ar: 'ضعيف' },
  'performance.form.selectEmployee': { en: 'Select Employee', ar: 'اختيار الموظف' },
  'performance.form.employee': { en: 'Employee', ar: 'الموظف' },
  'performance.form.selectEmployeePlaceholder': { en: 'Select an employee...', ar: 'اختر موظف...' },
  'performance.form.quarter': { en: 'Quarter', ar: 'الربع السنوي' },
  'performance.form.selectQuarterPlaceholder': { en: 'Select quarter...', ar: 'اختر الربع السنوي...' },
  'performance.form.criteria': { en: 'Evaluation Criteria', ar: 'معايير التقييم' },
  'performance.form.criteriaDesc': { en: 'Rate each criterion from 1 to 5 stars', ar: 'قيّم كل معيار من 1 إلى 5 نجوم' },
  'performance.form.overallScore': { en: 'Overall Score', ar: 'التقييم الإجمالي' },
  'performance.form.strengths': { en: 'Strengths', ar: 'نقاط القوة' },
  'performance.form.strengthsPlaceholder': { en: 'Describe employee strengths...', ar: 'اذكر نقاط قوة الموظف...' },
  'performance.form.improvements': { en: 'Areas for Improvement', ar: 'مجالات التحسين' },
  'performance.form.improvementsPlaceholder': { en: 'Describe areas that need improvement...', ar: 'اذكر المجالات التي تحتاج تحسين...' },
  'performance.form.nextQuarterGoals': { en: 'Next Quarter Goals', ar: 'أهداف الربع القادم' },
  'performance.form.goalsPlaceholder': { en: 'Set goals for the next quarter...', ar: 'حدد أهداف الربع القادم...' },
  'performance.form.managerComments': { en: 'Manager Comments', ar: 'ملاحظات المدير' },
  'performance.form.managerCommentsPlaceholder': { en: 'Add any additional comments...', ar: 'أضف أي ملاحظات إضافية...' },
  'performance.form.saveDraft': { en: 'Save Draft', ar: 'حفظ كمسودة' },
  'performance.form.submit': { en: 'Submit Review', ar: 'إرسال التقييم' },
  'performance.form.draftSaved': { en: 'Draft saved successfully', ar: 'تم حفظ المسودة بنجاح' },
  'performance.form.submitted': { en: 'Review submitted successfully', ar: 'تم إرسال التقييم بنجاح' },
  'performance.form.fillRequired': { en: 'Please fill all required fields', ar: 'يرجى ملء جميع الحقول المطلوبة' },
  'performance.status.approved': { en: 'Approved', ar: 'معتمد' },
  'performance.status.submitted': { en: 'Submitted', ar: 'مُرسل' },
  'performance.status.draft': { en: 'Draft', ar: 'مسودة' },
  'performance.list.title': { en: 'Performance Reviews', ar: 'تقييمات الأداء' },
  'performance.list.search': { en: 'Search by name or department...', ar: 'ابحث بالاسم أو القسم...' },
  'performance.list.status': { en: 'Status', ar: 'الحالة' },
  'performance.list.allStatuses': { en: 'All Statuses', ar: 'جميع الحالات' },
  'performance.list.quarter': { en: 'Quarter', ar: 'الربع' },
  'performance.list.allQuarters': { en: 'All Quarters', ar: 'جميع الأرباع' },
  'performance.list.employee': { en: 'Employee', ar: 'الموظف' },
  'performance.list.department': { en: 'Department', ar: 'القسم' },
  'performance.list.score': { en: 'Score', ar: 'التقييم' },
  'performance.list.reviewer': { en: 'Reviewer', ar: 'المقيّم' },
  'performance.list.actions': { en: 'Actions', ar: 'الإجراءات' },
  'performance.list.noResults': { en: 'No reviews found', ar: 'لا توجد تقييمات' },
  'performance.reports.title': { en: 'Quarterly Reports', ar: 'التقارير الربع سنوية' },
  'performance.reports.description': { en: 'View and export quarterly performance reports', ar: 'عرض وتصدير تقارير الأداء الربع سنوية' },
  'performance.reports.export': { en: 'Export', ar: 'تصدير' },
  'performance.reports.totalReviews': { en: 'Total Reviews', ar: 'إجمالي التقييمات' },
  'performance.reports.avgScore': { en: 'Average Score', ar: 'متوسط التقييم' },
  'performance.reports.aboveTarget': { en: 'Above Target', ar: 'فوق المستهدف' },
  'performance.reports.needsImprovement': { en: 'Needs Improvement', ar: 'يحتاج تحسين' },
  'performance.reports.quarterlyTrend': { en: 'Quarterly Score Trend', ar: 'اتجاه التقييم الربع سنوي' },
  'performance.reports.criteriaAnalysis': { en: 'Criteria Analysis', ar: 'تحليل المعايير' },
  'performance.reports.departmentPerformance': { en: 'Department Performance', ar: 'أداء الأقسام' },
  'performance.reports.employees': { en: 'employees', ar: 'موظف' },
  'performance.reports.criteriaBreakdown': { en: 'Criteria Breakdown', ar: 'تفصيل المعايير' },
  // Attendance - CheckInOut additional translations
  'attendance.selectEmployee': { en: 'Select Employee', ar: 'اختر الموظف' },
  'attendance.employee': { en: 'Employee', ar: 'الموظف' },
  'attendance.selectEmployeePlaceholder': { en: 'Select an employee...', ar: 'اختر موظف...' },
  'attendance.selectEmployeeFirst': { en: 'Please select an employee first', ar: 'يرجى اختيار موظف أولاً' },
  'attendance.addEmployee': { en: 'Add Employee', ar: 'إضافة موظف' },
  'attendance.addNewEmployee': { en: 'Add New Employee', ar: 'إضافة موظف جديد' },
  'attendance.employeeNameEn': { en: 'Name (English)', ar: 'الاسم (إنجليزي)' },
  'attendance.employeeNameAr': { en: 'Name (Arabic)', ar: 'الاسم (عربي)' },
  'attendance.department': { en: 'Department', ar: 'القسم' },
  'attendance.selectDepartment': { en: 'Select Department', ar: 'اختر القسم' },
  'attendance.location': { en: 'Location', ar: 'الموقع' },
  'attendance.locations.hq': { en: 'Headquarters', ar: 'المقر الرئيسي' },
  'attendance.locations.airportT1': { en: 'Airport - Terminal 1', ar: 'المطار - صالة 1' },
  'attendance.locations.airportT2': { en: 'Airport - Terminal 2', ar: 'المطار - صالة 2' },
  'attendance.locations.airportT3': { en: 'Airport - Terminal 3', ar: 'المطار - صالة 3' },
  'attendance.employeeAdded': { en: 'Employee Added', ar: 'تمت إضافة الموظف' },
  'attendance.fillAllFields': { en: 'Please fill all required fields', ar: 'يرجى ملء جميع الحقول المطلوبة' },
  'attendance.todaySummary': { en: "Today's Summary", ar: 'ملخص اليوم' },
  'attendance.totalCheckedIn': { en: 'Total Checked In', ar: 'إجمالي الحضور' },
  'attendance.totalCheckedOut': { en: 'Total Checked Out', ar: 'إجمالي الانصراف' },
  'attendance.totalLate': { en: 'Total Late', ar: 'إجمالي المتأخرين' },
  'common.cancel': { en: 'Cancel', ar: 'إلغاء' },
  'common.add': { en: 'Add', ar: 'إضافة' },
  'common.save': { en: 'Save', ar: 'حفظ' },
  'common.delete': { en: 'Delete', ar: 'حذف' },
  'common.edit': { en: 'Edit', ar: 'تعديل' },
  'common.all': { en: 'All', ar: 'الكل' },
  'common.actions': { en: 'Actions', ar: 'الإجراءات' },
  'common.back': { en: 'Back', ar: 'رجوع' },
  'common.export': { en: 'Export', ar: 'تصدير' },
  'common.of': { en: 'of', ar: 'من' },
  'common.error': { en: 'Error', ar: 'خطأ' },
  'common.success': { en: 'Success', ar: 'نجاح' },
  // Training Module
  'training.title': { en: 'Training Management', ar: 'إدارة التدريب' },
  'training.subtitle': { en: 'Manage training records, courses, and training plans', ar: 'إدارة سجلات التدريب والدورات وخطط التدريب' },
  'training.tabs.records': { en: 'Training Records', ar: 'سجلات التدريب' },
  'training.tabs.trainers': { en: 'Trainers', ar: 'المدربين' },
  'training.tabs.syllabus': { en: 'Courses Syllabus', ar: 'مناهج الدورات' },
  'training.tabs.courses': { en: 'Courses List', ar: 'قائمة الدورات' },
  'training.tabs.plan': { en: 'Training Plan', ar: 'خطة التدريب' },
  'training.searchByName': { en: 'Search By Name', ar: 'بحث بالاسم' },
  'training.searchByDept': { en: 'Search By Department', ar: 'بحث بالقسم' },
  'training.searchByStation': { en: 'Search By Station', ar: 'بحث بالمحطة' },
  'training.selectEmployee': { en: 'Select an employee to view training records', ar: 'اختر موظف لعرض سجلات التدريب' },
  'training.linkId': { en: 'Link ID', ar: 'رقم الهوية' },
  'training.station': { en: 'Station', ar: 'المحطة' },
  'training.hireDate': { en: 'Hire Date', ar: 'تاريخ التعيين' },
  'training.mobile': { en: 'Mobile No.', ar: 'رقم الهاتف' },
  'training.jobFunction': { en: 'Job Function', ar: 'الوظيفة' },
  'training.jobFunctionLegend': { en: 'Job Function Legend', ar: 'دليل الوظائف' },
  'training.records.title': { en: 'Training Records', ar: 'سجلات التدريب' },
  'training.records.add': { en: 'Add Training Record', ar: 'إضافة سجل تدريب' },
  'training.courseName': { en: 'Course Name', ar: 'اسم الدورة' },
  'training.provider': { en: 'Provider', ar: 'مقدم الدورة' },
  'training.location': { en: 'Course Location', ar: 'موقع الدورة' },
  'training.startDate': { en: 'Start Date', ar: 'تاريخ البداية' },
  'training.endDate': { en: 'End Date', ar: 'تاريخ النهاية' },
  'training.plannedDate': { en: 'Planned Date', ar: 'التاريخ المخطط' },
  'training.result': { en: 'Result', ar: 'النتيجة' },
  'training.percentage': { en: 'Percentage', ar: 'النسبة' },
  'training.result.passed': { en: 'Passed', ar: 'ناجح' },
  'training.result.failed': { en: 'Failed', ar: 'راسب' },
  'training.result.pending': { en: 'Pending', ar: 'قيد الانتظار' },
  'training.noRecords': { en: 'No training records found', ar: 'لا توجد سجلات تدريب' },
  'training.fillRequired': { en: 'Please fill all required fields', ar: 'يرجى ملء جميع الحقول المطلوبة' },
  // Trainers
  'training.trainers.list': { en: 'Trainers List', ar: 'قائمة المدربين' },
  'training.trainers.add': { en: 'Add Trainer', ar: 'إضافة مدرب' },
  'training.trainers.addNew': { en: 'Add New Trainer', ar: 'إضافة مدرب جديد' },
  'training.trainers.edit': { en: 'Edit Trainer', ar: 'تعديل المدرب' },
  'training.trainers.photo': { en: 'Photo', ar: 'الصورة' },
  'training.trainers.name': { en: 'Name', ar: 'الاسم' },
  'training.trainers.provider': { en: 'Provider', ar: 'جهة العمل' },
  'training.trainers.jobTitle': { en: 'Job Title', ar: 'المسمى الوظيفي' },
  'training.trainers.email': { en: 'Email', ar: 'البريد الإلكتروني' },
  'training.trainers.status': { en: 'Status', ar: 'الحالة' },
  'training.trainers.id': { en: 'ID', ar: 'الرقم' },
  'training.trainers.title': { en: 'Title', ar: 'اللقب' },
  'training.trainers.firstName': { en: 'First Name', ar: 'الاسم الأول' },
  'training.trainers.lastName': { en: 'Last Name', ar: 'الاسم الأخير' },
  'training.trainers.officeNumber': { en: 'Office Number', ar: 'رقم المكتب' },
  'training.trainers.mobNumber': { en: 'Mobile Number', ar: 'رقم الجوال' },
  'training.trainers.siteAddress': { en: 'Site Address', ar: 'عنوان الموقع' },
  'training.trainers.uploadPhoto': { en: 'Upload Photo', ar: 'رفع صورة' },
  'training.trainers.deleteRecord': { en: 'Delete Record', ar: 'حذف السجل' },
  'training.trainers.saveAndNew': { en: 'Save and New', ar: 'حفظ وإضافة جديد' },
  'training.trainers.discard': { en: 'Discard', ar: 'تجاهل' },
  'training.trainers.record': { en: 'Record', ar: 'سجل' },
  'training.trainerAdded': { en: 'Trainer added successfully', ar: 'تم إضافة المدرب بنجاح' },
  'training.trainerUpdated': { en: 'Trainer updated successfully', ar: 'تم تحديث المدرب بنجاح' },
  'training.trainerDeleted': { en: 'Trainer deleted successfully', ar: 'تم حذف المدرب بنجاح' },
  'training.status.onJob': { en: 'On Job', ar: 'على رأس العمل' },
  'training.status.inactive': { en: 'Inactive', ar: 'غير نشط' },
  'training.status.active': { en: 'Active', ar: 'نشط' },
  // Syllabus
  'training.syllabus.title': { en: 'Course Syllabus', ar: 'منهج الدورة' },
  'training.syllabus.editedBy': { en: 'Edited By', ar: 'تم التعديل بواسطة' },
  'training.syllabus.courseCode': { en: 'Course Code', ar: 'كود الدورة' },
  'training.syllabus.courseInfo': { en: 'Course Information', ar: 'معلومات الدورة' },
  'training.syllabus.duration': { en: 'Course Duration', ar: 'مدة الدورة' },
  'training.syllabus.objective': { en: 'Course Objective', ar: 'هدف الدورة' },
  'training.syllabus.administration': { en: 'Course Administration', ar: 'إدارة الدورة' },
  'training.syllabus.exercises': { en: 'Exercises', ar: 'التمارين' },
  'training.syllabus.basicTopics': { en: 'Basic Topics', ar: 'المواضيع الأساسية' },
  'training.syllabus.intermediateTopics': { en: 'Intermediate Topics', ar: 'المواضيع المتوسطة' },
  'training.syllabus.advancedTopics': { en: 'Advanced Topics', ar: 'المواضيع المتقدمة' },
  'training.syllabus.reference': { en: 'Reference', ar: 'المراجع' },
  'training.syllabus.examination': { en: 'Examination', ar: 'الامتحان' },
  'training.syllabus.added': { en: 'Syllabus added successfully', ar: 'تم إضافة المنهج بنجاح' },
  'training.syllabus.updated': { en: 'Syllabus updated successfully', ar: 'تم تحديث المنهج بنجاح' },
  'training.syllabus.deleted': { en: 'Syllabus deleted successfully', ar: 'تم حذف المنهج بنجاح' },
  // Courses List
  'training.courses.search': { en: 'Search courses...', ar: 'بحث عن دورة...' },
  'training.courses.filterCategory': { en: 'Filter by Category', ar: 'تصفية حسب الفئة' },
  'training.courses.filterStatus': { en: 'Filter by Status', ar: 'تصفية حسب الحالة' },
  'training.courses.add': { en: 'Add Course', ar: 'إضافة دورة' },
  'training.courses.edit': { en: 'Edit Course', ar: 'تعديل الدورة' },
  'training.courses.view': { en: 'View Course', ar: 'عرض الدورة' },
  'training.courses.code': { en: 'Code', ar: 'الكود' },
  'training.courses.name': { en: 'Course Name', ar: 'اسم الدورة' },
  'training.courses.nameEn': { en: 'Name (English)', ar: 'الاسم (إنجليزي)' },
  'training.courses.nameAr': { en: 'Name (Arabic)', ar: 'الاسم (عربي)' },
  'training.courses.category': { en: 'Category', ar: 'الفئة' },
  'training.courses.duration': { en: 'Duration', ar: 'المدة' },
  'training.courses.method': { en: 'Method', ar: 'طريقة التدريب' },
  'training.courses.validity': { en: 'Validity Period', ar: 'فترة الصلاحية' },
  'training.courses.status': { en: 'Status', ar: 'الحالة' },
  'training.courses.description': { en: 'Description', ar: 'الوصف' },
  'training.courses.noResults': { en: 'No courses found', ar: 'لا توجد دورات' },
  'training.courses.methodsLegend': { en: 'Methods of Instructions', ar: 'طرق التدريب' },
  'training.courses.added': { en: 'Course added successfully', ar: 'تم إضافة الدورة بنجاح' },
  'training.courses.updated': { en: 'Course updated successfully', ar: 'تم تحديث الدورة بنجاح' },
  'training.courses.deleted': { en: 'Course deleted successfully', ar: 'تم حذف الدورة بنجاح' },
  'training.category.safety': { en: 'Safety', ar: 'السلامة' },
  'training.category.security': { en: 'Security', ar: 'الأمن' },
  'training.category.humanFactors': { en: 'Human Factors', ar: 'العوامل البشرية' },
  'training.category.technical': { en: 'Technical', ar: 'التقني' },
  // Training Plan
  'training.plan.addCourse': { en: 'Add New Course To Training Plan', ar: 'إضافة دورة جديدة لخطة التدريب' },
  'training.plan.viewPlan': { en: 'View Training Plan', ar: 'عرض خطة التدريب' },
  'training.plan.viewNextYear': { en: 'View Training Plan Next Year', ar: 'عرض خطة التدريب للعام القادم' },
  'training.plan.staffCourses': { en: 'Staff Planned Courses', ar: 'الدورات المخططة للموظفين' },
  'training.plan.staffReport': { en: 'Staff Planned Course Report', ar: 'تقرير الدورات المخططة للموظفين' },
  'training.plan.participants': { en: 'Participants', ar: 'المشاركين' },
  'training.plan.trainer': { en: 'Trainer', ar: 'المدرب' },
  'training.plan.scheduled': { en: 'Scheduled', ar: 'مجدول' },
  'training.plan.inProgress': { en: 'In Progress', ar: 'قيد التنفيذ' },
  'training.plan.completed': { en: 'Completed', ar: 'مكتمل' },
  'training.plan.cancelled': { en: 'Cancelled', ar: 'ملغي' },
  'training.plan.due': { en: 'Due', ar: 'مستحق' },
  'training.plan.overdue': { en: 'Overdue', ar: 'متأخر' },
  'training.plan.courseAdded': { en: 'Course added to plan successfully', ar: 'تم إضافة الدورة للخطة بنجاح' },
  'training.plan.employeeId': { en: 'Employee ID', ar: 'رقم الموظف' },
  'training.plan.employeeName': { en: 'Employee Name', ar: 'اسم الموظف' },
  'training.plan.department': { en: 'Department', ar: 'القسم' },
  'training.plan.dueDate': { en: 'Due Date', ar: 'تاريخ الاستحقاق' },
  'training.plan.totalPlanned': { en: 'Total Planned', ar: 'إجمالي المخطط' },
  'training.plan.totalStaff': { en: 'Total Staff', ar: 'إجمالي الموظفين' },
  'training.plan.coursesScheduled': { en: 'Scheduled', ar: 'مجدول' },
  'training.plan.coursesDue': { en: 'Due', ar: 'مستحق' },
  'training.plan.coursesOverdue': { en: 'Overdue', ar: 'متأخر' },
  // Loans module
  'loans.title': { en: 'Loans & Advances Management', ar: 'إدارة القروض والسلف' },
  'loans.subtitle': { en: 'Manage employee loans, advances and installments', ar: 'إدارة قروض وسلف وأقساط الموظفين' },
  'loans.tabs.loans': { en: 'Loans', ar: 'القروض' },
  'loans.tabs.advances': { en: 'Advances', ar: 'السلف' },
  'loans.tabs.installments': { en: 'Installments', ar: 'الأقساط' },
  'loans.tabs.reports': { en: 'Reports', ar: 'التقارير' },
  'loans.tabs.settings': { en: 'Settings', ar: 'الإعدادات' },
  'loans.search': { en: 'Search...', ar: 'بحث...' },
  'loans.filterStatus': { en: 'Filter by Status', ar: 'تصفية حسب الحالة' },
  'loans.loansList': { en: 'Loans List', ar: 'قائمة القروض' },
  'loans.addLoan': { en: 'Add Loan', ar: 'إضافة قرض' },
  'loans.loanId': { en: 'Loan ID', ar: 'رقم القرض' },
  'loans.advanceId': { en: 'Advance ID', ar: 'رقم السلفة' },
  'loans.employee': { en: 'Employee', ar: 'الموظف' },
  'loans.selectEmployee': { en: 'Select Employee', ar: 'اختر موظف' },
  'loans.loanType': { en: 'Loan Type', ar: 'نوع القرض' },
  'loans.amount': { en: 'Amount', ar: 'المبلغ' },
  'loans.installments': { en: 'Installments', ar: 'الأقساط' },
  'loans.installmentsCount': { en: 'Number of Installments', ar: 'عدد الأقساط' },
  'loans.monthlyPayment': { en: 'Monthly Payment', ar: 'القسط الشهري' },
  'loans.remaining': { en: 'Remaining', ar: 'المتبقي' },
  'loans.status': { en: 'Status', ar: 'الحالة' },
  'loans.reason': { en: 'Reason', ar: 'السبب' },
  'loans.startDate': { en: 'Start Date', ar: 'تاريخ البداية' },
  'loans.approvedBy': { en: 'Approved By', ar: 'موافق عليه بواسطة' },
  'loans.approvalDate': { en: 'Approval Date', ar: 'تاريخ الموافقة' },
  'loans.loanDetails': { en: 'Loan Details', ar: 'تفاصيل القرض' },
  'loans.fillRequired': { en: 'Please fill all required fields', ar: 'يرجى ملء جميع الحقول المطلوبة' },
  'loans.loanAdded': { en: 'Loan added successfully', ar: 'تم إضافة القرض بنجاح' },
  'loans.loanApproved': { en: 'Loan approved successfully', ar: 'تم الموافقة على القرض بنجاح' },
  'loans.loanRejected': { en: 'Loan rejected', ar: 'تم رفض القرض' },
  'loans.loanDeleted': { en: 'Loan deleted successfully', ar: 'تم حذف القرض بنجاح' },
  'loans.stats.totalLoans': { en: 'Total Loans', ar: 'إجمالي القروض' },
  'loans.stats.activeLoans': { en: 'Active Loans', ar: 'القروض النشطة' },
  'loans.stats.pendingLoans': { en: 'Pending Approvals', ar: 'بانتظار الموافقة' },
  'loans.stats.totalOutstanding': { en: 'Total Outstanding', ar: 'إجمالي المستحق' },
  'loans.maxAdvance': { en: 'Max Advance', ar: 'الحد الأقصى للسلفة' },
  'loans.advanceExceedsLimit': { en: 'Advance amount exceeds limit', ar: 'مبلغ السلفة يتجاوز الحد الأقصى' },
  'loans.advanceAdded': { en: 'Advance request added', ar: 'تم إضافة طلب السلفة' },
  'loans.advanceApproved': { en: 'Advance approved', ar: 'تم الموافقة على السلفة' },
  'loans.advanceRejected': { en: 'Advance rejected', ar: 'تم رفض السلفة' },
  'loans.advances.title': { en: 'Salary Advances', ar: 'السلف على الراتب' },
  'loans.advances.add': { en: 'Add Advance', ar: 'إضافة سلفة' },
  'loans.advances.total': { en: 'Total Advances', ar: 'إجمالي السلف' },
  'loans.advances.pending': { en: 'Pending', ar: 'قيد الانتظار' },
  'loans.advances.approved': { en: 'Approved Amount', ar: 'المبلغ الموافق عليه' },
  'loans.advances.deducted': { en: 'Deducted Amount', ar: 'المبلغ المخصوم' },
  'loans.advances.requestDate': { en: 'Request Date', ar: 'تاريخ الطلب' },
  'loans.advances.deductionMonth': { en: 'Deduction Month', ar: 'شهر الخصم' },
  'loans.advances.details': { en: 'Advance Details', ar: 'تفاصيل السلفة' },
  'loans.installments.title': { en: 'Installments Management', ar: 'إدارة الأقساط' },
  'loans.installments.total': { en: 'Total Installments', ar: 'إجمالي الأقساط' },
  'loans.installments.paidCount': { en: 'Paid', ar: 'مدفوعة' },
  'loans.installments.pendingCount': { en: 'Pending', ar: 'معلقة' },
  'loans.installments.overdueCount': { en: 'Overdue', ar: 'متأخرة' },
  'loans.installments.paidAmount': { en: 'Paid Amount', ar: 'المبلغ المدفوع' },
  'loans.installments.pendingAmount': { en: 'Pending Amount', ar: 'المبلغ المعلق' },
  'loans.installments.filterMonth': { en: 'Filter by Month', ar: 'تصفية حسب الشهر' },
  'loans.installments.number': { en: 'Installment #', ar: 'رقم القسط' },
  'loans.installments.dueDate': { en: 'Due Date', ar: 'تاريخ الاستحقاق' },
  'loans.installments.paidDate': { en: 'Paid Date', ar: 'تاريخ الدفع' },
  'loans.installments.markPaid': { en: 'Mark as Paid', ar: 'تحديد كمدفوع' },
  'loans.installments.paid': { en: 'Installment marked as paid', ar: 'تم تحديد القسط كمدفوع' },
  'loans.reports.filters': { en: 'Report Filters', ar: 'فلاتر التقرير' },
  'loans.reports.type': { en: 'Report Type', ar: 'نوع التقرير' },
  'loans.reports.monthly': { en: 'Monthly', ar: 'شهري' },
  'loans.reports.quarterly': { en: 'Quarterly', ar: 'ربع سنوي' },
  'loans.reports.yearly': { en: 'Yearly', ar: 'سنوي' },
  'loans.reports.custom': { en: 'Custom Range', ar: 'نطاق مخصص' },
  'loans.reports.dateFrom': { en: 'From Date', ar: 'من تاريخ' },
  'loans.reports.dateTo': { en: 'To Date', ar: 'إلى تاريخ' },
  'loans.reports.department': { en: 'Department', ar: 'القسم' },
  'loans.reports.totalLoans': { en: 'Total Loans', ar: 'إجمالي القروض' },
  'loans.reports.loansAmount': { en: 'Loans Amount', ar: 'مبلغ القروض' },
  'loans.reports.totalAdvances': { en: 'Total Advances', ar: 'إجمالي السلف' },
  'loans.reports.advancesAmount': { en: 'Advances Amount', ar: 'مبلغ السلف' },
  'loans.reports.installmentsCollected': { en: 'Installments Collected', ar: 'الأقساط المحصلة' },
  'loans.reports.collectedAmount': { en: 'Collected Amount', ar: 'المبلغ المحصل' },
  'loans.reports.monthlyLoans': { en: 'Monthly Loans & Advances', ar: 'القروض والسلف الشهرية' },
  'loans.reports.loanTypes': { en: 'Loans by Type', ar: 'القروض حسب النوع' },
  'loans.reports.collectionTrend': { en: 'Collection Trend', ar: 'اتجاه التحصيل' },
  'loans.reports.departmentLoans': { en: 'Loans by Department', ar: 'القروض حسب القسم' },
  'loans.reports.loansCount': { en: 'Loans Count', ar: 'عدد القروض' },
  'loans.reports.totalAmount': { en: 'Total Amount', ar: 'إجمالي المبلغ' },
  'loans.settings.general': { en: 'General Settings', ar: 'الإعدادات العامة' },
  'loans.settings.generalDesc': { en: 'Configure general loan and advance settings', ar: 'تكوين إعدادات القروض والسلف العامة' },
  'loans.settings.maxConcurrentLoans': { en: 'Max Concurrent Loans', ar: 'الحد الأقصى للقروض المتزامنة' },
  'loans.settings.advanceMaxPercent': { en: 'Advance Max % of Salary', ar: 'الحد الأقصى للسلفة % من الراتب' },
  'loans.settings.advanceDeductionMethod': { en: 'Advance Deduction Method', ar: 'طريقة خصم السلفة' },
  'loans.settings.immediate': { en: 'Immediate', ar: 'فوري' },
  'loans.settings.nextMonth': { en: 'Next Month', ar: 'الشهر التالي' },
  'loans.settings.autoDeduct': { en: 'Auto Deduct from Salary', ar: 'خصم تلقائي من الراتب' },
  'loans.settings.autoDeductDesc': { en: 'Automatically deduct installments from salary', ar: 'خصم الأقساط تلقائياً من الراتب' },
  'loans.settings.allowEarlyRepayment': { en: 'Allow Early Repayment', ar: 'السماح بالسداد المبكر' },
  'loans.settings.earlyRepaymentDesc': { en: 'Allow employees to pay off loans early', ar: 'السماح للموظفين بسداد القروض مبكراً' },
  'loans.settings.notifications': { en: 'Notifications', ar: 'الإشعارات' },
  'loans.settings.sendNotifications': { en: 'Send Notifications', ar: 'إرسال الإشعارات' },
  'loans.settings.notificationsDesc': { en: 'Send reminders before installment due dates', ar: 'إرسال تذكيرات قبل مواعيد استحقاق الأقساط' },
  'loans.settings.notifyBeforeDays': { en: 'Notify Before (Days)', ar: 'إشعار قبل (أيام)' },
  'loans.settings.guarantor': { en: 'Guarantor Settings', ar: 'إعدادات الضامن' },
  'loans.settings.requireGuarantor': { en: 'Require Guarantor', ar: 'يتطلب ضامن' },
  'loans.settings.guarantorDesc': { en: 'Require a guarantor for loan applications', ar: 'يتطلب وجود ضامن لطلبات القروض' },
  'loans.settings.guarantorMinService': { en: 'Guarantor Min Service (Months)', ar: 'الحد الأدنى لخدمة الضامن (شهور)' },
  'loans.settings.loanTypes': { en: 'Loan Types', ar: 'أنواع القروض' },
  'loans.settings.loanTypesDesc': { en: 'Configure settings for each loan type', ar: 'تكوين إعدادات كل نوع قرض' },
  'loans.settings.selectLoanType': { en: 'Select Loan Type', ar: 'اختر نوع القرض' },
  'loans.settings.nameAr': { en: 'Name (Arabic)', ar: 'الاسم (عربي)' },
  'loans.settings.nameEn': { en: 'Name (English)', ar: 'الاسم (إنجليزي)' },
  'loans.settings.isActive': { en: 'Active', ar: 'نشط' },
  'loans.settings.maxAmount': { en: 'Max Amount', ar: 'الحد الأقصى للمبلغ' },
  'loans.settings.maxInstallments': { en: 'Max Installments', ar: 'الحد الأقصى للأقساط' },
  'loans.settings.interestRate': { en: 'Interest Rate %', ar: 'نسبة الفائدة %' },
  'loans.settings.minServiceMonths': { en: 'Min Service (Months)', ar: 'الحد الأدنى للخدمة (شهور)' },
  'loans.settings.maxPercentOfSalary': { en: 'Max % of Salary', ar: 'الحد الأقصى % من الراتب' },
  'loans.settings.requiresApproval': { en: 'Requires Approval', ar: 'يتطلب موافقة' },
  'loans.settings.saveAll': { en: 'Save All Settings', ar: 'حفظ جميع الإعدادات' },
  'loans.settings.saved': { en: 'Settings saved successfully', ar: 'تم حفظ الإعدادات بنجاح' },
  // Reports Module
  'reports.title': { en: 'Reports & Analytics', ar: 'التقارير والتحليلات' },
  'reports.subtitle': { en: 'Comprehensive reports and analytics for HR management', ar: 'تقارير وتحليلات شاملة لإدارة الموارد البشرية' },
  'reports.tabs.employees': { en: 'Employees', ar: 'الموظفين' },
  'reports.tabs.attendance': { en: 'Attendance', ar: 'الحضور' },
  'reports.tabs.leaves': { en: 'Leaves', ar: 'الإجازات' },
  'reports.tabs.salaries': { en: 'Salaries', ar: 'الرواتب' },
  'reports.tabs.performance': { en: 'Performance', ar: 'الأداء' },
  'reports.tabs.training': { en: 'Training', ar: 'التدريب' },
  'reports.thisWeek': { en: 'This Week', ar: 'هذا الأسبوع' },
  'reports.thisMonth': { en: 'This Month', ar: 'هذا الشهر' },
  'reports.thisQuarter': { en: 'This Quarter', ar: 'هذا الربع' },
  'reports.thisYear': { en: 'This Year', ar: 'هذه السنة' },
  'reports.allDepartments': { en: 'All Departments', ar: 'جميع الأقسام' },
  'reports.print': { en: 'Print', ar: 'طباعة' },
  'reports.exportPDF': { en: 'Export PDF', ar: 'تصدير PDF' },
  'reports.exportExcel': { en: 'Export Excel', ar: 'تصدير Excel' },
  'reports.totalEmployees': { en: 'Total Employees', ar: 'إجمالي الموظفين' },
  'reports.newHires': { en: 'New Hires', ar: 'التعيينات الجديدة' },
  'reports.terminated': { en: 'Terminated', ar: 'المنتهية خدماتهم' },
  'reports.departments': { en: 'Departments', ar: 'الأقسام' },
  'reports.headcountTrend': { en: 'Headcount Trend', ar: 'اتجاه عدد الموظفين' },
  'reports.departmentDistribution': { en: 'Department Distribution', ar: 'توزيع الأقسام' },
  'reports.turnoverAnalysis': { en: 'Turnover Analysis', ar: 'تحليل دوران الموظفين' },
  'reports.genderDistribution': { en: 'Gender Distribution', ar: 'توزيع الجنس' },
  'reports.employees': { en: 'Employees', ar: 'الموظفين' },
  'reports.hired': { en: 'Hired', ar: 'تم تعيينهم' },
  'reports.left': { en: 'Left', ar: 'تركوا العمل' },
  'reports.male': { en: 'Male', ar: 'ذكور' },
  'reports.female': { en: 'Female', ar: 'إناث' },
  'reports.avgAttendance': { en: 'Avg Attendance', ar: 'متوسط الحضور' },
  'reports.avgLateArrivals': { en: 'Avg Late Arrivals', ar: 'متوسط التأخير' },
  'reports.avgAbsence': { en: 'Avg Absence', ar: 'متوسط الغياب' },
  'reports.totalOvertime': { en: 'Total Overtime', ar: 'إجمالي العمل الإضافي' },
  'reports.dailyAttendance': { en: 'Daily Attendance', ar: 'الحضور اليومي' },
  'reports.statusDistribution': { en: 'Status Distribution', ar: 'توزيع الحالة' },
  'reports.attendanceTrend': { en: 'Attendance Trend', ar: 'اتجاه الحضور' },
  'reports.overtimeHours': { en: 'Overtime Hours', ar: 'ساعات العمل الإضافي' },
  'reports.present': { en: 'Present', ar: 'حاضر' },
  'reports.absent': { en: 'Absent', ar: 'غائب' },
  'reports.late': { en: 'Late', ar: 'متأخر' },
  'reports.onLeave': { en: 'On Leave', ar: 'في إجازة' },
  'reports.attendanceRate': { en: 'Attendance Rate', ar: 'نسبة الحضور' },
  'reports.hours': { en: 'Hours', ar: 'ساعات' },
  'reports.totalRequests': { en: 'Total Requests', ar: 'إجمالي الطلبات' },
  'reports.approved': { en: 'Approved', ar: 'موافق عليها' },
  'reports.rejected': { en: 'Rejected', ar: 'مرفوضة' },
  'reports.pending': { en: 'Pending', ar: 'معلقة' },
  'reports.leavesByType': { en: 'Leaves by Type', ar: 'الإجازات حسب النوع' },
  'reports.monthlyRequests': { en: 'Monthly Requests', ar: 'الطلبات الشهرية' },
  'reports.leaveBalanceByDept': { en: 'Leave Balance by Department', ar: 'رصيد الإجازات حسب القسم' },
  'reports.requests': { en: 'Requests', ar: 'الطلبات' },
  'reports.usedDays': { en: 'Used Days', ar: 'الأيام المستخدمة' },
  'reports.remainingDays': { en: 'Remaining Days', ar: 'الأيام المتبقية' },
  'reports.totalPayroll': { en: 'Total Payroll', ar: 'إجمالي الرواتب' },
  'reports.avgSalary': { en: 'Avg Salary', ar: 'متوسط الراتب' },
  'reports.totalAllowances': { en: 'Total Allowances', ar: 'إجمالي البدلات' },
  'reports.totalDeductions': { en: 'Total Deductions', ar: 'إجمالي الخصومات' },
  'reports.payrollTrend': { en: 'Payroll Trend', ar: 'اتجاه الرواتب' },
  'reports.salaryByDept': { en: 'Salary by Department', ar: 'الرواتب حسب القسم' },
  'reports.salaryDistribution': { en: 'Salary Distribution', ar: 'توزيع الرواتب' },
  'reports.netSalary': { en: 'Net Salary', ar: 'صافي الراتب' },
  'reports.basicSalary': { en: 'Basic Salary', ar: 'الراتب الأساسي' },
  'reports.avgRating': { en: 'Avg Rating', ar: 'متوسط التقييم' },
  'reports.topPerformers': { en: 'Top Performers', ar: 'أفضل الموظفين' },
  'reports.improvement': { en: 'Improvement', ar: 'التحسن' },
  'reports.reviewsCompleted': { en: 'Reviews Completed', ar: 'التقييمات المكتملة' },
  'reports.ratingDistribution': { en: 'Rating Distribution', ar: 'توزيع التقييمات' },
  'reports.criteriaAnalysis': { en: 'Criteria Analysis', ar: 'تحليل المعايير' },
  'reports.deptPerformance': { en: 'Department Performance', ar: 'أداء الأقسام' },
  'reports.quarterlyTrend': { en: 'Quarterly Trend', ar: 'الاتجاه الربع سنوي' },
  'reports.score': { en: 'Score', ar: 'الدرجة' },
  'reports.avgScore': { en: 'Avg Score', ar: 'متوسط الدرجة' },
  'reports.totalCourses': { en: 'Total Courses', ar: 'إجمالي الدورات' },
  'reports.trainedEmployees': { en: 'Trained Employees', ar: 'الموظفين المدربين' },
  'reports.totalHours': { en: 'Total Hours', ar: 'إجمالي الساعات' },
  'reports.certifications': { en: 'Certifications', ar: 'الشهادات' },
  'reports.courseCompletion': { en: 'Course Completion', ar: 'إتمام الدورات' },
  'reports.trainingByCategory': { en: 'Training by Category', ar: 'التدريب حسب الفئة' },
  'reports.trainingByDept': { en: 'Training by Department', ar: 'التدريب حسب القسم' },
  'reports.budgetVsSpent': { en: 'Budget vs Spent', ar: 'الميزانية مقابل المصروف' },
  'reports.enrolled': { en: 'Enrolled', ar: 'المسجلين' },
  'reports.completed': { en: 'Completed', ar: 'المكتملة' },
  'reports.trainingHours': { en: 'Training Hours', ar: 'ساعات التدريب' },
  'reports.budget': { en: 'Budget', ar: 'الميزانية' },
  'reports.spent': { en: 'Spent', ar: 'المصروف' },
  'months.jan': { en: 'Jan', ar: 'يناير' },
  'months.feb': { en: 'Feb', ar: 'فبراير' },
  'months.mar': { en: 'Mar', ar: 'مارس' },
  'months.apr': { en: 'Apr', ar: 'أبريل' },
  'months.may': { en: 'May', ar: 'مايو' },
  'months.jun': { en: 'Jun', ar: 'يونيو' },
  'days.sun': { en: 'Sun', ar: 'الأحد' },
  'days.mon': { en: 'Mon', ar: 'الاثنين' },
  'days.tue': { en: 'Tue', ar: 'الثلاثاء' },
  'days.wed': { en: 'Wed', ar: 'الأربعاء' },
  'days.thu': { en: 'Thu', ar: 'الخميس' },
  'leave.types.personal': { en: 'Personal', ar: 'شخصية' },
  // Salaries Module
  'salaries.title': { en: 'Salary Management', ar: 'إدارة الرواتب' },
  'salaries.subtitle': { en: 'Process payroll, manage salary slips, allowances and deductions', ar: 'معالجة الرواتب وإدارة قسائم الرواتب والبدلات والخصومات' },
  'salaries.tabs.payroll': { en: 'Payroll Processing', ar: 'مسير الرواتب' },
  'salaries.tabs.slips': { en: 'Salary Slips', ar: 'قسائم الرواتب' },
  'salaries.tabs.allowances': { en: 'Allowances & Deductions', ar: 'البدلات والخصومات' },
  'salaries.tabs.structure': { en: 'Salary Structure', ar: 'هيكل الرواتب' },
  'salaries.tabs.history': { en: 'Payroll History', ar: 'سجل الرواتب' },
  'salaries.months.jul': { en: 'Jul', ar: 'يوليو' },
  'salaries.months.aug': { en: 'Aug', ar: 'أغسطس' },
  'salaries.months.sep': { en: 'Sep', ar: 'سبتمبر' },
  'salaries.months.oct': { en: 'Oct', ar: 'أكتوبر' },
  'salaries.months.nov': { en: 'Nov', ar: 'نوفمبر' },
  'salaries.months.dec': { en: 'Dec', ar: 'ديسمبر' },
  // Payroll Processing
  'salaries.stats.totalEmployees': { en: 'Total Employees', ar: 'إجمالي الموظفين' },
  'salaries.stats.totalPayroll': { en: 'Total Payroll', ar: 'إجمالي الرواتب' },
  'salaries.stats.totalAllowances': { en: 'Total Allowances', ar: 'إجمالي البدلات' },
  'salaries.stats.pendingApproval': { en: 'Pending Approval', ar: 'بانتظار الموافقة' },
  'salaries.runPayroll': { en: 'Run Payroll', ar: 'تشغيل مسير الرواتب' },
  'salaries.month': { en: 'Month', ar: 'الشهر' },
  'salaries.year': { en: 'Year', ar: 'السنة' },
  'salaries.processPayroll': { en: 'Process Payroll', ar: 'معالجة الرواتب' },
  'salaries.viewDetails': { en: 'View Details', ar: 'عرض التفاصيل' },
  'salaries.payrollDetails': { en: 'Payroll Details', ar: 'تفاصيل مسير الرواتب' },
  'salaries.recentRuns': { en: 'Recent Payroll Runs', ar: 'عمليات المسير الأخيرة' },
  'salaries.period': { en: 'Period', ar: 'الفترة' },
  'salaries.employeesCount': { en: 'Employees', ar: 'الموظفين' },
  'salaries.totalBasic': { en: 'Total Basic', ar: 'إجمالي الأساسي' },
  'salaries.allowancesTotal': { en: 'Allowances', ar: 'البدلات' },
  'salaries.deductionsTotal': { en: 'Deductions', ar: 'الخصومات' },
  'salaries.netSalary': { en: 'Net Salary', ar: 'صافي الراتب' },
  'salaries.statusLabel': { en: 'Status', ar: 'الحالة' },
  'salaries.approve': { en: 'Approve', ar: 'اعتماد' },
  'salaries.status.draft': { en: 'Draft', ar: 'مسودة' },
  'salaries.status.processing': { en: 'Processing', ar: 'قيد المعالجة' },
  'salaries.status.completed': { en: 'Completed', ar: 'مكتمل' },
  'salaries.status.approved': { en: 'Approved', ar: 'معتمد' },
  'salaries.payrollStarted': { en: 'Payroll Processing Started', ar: 'بدأت معالجة الرواتب' },
  'salaries.payrollStartedDesc': { en: 'Payroll is being processed for the selected period', ar: 'جاري معالجة الرواتب للفترة المحددة' },
  'salaries.employee': { en: 'Employee', ar: 'الموظف' },
  'salaries.department': { en: 'Department', ar: 'القسم' },
  'salaries.basicSalary': { en: 'Basic Salary', ar: 'الراتب الأساسي' },
  // Salary Slips
  'salaries.searchEmployee': { en: 'Search employee...', ar: 'بحث عن موظف...' },
  'salaries.printAll': { en: 'Print All', ar: 'طباعة الكل' },
  'salaries.exportAll': { en: 'Export All', ar: 'تصدير الكل' },
  'salaries.slipsTitle': { en: 'Salary Slips', ar: 'قسائم الرواتب' },
  'salaries.employeeId': { en: 'Employee ID', ar: 'رقم الموظف' },
  'salaries.totalEarnings': { en: 'Total Earnings', ar: 'إجمالي المستحقات' },
  'salaries.totalDeductionsLabel': { en: 'Total Deductions', ar: 'إجمالي الخصومات' },
  'salaries.slipDetail': { en: 'Salary Slip', ar: 'قسيمة الراتب' },
  'salaries.earnings': { en: 'Earnings', ar: 'المستحقات' },
  'salaries.deductionsLabel': { en: 'Deductions', ar: 'الخصومات' },
  'salaries.housingAllowance': { en: 'Housing Allowance', ar: 'بدل السكن' },
  'salaries.transportAllowance': { en: 'Transport Allowance', ar: 'بدل المواصلات' },
  'salaries.mealAllowance': { en: 'Meal Allowance', ar: 'بدل الوجبات' },
  'salaries.otherAllowances': { en: 'Other Allowances', ar: 'بدلات أخرى' },
  'salaries.socialInsurance': { en: 'Social Insurance', ar: 'التأمين الاجتماعي' },
  'salaries.taxes': { en: 'Income Tax', ar: 'ضريبة الدخل' },
  'salaries.loanDeduction': { en: 'Loan Deduction', ar: 'خصم القرض' },
  'salaries.otherDeductions': { en: 'Other Deductions', ar: 'خصومات أخرى' },
  'salaries.overtime': { en: 'Overtime', ar: 'العمل الإضافي' },
  'salaries.bonus': { en: 'Bonus', ar: 'المكافأة' },
  'salaries.print': { en: 'Print', ar: 'طباعة' },
  'salaries.download': { en: 'Download', ar: 'تحميل' },
  // Allowances & Deductions
  'salaries.allowancesTypes': { en: 'Allowance Types', ar: 'أنواع البدلات' },
  'salaries.deductionsTypes': { en: 'Deduction Types', ar: 'أنواع الخصومات' },
  'salaries.activeItems': { en: 'active', ar: 'نشط' },
  'salaries.addItem': { en: 'Add Item', ar: 'إضافة عنصر' },
  'salaries.addAllowance': { en: 'Add Allowance', ar: 'إضافة بدل' },
  'salaries.addDeduction': { en: 'Add Deduction', ar: 'إضافة خصم' },
  'salaries.nameAr': { en: 'Name (Arabic)', ar: 'الاسم (عربي)' },
  'salaries.nameEn': { en: 'Name (English)', ar: 'الاسم (إنجليزي)' },
  'salaries.calculationType': { en: 'Calculation Type', ar: 'نوع الحساب' },
  'salaries.fixedAmount': { en: 'Fixed Amount', ar: 'مبلغ ثابت' },
  'salaries.percentageOfBasic': { en: '% of Basic', ar: '% من الأساسي' },
  'salaries.defaultValue': { en: 'Default Value', ar: 'القيمة الافتراضية' },
  'salaries.appliesTo': { en: 'Applies To', ar: 'ينطبق على' },
  'salaries.appliesAll': { en: 'All Employees', ar: 'جميع الموظفين' },
  'salaries.appliesManagers': { en: 'Managers Only', ar: 'المدراء فقط' },
  'salaries.appliesField': { en: 'Field Workers', ar: 'العاملين ميدانياً' },
  'salaries.appliesOptional': { en: 'Optional', ar: 'اختياري' },
  'salaries.appliesVariable': { en: 'Variable', ar: 'متغير' },
  'salaries.isTaxable': { en: 'Taxable', ar: 'خاضع للضريبة' },
  'salaries.taxable': { en: 'Taxable', ar: 'خاضع للضريبة' },
  'salaries.yes': { en: 'Yes', ar: 'نعم' },
  'salaries.no': { en: 'No', ar: 'لا' },
  'salaries.active': { en: 'Active', ar: 'نشط' },
  'salaries.inactive': { en: 'Inactive', ar: 'غير نشط' },
  'salaries.itemName': { en: 'Item Name', ar: 'اسم العنصر' },
  'salaries.itemAdded': { en: 'Item added successfully', ar: 'تم إضافة العنصر بنجاح' },
  // Salary Structure
  'salaries.totalGrades': { en: 'Total Grades', ar: 'إجمالي الدرجات' },
  'salaries.totalAssigned': { en: 'Total Assigned', ar: 'إجمالي المعينين' },
  'salaries.salaryRange': { en: 'Salary Range', ar: 'نطاق الرواتب' },
  'salaries.gradesTitle': { en: 'Salary Grades', ar: 'الدرجات الوظيفية' },
  'salaries.addGrade': { en: 'Add Grade', ar: 'إضافة درجة' },
  'salaries.gradeNameAr': { en: 'Grade Name (Arabic)', ar: 'اسم الدرجة (عربي)' },
  'salaries.gradeNameEn': { en: 'Grade Name (English)', ar: 'اسم الدرجة (إنجليزي)' },
  'salaries.gradeName': { en: 'Grade Name', ar: 'اسم الدرجة' },
  'salaries.gradeLevel': { en: 'Level', ar: 'المستوى' },
  'salaries.minSalary': { en: 'Min Salary', ar: 'الحد الأدنى' },
  'salaries.maxSalary': { en: 'Max Salary', ar: 'الحد الأقصى' },
  'salaries.housingPercent': { en: 'Housing %', ar: 'السكن %' },
  'salaries.transportFixed': { en: 'Transport', ar: 'المواصلات' },
  'salaries.mealFixed': { en: 'Meal', ar: 'الوجبات' },
  'salaries.employeesInGrade': { en: 'Employees', ar: 'الموظفين' },
  'salaries.gradeAdded': { en: 'Grade added successfully', ar: 'تم إضافة الدرجة بنجاح' },
  // Payroll History
  'salaries.annualPayroll': { en: 'Annual Payroll', ar: 'الرواتب السنوية' },
  'salaries.avgMonthly': { en: 'Avg Monthly', ar: 'المتوسط الشهري' },
  'salaries.yearlyGrowth': { en: 'Yearly Growth', ar: 'النمو السنوي' },
  'salaries.avgPerEmployee': { en: 'Avg per Employee', ar: 'المتوسط للموظف' },
  'salaries.payrollTrend': { en: 'Payroll Trend', ar: 'اتجاه الرواتب' },
  'salaries.netTrend': { en: 'Net Salary Trend', ar: 'اتجاه صافي الراتب' },
  'salaries.employeeHistory': { en: 'Employee Salary History', ar: 'سجل رواتب الموظفين' },
  'salaries.change': { en: 'Change', ar: 'التغيير' },
  'salaries.itemUpdated': { en: 'Item updated successfully', ar: 'تم تحديث العنصر بنجاح' },
  'salaries.editItem': { en: 'Edit Item', ar: 'تعديل العنصر' },
  'salaries.editGrade': { en: 'Edit Grade', ar: 'تعديل الدرجة' },
  'salaries.gradeUpdated': { en: 'Grade updated successfully', ar: 'تم تحديث الدرجة بنجاح' },
  // Salary Reports Page
  'salaryReports.title': { en: 'Salary Reports', ar: 'تقارير الرواتب' },
  'salaryReports.subtitle': { en: 'Comprehensive salary analysis and payroll reports', ar: 'تحليلات شاملة للرواتب وتقارير المرتبات' },
  'salaryReports.overview': { en: 'Overview', ar: 'نظرة عامة' },
  'salaryReports.byDepartment': { en: 'By Department', ar: 'حسب القسم' },
  'salaryReports.details': { en: 'Details', ar: 'التفاصيل' },
  'salaryReports.comparison': { en: 'Comparison', ar: 'المقارنة' },
  'salaryReports.allowancesAnalysis': { en: 'Allowances Analysis', ar: 'تحليل البدلات' },
  'salaryReports.deptCostComparison': { en: 'Department Cost Comparison', ar: 'مقارنة تكاليف الأقسام' },
  'salaryReports.deptSummary': { en: 'Department Summary', ar: 'ملخص الأقسام' },
  'salaryReports.employeesCount': { en: 'Employees', ar: 'عدد الموظفين' },
  'salaryReports.costPercentage': { en: 'Cost %', ar: 'نسبة التكلفة' },
  'salaryReports.employeeSalaryDetails': { en: 'Employee Salary Details', ar: 'تفاصيل رواتب الموظفين' },
  'salaryReports.yearOverYear': { en: 'Year-over-Year Comparison', ar: 'مقارنة سنوية' },
  'salaryReports.currentYear': { en: 'Current Year', ar: 'السنة الحالية' },
  'salaryReports.previousYear': { en: 'Previous Year', ar: 'السنة السابقة' },
  'salaryReports.growthRate': { en: 'Payroll Growth Rate', ar: 'معدل نمو الرواتب' },
  'salaryReports.vsLastYear': { en: 'vs last year', ar: 'مقارنة بالسنة الماضية' },
  'salaryReports.avgIncrease': { en: 'Avg Salary Increase', ar: 'متوسط زيادة الراتب' },
  'salaryReports.perEmployee': { en: 'per employee', ar: 'لكل موظف' },
  'salaryReports.newPositions': { en: 'New Positions', ar: 'وظائف جديدة' },
  'salaryReports.thisYear': { en: 'this year', ar: 'هذه السنة' },
  'salaryReports.allowanceBreakdown': { en: 'Allowance Breakdown', ar: 'تفصيل البدلات' },
  'salaryReports.deductionBreakdown': { en: 'Deduction Breakdown', ar: 'تفصيل الخصومات' },
  'salaryReports.monthlyAllowanceTrend': { en: 'Monthly Allowances vs Deductions', ar: 'البدلات مقابل الخصومات الشهرية' },
  // Leave Balance Tab
  'leaveBalance.year': { en: 'Year', ar: 'السنة' },
  'leaveBalance.annualLeave': { en: 'Annual Leave', ar: 'الإجازة السنوية' },
  'leaveBalance.sickLeave': { en: 'Sick Leave', ar: 'الإجازة المرضية' },
  'leaveBalance.casualLeave': { en: 'Casual Leave', ar: 'الإجازة العارضة' },
  'leaveBalance.permissions': { en: 'Permissions', ar: 'الأذونات' },
  'leaveBalance.total': { en: 'Total', ar: 'الإجمالي' },
  'leaveBalance.used': { en: 'Used', ar: 'المستخدم' },
  'leaveBalance.remaining': { en: 'Remaining', ar: 'المتبقي' },
  'leaveBalance.days': { en: 'days', ar: 'يوم' },
  'leaveBalance.hours': { en: 'hours', ar: 'ساعة' },
  'leaveBalance.saveBalance': { en: 'Save Balance', ar: 'حفظ الرصيد' },
  'leaveBalance.saved': { en: 'Saved', ar: 'تم الحفظ' },
  'leaveBalance.savedMessage': { en: 'Leave balance saved successfully', ar: 'تم حفظ رصيد الإجازات بنجاح' },
  'leaveBalance.balanceHistory': { en: 'Balance History', ar: 'سجل الأرصدة' },
  'leaveBalance.historyTitle': { en: 'Balance History (Current Year + Previous 4 Years)', ar: 'سجل الأرصدة (السنة الحالية + 4 سنوات سابقة)' },
  'leaveBalance.showing': { en: 'Showing', ar: 'عرض' },
  'leaveBalance.yearsLabel': { en: 'year(s)', ar: 'سنة/سنوات' },
  'leaveBalance.currentYear': { en: 'Current Year', ar: 'السنة الحالية' },
  'leaveBalance.noHistory': { en: 'No balance history found', ar: 'لا يوجد سجل أرصدة' },
  // Leave Record Tab
  'leaveRecord.leaves': { en: 'Leaves', ar: 'الإجازات' },
  'leaveRecord.permissions': { en: 'Permissions', ar: 'الأذونات' },
  'leaveRecord.extraDays': { en: 'Extra Days', ar: 'الأيام الإضافية' },
  'leaveRecord.annualLeaveBalance': { en: 'Annual Leave Balance', ar: 'رصيد الإجازات السنوية' },
  'leaveRecord.permissionsBalance': { en: 'Permissions Balance', ar: 'رصيد الأذونات' },
  'leaveRecord.extraDaysLabel': { en: 'Extra Days', ar: 'الأيام الإضافية' },
  'leaveRecord.dayAvailable': { en: 'day available', ar: 'يوم متاح' },
  'leaveRecord.hourAvailable': { en: 'hour available', ar: 'ساعة متاحة' },
  'leaveRecord.dayAdded': { en: 'day added', ar: 'يوم مضاف' },
  'leaveRecord.approvedLeaves': { en: 'Approved', ar: 'موافق عليها' },
  'leaveRecord.pendingLeaves': { en: 'Pending', ar: 'قيد المراجعة' },
  'leaveRecord.rejectedLeaves': { en: 'Rejected', ar: 'مرفوضة' },
  'leaveRecord.approvedLabel': { en: 'Approved', ar: 'موافق عليها' },
  'leaveRecord.pendingLabel': { en: 'Pending', ar: 'قيد المراجعة' },
  'leaveRecord.rejectedLabel': { en: 'Rejected', ar: 'مرفوضة' },
  'leaveRecord.leaveType': { en: 'Leave Type', ar: 'نوع الإجازة' },
  'leaveRecord.startDate': { en: 'Start Date', ar: 'تاريخ البداية' },
  'leaveRecord.endDate': { en: 'End Date', ar: 'تاريخ النهاية' },
  'leaveRecord.days': { en: 'Days', ar: 'الأيام' },
  'leaveRecord.status': { en: 'Status', ar: 'الحالة' },
  'leaveRecord.reason': { en: 'Reason', ar: 'السبب' },
  'leaveRecord.notes': { en: 'Notes', ar: 'ملاحظات' },
  'leaveRecord.permType': { en: 'Type', ar: 'النوع' },
  'leaveRecord.date': { en: 'Date', ar: 'التاريخ' },
  'leaveRecord.time': { en: 'Time', ar: 'الوقت' },
  'leaveRecord.duration': { en: 'Duration', ar: 'المدة' },
  'leaveRecord.extraDaysCurrentYear': { en: 'Extra Days for Current Year', ar: 'الأيام الإضافية للسنة الحالية' },
  'leaveRecord.approvedDays': { en: 'Approved Days', ar: 'يوم موافق عليه' },
  'leaveRecord.pendingDays': { en: 'Pending Days', ar: 'يوم قيد المراجعة' },
  'leaveRecord.totalAddedDays': { en: 'Total Added Days', ar: 'إجمالي الأيام المضافة' },
  'leaveRecord.additionType': { en: 'Addition Type', ar: 'نوع الإضافة' },
  'leaveRecord.year': { en: 'Year', ar: 'السنة' },
  // Departments Tab
  'departments.totalEmployees': { en: 'Total Employees', ar: 'إجمالي الموظفين' },
  'departments.inDepartment': { en: 'In this department', ar: 'في هذا القسم' },
  'departments.activeEmployees': { en: 'Active Employees', ar: 'الموظفين النشطين' },
  'departments.currentlyActive': { en: 'Currently active', ar: 'نشط حالياً' },
  'departments.avgPerformance': { en: 'Avg Performance', ar: 'متوسط الأداء' },
  'departments.performanceScore': { en: 'Performance score', ar: 'درجة الأداء' },
  'departments.growthRate': { en: 'Growth Rate', ar: 'معدل النمو' },
  'departments.thisYear': { en: 'This year', ar: 'هذا العام' },
  'departments.departmentInfo': { en: 'Department Information', ar: 'بيانات القسم' },
  'departments.nameAr': { en: 'Department Name (Arabic)', ar: 'اسم القسم بالعربي' },
  'departments.nameEn': { en: 'Department Name (English)', ar: 'اسم القسم بالإنجليزي' },
  'departments.manager': { en: 'Department Manager', ar: 'مدير القسم' },
  'departments.accessCodes': { en: 'Department Access Codes', ar: 'أكواد الأقسام' },
  'departments.save': { en: 'Save Department', ar: 'حفظ القسم' },
  // Departments Page
  'departmentsPage.title': { en: 'Departments Management', ar: 'إدارة الأقسام' },
  'departmentsPage.subtitle': { en: 'Manage departments, assign managers, and track analytics', ar: 'إدارة الأقسام وتعيين المديرين ومتابعة الإحصائيات' },
  'departmentsPage.totalDepts': { en: 'Total Departments', ar: 'إجمالي الأقسام' },
  'departmentsPage.registeredDepts': { en: 'Registered departments', ar: 'أقسام مسجلة' },
  'departmentsPage.totalEmps': { en: 'Total Employees', ar: 'إجمالي الموظفين' },
  'departmentsPage.acrossAllDepts': { en: 'Across all departments', ar: 'في جميع الأقسام' },
  'departmentsPage.avgSize': { en: 'Average Size', ar: 'متوسط الحجم' },
  'departmentsPage.empsPerDept': { en: 'Employees per department', ar: 'موظف لكل قسم' },
  'departmentsPage.managers': { en: 'Managers', ar: 'المديرين' },
  'departmentsPage.uniqueManagers': { en: 'Unique managers', ar: 'مدير مختلف' },
  'departmentsPage.addDept': { en: 'Add New Department', ar: 'إضافة قسم جديد' },
  'departmentsPage.editDept': { en: 'Edit Department', ar: 'تعديل القسم' },
  'departmentsPage.distribution': { en: 'Employee Distribution', ar: 'توزيع الموظفين' },
  'departmentsPage.deptList': { en: 'Departments List', ar: 'قائمة الأقسام' },
  'departmentsPage.deptNameAr': { en: 'Name (Arabic)', ar: 'الاسم بالعربي' },
  'departmentsPage.deptNameEn': { en: 'Name (English)', ar: 'الاسم بالإنجليزي' },
  'departmentsPage.deptManager': { en: 'Manager', ar: 'المدير' },
  'departmentsPage.empCount': { en: 'Employees', ar: 'عدد الموظفين' },
  'departmentsPage.actions': { en: 'Actions', ar: 'الإجراءات' },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
