import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<string, Record<Language, string>> = {
  'app.title': { en: 'HR Management System', ar: 'نظام إدارة الموارد البشرية' },
  'nav.dashboard': { en: 'Dashboard', ar: 'لوحة التحكم' },
  'nav.employees': { en: 'Employees', ar: 'الموظفين' },
  'nav.departments': { en: 'Departments', ar: 'الأقسام' },
  'nav.attendance': { en: 'Attendance', ar: 'الحضور والانصراف' },
  'nav.missions': { en: 'Mission Requests', ar: 'طلبات المأمورية' },
  'nav.leaves': { en: 'Leaves', ar: 'الإجازات' },
  'nav.permissions': { en: 'Permissions', ar: 'الأذونات' },
  'nav.salaries': { en: 'Salaries', ar: 'الرواتب' },
  'nav.salaryReports': { en: 'Salary Reports', ar: 'تقارير الرواتب' },
  'nav.loans': { en: 'Loans', ar: 'القروض' },
  'nav.recruitment': { en: 'Recruitment', ar: 'التوظيف' },
  'nav.performance': { en: 'Performance', ar: 'تقييم الأداء' },
  'nav.assets': { en: 'Assets', ar: 'الأصول' },
  'nav.uniforms': { en: 'Uniforms', ar: 'يونيفورم الموظفين' },
  'nav.documents': { en: 'Documents', ar: 'المستندات' },
  'nav.reports': { en: 'Reports', ar: 'التقارير' },
  'nav.training': { en: 'Training', ar: 'التدريب' },
  'nav.configurations': { en: 'CONFIGURATIONS', ar: 'الإعدادات' },
  'nav.users': { en: 'Users', ar: 'المستخدمين' },
  'nav.groups': { en: 'Groups', ar: 'المجموعات' },
  'nav.roles': { en: 'Roles', ar: 'الأدوار' },
  'nav.settings': { en: 'Site Settings', ar: 'إعدادات الموقع' },
  'nav.employeePortal': { en: 'Employee Portal', ar: 'بوابة الموظف' },
  'dashboard.title': { en: 'Dashboard', ar: 'لوحة التحكم' },
  'dashboard.totalEmployees': { en: 'Total Employees', ar: 'إجمالي الموظفين' },
  'dashboard.activeEmployees': { en: 'Active Employees', ar: 'موظفين نشطين' },
  'dashboard.departments': { en: 'Departments', ar: 'الأقسام' },
  'dashboard.todayAttendance': { en: 'Today Attendance', ar: 'الحضور اليوم' },
  'dashboard.openPositions': { en: 'Open Positions', ar: 'الوظائف المفتوحة' },
  'dashboard.pendingLeaves': { en: 'Pending Leave Requests', ar: 'طلبات الإجازة المعلقة' },
  'dashboard.assignedAssets': { en: 'Assigned Assets', ar: 'الأصول المعينة' },
  'dashboard.avgPerformance': { en: 'Avg Performance', ar: 'متوسط تقييم الأداء' },
  'chart.reportsStats': { en: 'Reports & Statistics', ar: 'التقارير والإحصائيات' },
  'chart.employeeGrowth': { en: 'Employee Growth (Last 6 Months)', ar: 'نمو الموظفين (آخر 6 أشهر)' },
  'chart.departmentDist': { en: 'Employees by Department', ar: 'توزيع الموظفين حسب القسم' },
  'chart.weeklyAttendance': { en: 'Weekly Attendance & Performance', ar: 'الحضور والأداء الأسبوعي' },
  'chart.advancedReports': { en: 'Advanced Reports', ar: 'لوحة التقارير المتقدمة' },
  'chart.refresh': { en: 'Refresh', ar: 'تحديث' },
  'dept.it': { en: 'IT', ar: 'تقنية المعلومات' },
  'dept.hr': { en: 'HR', ar: 'الموارد البشرية' },
  'dept.finance': { en: 'Finance', ar: 'المالية' },
  'dept.sales': { en: 'Sales', ar: 'المبيعات' },
  'dept.marketing': { en: 'Marketing', ar: 'التسويق' },
  'dept.operations': { en: 'Operations', ar: 'العمليات' },
  'legend.attendance': { en: 'Attendance', ar: 'الحضور' },
  'legend.completed': { en: 'Completed Tasks', ar: 'التقييمات المكتملة' },
  'legend.late': { en: 'Late', ar: 'التأخير' },
  'month.jan': { en: 'Jan', ar: 'يناير' },
  'month.feb': { en: 'Feb', ar: 'فبراير' },
  'month.mar': { en: 'Mar', ar: 'مارس' },
  'month.apr': { en: 'Apr', ar: 'أبريل' },
  'month.may': { en: 'May', ar: 'مايو' },
  'month.jun': { en: 'Jun', ar: 'يونيو' },
  // Employees page
  'employees.title': { en: 'Employee Management', ar: 'إدارة الموظفين' },
  'employees.search': { en: 'Search for employee...', ar: 'ابحث عن موظف...' },
  'employees.addEmployee': { en: 'Add Employee', ar: 'إضافة موظف' },
  'employees.refresh': { en: 'Refresh', ar: 'تحديث' },
  'employees.editEmployee': { en: 'Edit Employee', ar: 'تعديل الموظف' },
  'employees.save': { en: 'Save', ar: 'حفظ' },
  'employees.cancel': { en: 'Cancel', ar: 'إلغاء' },
  'employees.select': { en: 'Select', ar: 'اختر' },
  'employees.selectDepartment': { en: 'Select Department', ar: 'اختر القسم' },
  'employees.selectDegree': { en: 'Select Degree', ar: 'اختر الدرجة' },
  'employees.selectContractType': { en: 'Select Contract Type', ar: 'اختر نوع العقد' },
  'employees.addNewDepartment': { en: 'Add New Department', ar: 'إضافة قسم جديد' },
  'employees.clickToUpload': { en: 'Click on camera to upload photo', ar: 'انقر على أيقونة الكاميرا لتحميل صورة' },
  'employees.table.photo': { en: 'Photo', ar: 'الصورة' },
  'employees.table.employeeId': { en: 'Employee ID', ar: 'رقم الموظف' },
  'employees.table.name': { en: 'Name', ar: 'الاسم' },
  'employees.table.department': { en: 'Department', ar: 'القسم' },
  'employees.table.jobTitle': { en: 'Job Title', ar: 'المسمى الوظيفي' },
  'employees.table.phone': { en: 'Phone', ar: 'الهاتف' },
  'employees.table.status': { en: 'Status', ar: 'الحالة' },
  'employees.table.actions': { en: 'Actions', ar: 'الإجراءات' },
  'employees.status.active': { en: 'Active', ar: 'نشط' },
  'employees.status.inactive': { en: 'Inactive', ar: 'غير نشط' },
  'employees.status.resigned': { en: 'Resigned', ar: 'مستقيل' },
  'employees.tabs.basicInfo': { en: 'Basic Info', ar: 'معلومات أساسية' },
  'employees.tabs.contactInfo': { en: 'Contact Info', ar: 'معلومات الاتصال' },
  'employees.tabs.identity': { en: 'Identity & Documents', ar: 'الهوية والوثائق' },
  'employees.tabs.jobInfo': { en: 'Job Info', ar: 'معلومات الوظيفة' },
  'employees.tabs.insurance': { en: 'Insurance', ar: 'التأمينات' },
  'employees.tabs.permits': { en: 'Permits', ar: 'التصاريح' },
  'employees.tabs.certificates': { en: 'Certificates', ar: 'الشهادات والوثائق' },
  'employees.tabs.departments': { en: 'Departments', ar: 'الأقسام' },
  'employees.tabs.other': { en: 'Other', ar: 'أخرى' },
  'employees.tabs.leaveBalance': { en: 'Leave Balance', ar: 'رصيد الإجازات' },
  'employees.tabs.salary': { en: 'Salary & Allowances', ar: 'الرواتب والبدلات' },
  'employees.fields.employeeId': { en: 'Employee ID', ar: 'رقم الموظف' },
  'employees.fields.stationLocation': { en: 'Station/Location', ar: 'المحطة/الموقع' },
  'employees.fields.enterStation': { en: 'Enter Station', ar: 'ادخل المحطة' },
  'employees.fields.fullNameAr': { en: 'Full Name (Arabic)', ar: 'الاسم الكامل بالعربية' },
  'employees.fields.fullNameEn': { en: 'Full Name (English)', ar: 'الاسم الكامل بالإنجليزية' },
  'employees.fields.firstName': { en: 'First Name', ar: 'الاسم الأول' },
  'employees.fields.fatherName': { en: 'Father Name', ar: 'اسم الأب' },
  'employees.fields.familyName': { en: 'Family Name', ar: 'اسم العائلة' },
  'employees.fields.birthDate': { en: 'Birth Date', ar: 'تاريخ الميلاد' },
  'employees.fields.birthPlace': { en: 'Birth Place', ar: 'مكان الميلاد' },
  'employees.fields.birthGovernorate': { en: 'Birth Governorate', ar: 'محافظة الميلاد' },
  'employees.fields.gender': { en: 'Gender', ar: 'النوع' },
  'employees.fields.religion': { en: 'Religion', ar: 'الديانة' },
  'employees.fields.nationality': { en: 'Nationality', ar: 'الجنسية' },
  'employees.fields.maritalStatus': { en: 'Marital Status', ar: 'الحالة الاجتماعية' },
  'employees.fields.childrenCount': { en: 'Number of Children', ar: 'عدد الأطفال' },
  'employees.fields.educationAr': { en: 'Education (Arabic)', ar: 'المؤهل الدراسي بالعربية' },
  'employees.fields.graduationYear': { en: 'Graduation Year', ar: 'سنة التخرج' },
  'employees.fields.email': { en: 'Email', ar: 'البريد الإلكتروني' },
  'employees.fields.homePhone': { en: 'Home Phone', ar: 'هاتف المنزل' },
  'employees.fields.mobile': { en: 'Mobile', ar: 'الهاتف المحمول' },
  'employees.fields.address': { en: 'Address', ar: 'العنوان' },
  'employees.fields.city': { en: 'City', ar: 'المدينة' },
  'employees.fields.governorate': { en: 'Governorate', ar: 'المحافظة' },
  'employees.fields.nationalId': { en: 'National ID / Passport', ar: 'الرقم القومي/رقم جواز السفر' },
  'employees.fields.idIssueDate': { en: 'ID Issue Date', ar: 'تاريخ إصدار البطاقة' },
  'employees.fields.idExpiryDate': { en: 'ID Expiry Date', ar: 'تاريخ انتهاء البطاقة' },
  'employees.fields.issuingAuthority': { en: 'Issuing Authority', ar: 'جهة الإصدار' },
  'employees.fields.issuingGovernorate': { en: 'Issuing Governorate', ar: 'محافظة الإصدار' },
  'employees.fields.militaryStatus': { en: 'Military Status', ar: 'الحالة العسكرية' },
  'employees.fields.department': { en: 'Department', ar: 'القسم' },
  'employees.fields.jobTitleAr': { en: 'Job Title (Arabic)', ar: 'المسمى الوظيفي بالعربية' },
  'employees.fields.jobTitleEn': { en: 'Job Title (English)', ar: 'المسمى الوظيفي بالإنجليزية' },
  'employees.fields.jobLevel': { en: 'Job Level', ar: 'مستوى الوظيفة' },
  'employees.fields.jobDegree': { en: 'Job Degree', ar: 'الدرجة الوظيفية' },
  'employees.fields.hireDate': { en: 'Hire Date', ar: 'تاريخ التعيين' },
  'employees.fields.recruitedBy': { en: 'Recruited By', ar: 'طلب التوظيف بواسطة' },
  'employees.fields.employmentStatus': { en: 'Employment Status', ar: 'الحالة' },
  'employees.fields.resigned': { en: 'Resigned', ar: 'مستقيل' },
  'employees.fields.resignationDate': { en: 'Resignation Date', ar: 'تاريخ الاستقالة' },
  'employees.fields.resignationReason': { en: 'Resignation Reason', ar: 'سبب الاستقالة' },
  'employees.fields.socialInsuranceNo': { en: 'Social Insurance No.', ar: 'رقم التأمين الاجتماعي' },
  'employees.fields.socialInsuranceStartDate': { en: 'Social Insurance Start Date', ar: 'تاريخ بدء التأمين الاجتماعي' },
  'employees.fields.socialInsuranceEndDate': { en: 'Social Insurance End Date', ar: 'تاريخ انتهاء التأمين الاجتماعي' },
  'employees.fields.healthInsuranceCardNo': { en: 'Health Insurance Card No.', ar: 'رقم بطاقة التأمين الصحي' },
  'employees.fields.healthInsurance': { en: 'Health Insurance', ar: 'التأمين الصحي' },
  'employees.fields.govHealthInsurance': { en: 'Government Health Insurance', ar: 'التأمين الصحي الحكومي' },
  'employees.fields.socialInsurance': { en: 'Social Insurance', ar: 'التأمين الاجتماعي' },
  'employees.fields.contractType': { en: 'Contract Type', ar: 'نوع العقد' },
  'employees.fields.cairoAirportTempPermit': { en: 'Cairo Airport Temp Permit', ar: 'تصريح مطار القاهرة المؤقت' },
  'employees.fields.cairoAirportAnnualPermit': { en: 'Cairo Airport Annual Permit', ar: 'تصريح مطار القاهرة السنوي' },
  'employees.fields.tempPermitNo': { en: 'Temp Permit No.', ar: 'رقم التصريح المؤقت' },
  'employees.fields.annualPermitNo': { en: 'Annual Permit No.', ar: 'رقم التصريح السنوي' },
  'employees.fields.airportsTempPermit': { en: 'Airports Temp Permit', ar: 'تصريح المطارات المؤقت' },
  'employees.fields.airportsAnnualPermit': { en: 'Airports Annual Permit', ar: 'تصريح المطارات السنوي' },
  'employees.fields.airportsTempPermitNo': { en: 'Airports Temp Permit No.', ar: 'رقم تصريح المطارات المؤقت' },
  'employees.fields.airportsAnnualPermitNo': { en: 'Airports Annual Permit No.', ar: 'رقم تصريح المطارات السنوي' },
  'employees.fields.airportsPermitType': { en: 'Airports Permit Type', ar: 'نوع تصاريح المطارات' },
  'employees.fields.permitNameEn': { en: 'Permit Name (English)', ar: 'المسمى في التصريح بالإنجليزية' },
  'employees.fields.permitNameAr': { en: 'Permit Name (Arabic)', ar: 'المسمى في التصريح بالعربية' },
  'employees.fields.qualificationCert': { en: 'Qualification Certificate', ar: 'شهادة المؤهل' },
  'employees.fields.militaryServiceCert': { en: 'Military Service Certificate', ar: 'شهادة الخدمة العسكرية' },
  'employees.fields.birthCert': { en: 'Birth Certificate', ar: 'شهادة الميلاد' },
  'employees.fields.idCopy': { en: 'ID Copy', ar: 'صورة البطاقة' },
  'employees.fields.pledge': { en: 'Pledge', ar: 'التعهد' },
  'employees.fields.contract': { en: 'Contract', ar: 'العقد' },
  'employees.fields.receipt': { en: 'Receipt', ar: 'الفيش' },
  'employees.fields.attachments': { en: 'Attachments', ar: 'المرفقات' },
  'employees.fields.notes': { en: 'Notes', ar: 'ملاحظات' },
  'employees.fields.notesPlaceholder': { en: 'Enter any additional notes...', ar: 'أدخل أي ملاحظات إضافية...' },
  'employees.fields.annualLeaveBalance': { en: 'Annual Leave Balance', ar: 'رصيد الإجازات السنوية' },
  'employees.fields.sickLeaveBalance': { en: 'Sick Leave Balance', ar: 'رصيد الإجازات المرضية' },
  'employees.fields.casualLeaveBalance': { en: 'Casual Leave Balance', ar: 'رصيد الإجازات العارضة' },
  'employees.fields.usedLeave': { en: 'Used Leave', ar: 'الإجازات المستخدمة' },
  'employees.fields.basicSalary': { en: 'Basic Salary', ar: 'الراتب الأساسي' },
  'employees.fields.allowances': { en: 'Allowances', ar: 'البدلات' },
  'employees.fields.transportAllowance': { en: 'Transport Allowance', ar: 'بدل المواصلات' },
  'employees.fields.housingAllowance': { en: 'Housing Allowance', ar: 'بدل السكن' },
  'employees.fields.mealAllowance': { en: 'Meal Allowance', ar: 'بدل الوجبات' },
  'employees.fields.otherAllowances': { en: 'Other Allowances', ar: 'بدلات أخرى' },
  'employees.fields.deductions': { en: 'Deductions', ar: 'الاستقطاعات' },
  'employees.fields.netSalary': { en: 'Net Salary', ar: 'صافي الراتب' },
  'employees.gender.male': { en: 'Male', ar: 'ذكر' },
  'employees.gender.female': { en: 'Female', ar: 'أنثى' },
  'employees.religion.muslim': { en: 'Muslim', ar: 'مسلم' },
  'employees.religion.christian': { en: 'Christian', ar: 'مسيحي' },
  'employees.maritalStatus.single': { en: 'Single', ar: 'أعزب' },
  'employees.maritalStatus.married': { en: 'Married', ar: 'متزوج' },
  'employees.maritalStatus.divorced': { en: 'Divorced', ar: 'مطلق' },
  'employees.maritalStatus.widowed': { en: 'Widowed', ar: 'أرمل' },
  'employees.military.completed': { en: 'Completed', ar: 'أدى الخدمة' },
  'employees.military.exempt': { en: 'Exempt', ar: 'معفى' },
  'employees.military.postponed': { en: 'Postponed', ar: 'مؤجل' },
  'employees.contract.permanent': { en: 'Permanent', ar: 'دائم' },
  'employees.contract.temporary': { en: 'Temporary', ar: 'مؤقت' },
  'employees.contract.parttime': { en: 'Part-time', ar: 'جزئي' },
  // Leaves module
  'leaves.title': { en: 'Leave Management', ar: 'إدارة الإجازات' },
  'leaves.subtitle': { en: 'Manage employee leave requests and approvals', ar: 'إدارة طلبات إجازات الموظفين والموافقات' },
  'leaves.tabs.requests': { en: 'All Requests', ar: 'جميع الطلبات' },
  'leaves.tabs.newRequest': { en: 'New Request', ar: 'طلب جديد' },
  'leaves.tabs.approvals': { en: 'Approvals', ar: 'الموافقات' },
  'leaves.tabs.balance': { en: 'Balance', ar: 'الأرصدة' },
  'leaves.tabs.calendar': { en: 'Calendar', ar: 'التقويم' },
  'leaves.days': { en: 'days', ar: 'أيام' },
  'leaves.types.annual': { en: 'Annual', ar: 'سنوية' },
  'leaves.types.sick': { en: 'Sick', ar: 'مرضية' },
  'leaves.types.casual': { en: 'Casual', ar: 'عارضة' },
  'leaves.types.unpaid': { en: 'Unpaid', ar: 'بدون راتب' },
  'leaves.types.maternity': { en: 'Maternity', ar: 'أمومة' },
  'leaves.types.paternity': { en: 'Paternity', ar: 'أبوة' },
  'leaves.status.pending': { en: 'Pending', ar: 'قيد الانتظار' },
  'leaves.status.approved': { en: 'Approved', ar: 'موافق عليه' },
  'leaves.status.rejected': { en: 'Rejected', ar: 'مرفوض' },
  'leaves.form.title': { en: 'Submit Leave Request', ar: 'تقديم طلب إجازة' },
  'leaves.form.leaveType': { en: 'Leave Type', ar: 'نوع الإجازة' },
  'leaves.form.selectType': { en: 'Select leave type', ar: 'اختر نوع الإجازة' },
  'leaves.form.startDate': { en: 'Start Date', ar: 'تاريخ البداية' },
  'leaves.form.endDate': { en: 'End Date', ar: 'تاريخ النهاية' },
  'leaves.form.totalDays': { en: 'Total Days', ar: 'إجمالي الأيام' },
  'leaves.form.reason': { en: 'Reason', ar: 'السبب' },
  'leaves.form.reasonPlaceholder': { en: 'Enter reason for leave...', ar: 'أدخل سبب الإجازة...' },
  'leaves.form.pickDate': { en: 'Pick a date', ar: 'اختر تاريخ' },
  'leaves.form.submit': { en: 'Submit Request', ar: 'إرسال الطلب' },
  'leaves.form.error': { en: 'Error', ar: 'خطأ' },
  'leaves.form.fillAllFields': { en: 'Please fill all required fields', ar: 'يرجى ملء جميع الحقول المطلوبة' },
  'leaves.form.success': { en: 'Success', ar: 'نجاح' },
  'leaves.form.requestSubmitted': { en: 'Leave request submitted successfully', ar: 'تم تقديم طلب الإجازة بنجاح' },
  'leaves.list.title': { en: 'Leave Requests', ar: 'طلبات الإجازات' },
  'leaves.list.employee': { en: 'Employee', ar: 'الموظف' },
  'leaves.list.department': { en: 'Department', ar: 'القسم' },
  'leaves.list.type': { en: 'Type', ar: 'النوع' },
  'leaves.list.startDate': { en: 'Start Date', ar: 'تاريخ البداية' },
  'leaves.list.endDate': { en: 'End Date', ar: 'تاريخ النهاية' },
  'leaves.list.days': { en: 'Days', ar: 'الأيام' },
  'leaves.list.status': { en: 'Status', ar: 'الحالة' },
  'leaves.list.noRequests': { en: 'No leave requests found', ar: 'لا توجد طلبات إجازة' },
  'leaves.approvals.title': { en: 'Pending Approvals', ar: 'الموافقات المعلقة' },
  'leaves.approvals.noPending': { en: 'No pending requests to approve', ar: 'لا توجد طلبات معلقة للموافقة' },
  'leaves.approvals.approve': { en: 'Approve', ar: 'موافقة' },
  'leaves.approvals.reject': { en: 'Reject', ar: 'رفض' },
  'leaves.approvals.approved': { en: 'Approved', ar: 'تمت الموافقة' },
  'leaves.approvals.approvedMessage': { en: 'Leave request has been approved', ar: 'تمت الموافقة على طلب الإجازة' },
  'leaves.approvals.rejected': { en: 'Rejected', ar: 'تم الرفض' },
  'leaves.approvals.rejectedMessage': { en: 'Leave request has been rejected', ar: 'تم رفض طلب الإجازة' },
  'leaves.approvals.rejectTitle': { en: 'Reject Leave Request', ar: 'رفض طلب الإجازة' },
  'leaves.approvals.rejectReasonPlaceholder': { en: 'Enter reason for rejection...', ar: 'أدخل سبب الرفض...' },
  'leaves.approvals.confirmReject': { en: 'Confirm Rejection', ar: 'تأكيد الرفض' },
  'leaves.balance.annualLeave': { en: 'Annual Leave', ar: 'الإجازة السنوية' },
  'leaves.balance.sickLeave': { en: 'Sick Leave', ar: 'الإجازة المرضية' },
  'leaves.balance.casualLeave': { en: 'Casual Leave', ar: 'الإجازة العارضة' },
  'leaves.balance.used': { en: 'Used', ar: 'مستخدم' },
  'leaves.balance.remaining': { en: 'Remaining', ar: 'المتبقي' },
  'leaves.balance.detailedBalance': { en: 'Detailed Leave Balance', ar: 'تفاصيل رصيد الإجازات' },
  'leaves.balance.employee': { en: 'Employee', ar: 'الموظف' },
  'leaves.balance.department': { en: 'Department', ar: 'القسم' },
  'leaves.calendar.title': { en: 'Team Absence Calendar', ar: 'تقويم غياب الفريق' },
  'leaves.calendar.more': { en: 'more', ar: 'المزيد' },
  // Attendance module
  'attendance.title': { en: 'Attendance Management', ar: 'إدارة الحضور والانصراف' },
  'attendance.subtitle': { en: 'Track employee check-ins, check-outs, and attendance reports', ar: 'تتبع حضور وانصراف الموظفين والتقارير' },
  'attendance.tabs.checkInOut': { en: 'Check In/Out', ar: 'تسجيل الحضور' },
  'attendance.tabs.records': { en: 'Records', ar: 'السجلات' },
  'attendance.tabs.lateArrivals': { en: 'Late Arrivals', ar: 'التأخيرات' },
  'attendance.tabs.reports': { en: 'Reports', ar: 'التقارير' },
  'attendance.checkin.button': { en: 'Check In', ar: 'تسجيل الحضور' },
  'attendance.checkout.button': { en: 'Check Out', ar: 'تسجيل الانصراف' },
  'attendance.checkin.time': { en: 'Check In Time', ar: 'وقت الحضور' },
  'attendance.checkout.time': { en: 'Check Out Time', ar: 'وقت الانصراف' },
  'attendance.workDuration': { en: 'Work Duration', ar: 'مدة العمل' },
  'attendance.todayStatus': { en: "Today's Status", ar: 'حالة اليوم' },
  'attendance.completed': { en: 'Day Completed', ar: 'تم الانتهاء' },
  'attendance.checkin.success': { en: 'Checked In', ar: 'تم تسجيل الحضور' },
  'attendance.checkin.successMessage': { en: 'You have successfully checked in', ar: 'تم تسجيل حضورك بنجاح' },
  'attendance.checkout.success': { en: 'Checked Out', ar: 'تم تسجيل الانصراف' },
  'attendance.checkout.successMessage': { en: 'You have successfully checked out', ar: 'تم تسجيل انصرافك بنجاح' },
  'attendance.checkin.confirm': { en: 'Confirm Check In', ar: 'تأكيد تسجيل الحضور' },
  'attendance.checkout.confirm': { en: 'Confirm Check Out', ar: 'تأكيد تسجيل الانصراف' },
  'attendance.allEmployeesCheckedIn': { en: 'All employees have checked in today', ar: 'جميع الموظفين سجلوا حضورهم اليوم' },
  'attendance.noEmployeesToCheckOut': { en: 'No employees to check out', ar: 'لا يوجد موظفين لتسجيل انصرافهم' },
  'attendance.recentActivity': { en: 'Recent Activity', ar: 'النشاط الأخير' },
  'attendance.lateBy': { en: 'Late by', ar: 'تأخير بمقدار' },
  'attendance.status.present': { en: 'Present', ar: 'حاضر' },
  'attendance.status.absent': { en: 'Absent', ar: 'غائب' },
  'attendance.status.late': { en: 'Late', ar: 'متأخر' },
  'attendance.status.early-leave': { en: 'Early Leave', ar: 'انصراف مبكر' },
  'attendance.status.on-leave': { en: 'On Leave', ar: 'في إجازة' },
  'attendance.list.title': { en: 'Attendance Records', ar: 'سجلات الحضور' },
  'attendance.list.search': { en: 'Search employees...', ar: 'ابحث عن موظف...' },
  'attendance.list.filterStatus': { en: 'Filter by status', ar: 'تصفية حسب الحالة' },
  'attendance.list.allStatuses': { en: 'All Statuses', ar: 'جميع الحالات' },
  'attendance.list.pickDate': { en: 'Pick a date', ar: 'اختر تاريخ' },
  'attendance.list.clearDate': { en: 'Clear', ar: 'مسح' },
  'attendance.list.date': { en: 'Date', ar: 'التاريخ' },
  'attendance.list.employee': { en: 'Employee', ar: 'الموظف' },
  'attendance.list.department': { en: 'Department', ar: 'القسم' },
  'attendance.list.checkIn': { en: 'Check In', ar: 'الحضور' },
  'attendance.list.checkOut': { en: 'Check Out', ar: 'الانصراف' },
  'attendance.list.workHours': { en: 'Work Hours', ar: 'ساعات العمل' },
  'attendance.list.overtime': { en: 'Overtime', ar: 'إضافي' },
  'attendance.list.status': { en: 'Status', ar: 'الحالة' },
  'attendance.list.noRecords': { en: 'No attendance records found', ar: 'لا توجد سجلات حضور' },
  'attendance.late.today': { en: 'Late Today', ar: 'المتأخرون اليوم' },
  'attendance.late.thisWeek': { en: 'Late This Week', ar: 'متأخرون هذا الأسبوع' },
  'attendance.late.frequentOffenders': { en: 'Frequent Offenders', ar: 'المتأخرون بشكل متكرر' },
  'attendance.late.todayList': { en: "Today's Late Arrivals", ar: 'المتأخرون اليوم' },
  'attendance.late.noReason': { en: 'No reason provided', ar: 'لم يتم تقديم سبب' },
  'attendance.late.frequentTitle': { en: 'Frequent Late Arrivals', ar: 'التأخيرات المتكررة' },
  'attendance.late.noLateArrivals': { en: 'No late arrivals recorded', ar: 'لا توجد تأخيرات مسجلة' },
  'attendance.late.lateCount': { en: 'Late Count', ar: 'عدد التأخيرات' },
  'attendance.late.avgLateTime': { en: 'Avg. Late Time', ar: 'متوسط وقت التأخير' },
  'attendance.late.severity': { en: 'Severity', ar: 'الخطورة' },
  'attendance.late.times': { en: 'times', ar: 'مرات' },
  'attendance.late.severity.low': { en: 'Low', ar: 'منخفض' },
  'attendance.late.severity.medium': { en: 'Medium', ar: 'متوسط' },
  'attendance.late.severity.high': { en: 'High', ar: 'عالي' },
  'attendance.reports.attendanceRate': { en: 'Attendance Rate', ar: 'معدل الحضور' },
  'attendance.reports.punctualityRate': { en: 'Punctuality Rate', ar: 'معدل الالتزام بالوقت' },
  'attendance.reports.totalWorkHours': { en: 'Total Work Hours', ar: 'إجمالي ساعات العمل' },
  'attendance.reports.totalOvertime': { en: 'Total Overtime', ar: 'إجمالي الإضافي' },
  'attendance.reports.statusDistribution': { en: 'Status Distribution', ar: 'توزيع الحالات' },
  'attendance.reports.weeklyTrend': { en: 'Weekly Trend', ar: 'الاتجاه الأسبوعي' },
  'attendance.reports.totalAttendance': { en: 'Total Attendance', ar: 'إجمالي الحضور' },
  'attendance.reports.departmentWise': { en: 'Department-wise Attendance', ar: 'الحضور حسب القسم' },
  // Attendance - Shifts Management
  'attendance.tabs.shifts': { en: 'Shifts', ar: 'الورديات' },
  'attendance.tabs.rules': { en: 'Rules', ar: 'القواعد' },
  'attendance.tabs.locations': { en: 'Locations', ar: 'المواقع' },
  'attendance.tabs.assignment': { en: 'Assignment', ar: 'التعيينات' },
  'attendance.shifts.title': { en: 'Shift Management', ar: 'إدارة الورديات' },
  'attendance.shifts.subtitle': { en: 'Configure 24/7 shift patterns for airport operations', ar: 'تكوين أنماط الورديات على مدار الساعة لعمليات المطار' },
  'attendance.shifts.addShift': { en: 'Add Shift', ar: 'إضافة وردية' },
  'attendance.shifts.nameEn': { en: 'Name (English)', ar: 'الاسم (إنجليزي)' },
  'attendance.shifts.nameAr': { en: 'Name (Arabic)', ar: 'الاسم (عربي)' },
  'attendance.shifts.startTime': { en: 'Start Time', ar: 'وقت البداية' },
  'attendance.shifts.endTime': { en: 'End Time', ar: 'وقت النهاية' },
  'attendance.shifts.location': { en: 'Location', ar: 'الموقع' },
  'attendance.shifts.selectLocation': { en: 'Select location', ar: 'اختر الموقع' },
  'attendance.shifts.breakDuration': { en: 'Break (min)', ar: 'الاستراحة (دقيقة)' },
  'attendance.shifts.color': { en: 'Color', ar: 'اللون' },
  'attendance.shifts.overnight': { en: 'Overnight Shift', ar: 'وردية ليلية' },
  'attendance.shifts.save': { en: 'Save Shift', ar: 'حفظ الوردية' },
  'attendance.shifts.filterByLocation': { en: 'Filter by Location', ar: 'تصفية حسب الموقع' },
  'attendance.shifts.allLocations': { en: 'All Locations', ar: 'جميع المواقع' },
  'attendance.shifts.time': { en: 'Time', ar: 'الوقت' },
  'attendance.shifts.duration': { en: 'Duration', ar: 'المدة' },
  'attendance.shifts.break': { en: 'Break', ar: 'الاستراحة' },
  'attendance.shifts.overnightShift': { en: 'Overnight', ar: 'ليلية' },
  'attendance.shifts.scheduleOverview': { en: 'Shift Schedule Overview', ar: 'نظرة عامة على جدول الورديات' },
  'attendance.shifts.scheduleDesc': { en: 'View all configured shifts and their assignments', ar: 'عرض جميع الورديات المكونة وتعييناتها' },
  'attendance.shifts.shift': { en: 'Shift', ar: 'الوردية' },
  'attendance.shifts.employees': { en: 'Employees', ar: 'الموظفين' },
  'attendance.shifts.status': { en: 'Status', ar: 'الحالة' },
  'attendance.shifts.active': { en: 'Active', ar: 'نشط' },
  // Attendance - Rules Management
  'attendance.rules.title': { en: 'Attendance Rules', ar: 'قواعد الحضور' },
  'attendance.rules.subtitle': { en: 'Configure attendance policies for different schedule types', ar: 'تكوين سياسات الحضور لأنواع الجداول المختلفة' },
  'attendance.rules.addRule': { en: 'Add Rule', ar: 'إضافة قاعدة' },
  'attendance.rules.fixed': { en: 'Fixed', ar: 'ثابت' },
  'attendance.rules.flexible': { en: 'Flexible', ar: 'مرن' },
  'attendance.rules.shift': { en: 'Shift', ar: 'ورديات' },
  'attendance.rules.nameEn': { en: 'Name (English)', ar: 'الاسم (إنجليزي)' },
  'attendance.rules.nameAr': { en: 'Name (Arabic)', ar: 'الاسم (عربي)' },
  'attendance.rules.description': { en: 'Description', ar: 'الوصف' },
  'attendance.rules.fixedSettings': { en: 'Fixed Schedule Settings', ar: 'إعدادات الدوام الثابت' },
  'attendance.rules.flexibleSettings': { en: 'Flexible Schedule Settings', ar: 'إعدادات الدوام المرن' },
  'attendance.rules.shiftSettings': { en: 'Shift Schedule Settings', ar: 'إعدادات نظام الورديات' },
  'attendance.rules.startTime': { en: 'Start Time', ar: 'وقت البداية' },
  'attendance.rules.endTime': { en: 'End Time', ar: 'وقت النهاية' },
  'attendance.rules.gracePeriod': { en: 'Grace Period', ar: 'فترة السماح' },
  'attendance.rules.earlyLeave': { en: 'Early Leave Tolerance', ar: 'تسامح الانصراف المبكر' },
  'attendance.rules.minutes': { en: 'min', ar: 'دقيقة' },
  'attendance.rules.arrivalStart': { en: 'Arrival Window Start', ar: 'بداية نافذة الحضور' },
  'attendance.rules.arrivalEnd': { en: 'Arrival Window End', ar: 'نهاية نافذة الحضور' },
  'attendance.rules.minWorkHours': { en: 'Minimum Work Hours', ar: 'الحد الأدنى لساعات العمل' },
  'attendance.rules.coreStart': { en: 'Core Hours Start', ar: 'بداية الساعات الأساسية' },
  'attendance.rules.coreEnd': { en: 'Core Hours End', ar: 'نهاية الساعات الأساسية' },
  'attendance.rules.shiftTemplate': { en: 'Shift Template', ar: 'قالب الورديات' },
  'attendance.rules.threeShift': { en: '3-Shift Pattern (8 hours each)', ar: 'نظام 3 ورديات (8 ساعات لكل وردية)' },
  'attendance.rules.fourShift': { en: '4-Shift Pattern (6 hours each)', ar: 'نظام 4 ورديات (6 ساعات لكل وردية)' },
  'attendance.rules.allowSwap': { en: 'Allow Shift Swap', ar: 'السماح بتبديل الورديات' },
  'attendance.rules.nightAllowance': { en: 'Night Shift Allowance', ar: 'بدل الوردية الليلية' },
  'attendance.rules.commonSettings': { en: 'Common Settings', ar: 'الإعدادات العامة' },
  'attendance.rules.maxDailyOT': { en: 'Max Daily Overtime (hours)', ar: 'الحد الأقصى للإضافي اليومي (ساعات)' },
  'attendance.rules.maxWeeklyOT': { en: 'Max Weekly Overtime (hours)', ar: 'الحد الأقصى للإضافي الأسبوعي (ساعات)' },
  'attendance.rules.save': { en: 'Save Rule', ar: 'حفظ القاعدة' },
  'attendance.rules.fixedRules': { en: 'Fixed Rules', ar: 'قواعد ثابتة' },
  'attendance.rules.flexibleRules': { en: 'Flexible Rules', ar: 'قواعد مرنة' },
  'attendance.rules.shiftRules': { en: 'Shift Rules', ar: 'قواعد ورديات' },
  'attendance.rules.assignedEmployees': { en: 'Assigned Employees', ar: 'موظفين معينين' },
  'attendance.rules.viewDetails': { en: 'View Details', ar: 'عرض التفاصيل' },
  'attendance.rules.workingHours': { en: 'Working Hours', ar: 'ساعات العمل' },
  'attendance.rules.arrivalWindow': { en: 'Arrival Window', ar: 'نافذة الحضور' },
  'attendance.rules.allowed': { en: 'Allowed', ar: 'مسموح' },
  'attendance.rules.notAllowed': { en: 'Not Allowed', ar: 'غير مسموح' },
  'attendance.rules.yes': { en: 'Yes', ar: 'نعم' },
  'attendance.rules.no': { en: 'No', ar: 'لا' },
  'attendance.rules.workDays': { en: 'Work Days', ar: 'أيام العمل' },
  'attendance.rules.daysPerWeek': { en: 'days/week', ar: 'يوم/أسبوع' },
  // Attendance - Locations Management
  'attendance.locations.title': { en: 'Location Management', ar: 'إدارة المواقع' },
  'attendance.locations.subtitle': { en: 'Configure headquarters and airport locations', ar: 'تكوين مواقع المقر الرئيسي والمطارات' },
  'attendance.locations.addLocation': { en: 'Add Location', ar: 'إضافة موقع' },
  'attendance.locations.nameEn': { en: 'Name (English)', ar: 'الاسم (إنجليزي)' },
  'attendance.locations.nameAr': { en: 'Name (Arabic)', ar: 'الاسم (عربي)' },
  'attendance.locations.code': { en: 'Code', ar: 'الرمز' },
  'attendance.locations.type': { en: 'Type', ar: 'النوع' },
  'attendance.locations.headquarters': { en: 'Headquarters', ar: 'المقر الرئيسي' },
  'attendance.locations.airport': { en: 'Airport', ar: 'مطار' },
  'attendance.locations.airports': { en: 'Airports', ar: 'المطارات' },
  'attendance.locations.address': { en: 'Address', ar: 'العنوان' },
  'attendance.locations.timezone': { en: 'Timezone', ar: 'المنطقة الزمنية' },
  'attendance.locations.save': { en: 'Save Location', ar: 'حفظ الموقع' },
  'attendance.locations.activeLocations': { en: 'Active Locations', ar: 'مواقع نشطة' },
  'attendance.locations.employees': { en: 'employees', ar: 'موظف' },
  'attendance.locations.24hours': { en: '24/7 Operations', ar: 'عمليات على مدار الساعة' },
  'attendance.locations.geofence': { en: 'Geofence Radius', ar: 'نطاق السياج الجغرافي' },
  'attendance.locations.editLocation': { en: 'Edit Location', ar: 'تعديل الموقع' },
  // Attendance - Employee Assignment
  'attendance.assignment.title': { en: 'Employee Attendance Assignment', ar: 'تعيين حضور الموظفين' },
  'attendance.assignment.subtitle': { en: 'Assign attendance rules and shifts to employees', ar: 'تعيين قواعد الحضور والورديات للموظفين' },
  'attendance.assignment.assignEmployee': { en: 'Assign Employee', ar: 'تعيين موظف' },
  'attendance.assignment.employee': { en: 'Employee', ar: 'الموظف' },
  'attendance.assignment.selectEmployee': { en: 'Select employee', ar: 'اختر الموظف' },
  'attendance.assignment.attendanceRule': { en: 'Attendance Rule', ar: 'قاعدة الحضور' },
  'attendance.assignment.selectRule': { en: 'Select rule', ar: 'اختر القاعدة' },
  'attendance.assignment.location': { en: 'Location', ar: 'الموقع' },
  'attendance.assignment.selectLocation': { en: 'Select location', ar: 'اختر الموقع' },
  'attendance.assignment.shift': { en: 'Shift', ar: 'الوردية' },
  'attendance.assignment.selectShift': { en: 'Select shift (for shift workers)', ar: 'اختر الوردية (لعمال الورديات)' },
  'attendance.assignment.noShift': { en: 'No Shift (HQ employees)', ar: 'بدون وردية (موظفي المقر)' },
  'attendance.assignment.effectiveFrom': { en: 'Effective From', ar: 'ساري من تاريخ' },
  'attendance.assignment.save': { en: 'Save Assignment', ar: 'حفظ التعيين' },
  'attendance.assignment.search': { en: 'Search employees...', ar: 'ابحث عن موظف...' },
  'attendance.assignment.allLocations': { en: 'All Locations', ar: 'جميع المواقع' },
  'attendance.assignment.allRules': { en: 'All Rules', ar: 'جميع القواعد' },
  'attendance.assignment.employeeAssignments': { en: 'Employee Assignments', ar: 'تعيينات الموظفين' },
  'attendance.assignment.employees': { en: 'employees', ar: 'موظف' },
  'attendance.assignment.department': { en: 'Department', ar: 'القسم' },
  'attendance.assignment.actions': { en: 'Actions', ar: 'الإجراءات' },
  // Performance module
  'performance.title': { en: 'Performance Evaluation', ar: 'تقييم الأداء' },
  'performance.subtitle': { en: 'Quarterly employee performance reviews and tracking', ar: 'تقييمات الأداء الربع سنوية ومتابعة الموظفين' },
  'performance.tabs.dashboard': { en: 'Dashboard', ar: 'لوحة التحكم' },
  'performance.tabs.reviews': { en: 'Reviews', ar: 'التقييمات' },
  'performance.tabs.newReview': { en: 'New Review', ar: 'تقييم جديد' },
  'performance.tabs.reports': { en: 'Reports', ar: 'التقارير' },
  'performance.stats.avgScore': { en: 'Average Score', ar: 'متوسط التقييم' },
  'performance.stats.totalReviews': { en: 'Total Reviews', ar: 'إجمالي التقييمات' },
  'performance.stats.pendingReviews': { en: 'Pending Reviews', ar: 'تقييمات معلقة' },
  'performance.stats.completionRate': { en: 'Completion Rate', ar: 'معدل الإكمال' },
  'performance.charts.distribution': { en: 'Performance Distribution', ar: 'توزيع التقييمات' },
  'performance.charts.quarterlyTrend': { en: 'Quarterly Trend', ar: 'الاتجاه الربع سنوي' },
  'performance.topPerformers': { en: 'Top Performers', ar: 'أفضل الموظفين أداءً' },
  'performance.metrics.average': { en: 'Average Score', ar: 'متوسط التقييم' },
  'performance.metrics.completed': { en: 'Completed Reviews', ar: 'التقييمات المكتملة' },
  'performance.metrics.actualScore': { en: 'Actual Score', ar: 'التقييم الفعلي' },
  'performance.metrics.target': { en: 'Target', ar: 'المستهدف' },
  'performance.score.excellent': { en: 'Excellent', ar: 'ممتاز' },
  'performance.score.veryGood': { en: 'Very Good', ar: 'جيد جداً' },
  'performance.score.good': { en: 'Good', ar: 'جيد' },
  'performance.score.acceptable': { en: 'Acceptable', ar: 'مقبول' },
  'performance.score.poor': { en: 'Poor', ar: 'ضعيف' },
  'performance.form.selectEmployee': { en: 'Select Employee', ar: 'اختيار الموظف' },
  'performance.form.employee': { en: 'Employee', ar: 'الموظف' },
  'performance.form.selectEmployeePlaceholder': { en: 'Select an employee...', ar: 'اختر موظف...' },
  'performance.form.quarter': { en: 'Quarter', ar: 'الربع السنوي' },
  'performance.form.selectQuarterPlaceholder': { en: 'Select quarter...', ar: 'اختر الربع السنوي...' },
  'performance.form.criteria': { en: 'Evaluation Criteria', ar: 'معايير التقييم' },
  'performance.form.criteriaDesc': { en: 'Rate each criterion from 1 to 5 stars', ar: 'قيّم كل معيار من 1 إلى 5 نجوم' },
  'performance.form.overallScore': { en: 'Overall Score', ar: 'التقييم الإجمالي' },
  'performance.form.strengths': { en: 'Strengths', ar: 'نقاط القوة' },
  'performance.form.strengthsPlaceholder': { en: 'Describe employee strengths...', ar: 'اذكر نقاط قوة الموظف...' },
  'performance.form.improvements': { en: 'Areas for Improvement', ar: 'مجالات التحسين' },
  'performance.form.improvementsPlaceholder': { en: 'Describe areas that need improvement...', ar: 'اذكر المجالات التي تحتاج تحسين...' },
  'performance.form.nextQuarterGoals': { en: 'Next Quarter Goals', ar: 'أهداف الربع القادم' },
  'performance.form.goalsPlaceholder': { en: 'Set goals for the next quarter...', ar: 'حدد أهداف الربع القادم...' },
  'performance.form.managerComments': { en: 'Manager Comments', ar: 'ملاحظات المدير' },
  'performance.form.managerCommentsPlaceholder': { en: 'Add any additional comments...', ar: 'أضف أي ملاحظات إضافية...' },
  'performance.form.saveDraft': { en: 'Save Draft', ar: 'حفظ كمسودة' },
  'performance.form.submit': { en: 'Submit Review', ar: 'إرسال التقييم' },
  'performance.form.draftSaved': { en: 'Draft saved successfully', ar: 'تم حفظ المسودة بنجاح' },
  'performance.form.submitted': { en: 'Review submitted successfully', ar: 'تم إرسال التقييم بنجاح' },
  'performance.form.fillRequired': { en: 'Please fill all required fields', ar: 'يرجى ملء جميع الحقول المطلوبة' },
  'performance.status.approved': { en: 'Approved', ar: 'معتمد' },
  'performance.status.submitted': { en: 'Submitted', ar: 'مُرسل' },
  'performance.status.draft': { en: 'Draft', ar: 'مسودة' },
  'performance.list.title': { en: 'Performance Reviews', ar: 'تقييمات الأداء' },
  'performance.list.search': { en: 'Search by name or department...', ar: 'ابحث بالاسم أو القسم...' },
  'performance.list.status': { en: 'Status', ar: 'الحالة' },
  'performance.list.allStatuses': { en: 'All Statuses', ar: 'جميع الحالات' },
  'performance.list.quarter': { en: 'Quarter', ar: 'الربع' },
  'performance.list.allQuarters': { en: 'All Quarters', ar: 'جميع الأرباع' },
  'performance.list.employee': { en: 'Employee', ar: 'الموظف' },
  'performance.list.department': { en: 'Department', ar: 'القسم' },
  'performance.list.score': { en: 'Score', ar: 'التقييم' },
  'performance.list.reviewer': { en: 'Reviewer', ar: 'المقيّم' },
  'performance.list.actions': { en: 'Actions', ar: 'الإجراءات' },
  'performance.list.noResults': { en: 'No reviews found', ar: 'لا توجد تقييمات' },
  'performance.reports.title': { en: 'Quarterly Reports', ar: 'التقارير الربع سنوية' },
  'performance.reports.description': { en: 'View and export quarterly performance reports', ar: 'عرض وتصدير تقارير الأداء الربع سنوية' },
  'performance.reports.export': { en: 'Export', ar: 'تصدير' },
  'performance.reports.totalReviews': { en: 'Total Reviews', ar: 'إجمالي التقييمات' },
  'performance.reports.avgScore': { en: 'Average Score', ar: 'متوسط التقييم' },
  'performance.reports.aboveTarget': { en: 'Above Target', ar: 'فوق المستهدف' },
  'performance.reports.needsImprovement': { en: 'Needs Improvement', ar: 'يحتاج تحسين' },
  'performance.reports.quarterlyTrend': { en: 'Quarterly Score Trend', ar: 'اتجاه التقييم الربع سنوي' },
  'performance.reports.criteriaAnalysis': { en: 'Criteria Analysis', ar: 'تحليل المعايير' },
  'performance.reports.departmentPerformance': { en: 'Department Performance', ar: 'أداء الأقسام' },
  'performance.reports.employees': { en: 'employees', ar: 'موظف' },
  'performance.reports.criteriaBreakdown': { en: 'Criteria Breakdown', ar: 'تفصيل المعايير' },
  // Attendance - CheckInOut additional translations
  'attendance.selectEmployee': { en: 'Select Employee', ar: 'اختر الموظف' },
  'attendance.employee': { en: 'Employee', ar: 'الموظف' },
  'attendance.selectEmployeePlaceholder': { en: 'Select an employee...', ar: 'اختر موظف...' },
  'attendance.selectEmployeeFirst': { en: 'Please select an employee first', ar: 'يرجى اختيار موظف أولاً' },
  'attendance.addEmployee': { en: 'Add Employee', ar: 'إضافة موظف' },
  'attendance.addNewEmployee': { en: 'Add New Employee', ar: 'إضافة موظف جديد' },
  'attendance.employeeNameEn': { en: 'Name (English)', ar: 'الاسم (إنجليزي)' },
  'attendance.employeeNameAr': { en: 'Name (Arabic)', ar: 'الاسم (عربي)' },
  'attendance.department': { en: 'Department', ar: 'القسم' },
  'attendance.selectDepartment': { en: 'Select Department', ar: 'اختر القسم' },
  'attendance.location': { en: 'Location', ar: 'الموقع' },
  'attendance.locations.hq': { en: 'Headquarters', ar: 'المقر الرئيسي' },
  'attendance.locations.airportT1': { en: 'Airport - Terminal 1', ar: 'المطار - صالة 1' },
  'attendance.locations.airportT2': { en: 'Airport - Terminal 2', ar: 'المطار - صالة 2' },
  'attendance.locations.airportT3': { en: 'Airport - Terminal 3', ar: 'المطار - صالة 3' },
  'attendance.employeeAdded': { en: 'Employee Added', ar: 'تمت إضافة الموظف' },
  'attendance.fillAllFields': { en: 'Please fill all required fields', ar: 'يرجى ملء جميع الحقول المطلوبة' },
  'attendance.todaySummary': { en: "Today's Summary", ar: 'ملخص اليوم' },
  'attendance.totalCheckedIn': { en: 'Total Checked In', ar: 'إجمالي الحضور' },
  'attendance.totalCheckedOut': { en: 'Total Checked Out', ar: 'إجمالي الانصراف' },
  'attendance.totalLate': { en: 'Total Late', ar: 'إجمالي المتأخرين' },
  'common.cancel': { en: 'Cancel', ar: 'إلغاء' },
  'common.add': { en: 'Add', ar: 'إضافة' },
  'common.save': { en: 'Save', ar: 'حفظ' },
  'common.delete': { en: 'Delete', ar: 'حذف' },
  'common.edit': { en: 'Edit', ar: 'تعديل' },
  'common.all': { en: 'All', ar: 'الكل' },
  'common.actions': { en: 'Actions', ar: 'الإجراءات' },
  'common.back': { en: 'Back', ar: 'رجوع' },
  'common.export': { en: 'Export', ar: 'تصدير' },
  'common.of': { en: 'of', ar: 'من' },
  'common.error': { en: 'Error', ar: 'خطأ' },
  'common.success': { en: 'Success', ar: 'نجاح' },
  // Training Module
  'training.title': { en: 'Training Management', ar: 'إدارة التدريب' },
  'training.subtitle': { en: 'Manage training records, courses, and training plans', ar: 'إدارة سجلات التدريب والدورات وخطط التدريب' },
  'training.tabs.records': { en: 'Training Records', ar: 'سجلات التدريب' },
  'training.tabs.trainers': { en: 'Trainers', ar: 'المدربين' },
  'training.tabs.syllabus': { en: 'Courses Syllabus', ar: 'مناهج الدورات' },
  'training.tabs.courses': { en: 'Courses List', ar: 'قائمة الدورات' },
  'training.tabs.plan': { en: 'Training Plan', ar: 'خطة التدريب' },
  'training.searchByName': { en: 'Search By Name', ar: 'بحث بالاسم' },
  'training.searchByDept': { en: 'Search By Department', ar: 'بحث بالقسم' },
  'training.searchByStation': { en: 'Search By Station', ar: 'بحث بالمحطة' },
  'training.selectEmployee': { en: 'Select an employee to view training records', ar: 'اختر موظف لعرض سجلات التدريب' },
  'training.linkId': { en: 'Link ID', ar: 'رقم الهوية' },
  'training.station': { en: 'Station', ar: 'المحطة' },
  'training.hireDate': { en: 'Hire Date', ar: 'تاريخ التعيين' },
  'training.mobile': { en: 'Mobile No.', ar: 'رقم الهاتف' },
  'training.jobFunction': { en: 'Job Function', ar: 'الوظيفة' },
  'training.jobFunctionLegend': { en: 'Job Function Legend', ar: 'دليل الوظائف' },
  'training.records.title': { en: 'Training Records', ar: 'سجلات التدريب' },
  'training.records.add': { en: 'Add Training Record', ar: 'إضافة سجل تدريب' },
  'training.courseName': { en: 'Course Name', ar: 'اسم الدورة' },
  'training.provider': { en: 'Provider', ar: 'مقدم الدورة' },
  'training.location': { en: 'Course Location', ar: 'موقع الدورة' },
  'training.startDate': { en: 'Start Date', ar: 'تاريخ البداية' },
  'training.endDate': { en: 'End Date', ar: 'تاريخ النهاية' },
  'training.plannedDate': { en: 'Planned Date', ar: 'التاريخ المخطط' },
  'training.result': { en: 'Result', ar: 'النتيجة' },
  'training.percentage': { en: 'Percentage', ar: 'النسبة' },
  'training.result.passed': { en: 'Passed', ar: 'ناجح' },
  'training.result.failed': { en: 'Failed', ar: 'راسب' },
  'training.result.pending': { en: 'Pending', ar: 'قيد الانتظار' },
  'training.noRecords': { en: 'No training records found', ar: 'لا توجد سجلات تدريب' },
  'training.fillRequired': { en: 'Please fill all required fields', ar: 'يرجى ملء جميع الحقول المطلوبة' },
  // Trainers
  'training.trainers.list': { en: 'Trainers List', ar: 'قائمة المدربين' },
  'training.trainers.add': { en: 'Add Trainer', ar: 'إضافة مدرب' },
  'training.trainers.addNew': { en: 'Add New Trainer', ar: 'إضافة مدرب جديد' },
  'training.trainers.edit': { en: 'Edit Trainer', ar: 'تعديل المدرب' },
  'training.trainers.photo': { en: 'Photo', ar: 'الصورة' },
  'training.trainers.name': { en: 'Name', ar: 'الاسم' },
  'training.trainers.provider': { en: 'Provider', ar: 'جهة العمل' },
  'training.trainers.jobTitle': { en: 'Job Title', ar: 'المسمى الوظيفي' },
  'training.trainers.email': { en: 'Email', ar: 'البريد الإلكتروني' },
  'training.trainers.status': { en: 'Status', ar: 'الحالة' },
  'training.trainers.id': { en: 'ID', ar: 'الرقم' },
  'training.trainers.title': { en: 'Title', ar: 'اللقب' },
  'training.trainers.firstName': { en: 'First Name', ar: 'الاسم الأول' },
  'training.trainers.lastName': { en: 'Last Name', ar: 'الاسم الأخير' },
  'training.trainers.officeNumber': { en: 'Office Number', ar: 'رقم المكتب' },
  'training.trainers.mobNumber': { en: 'Mobile Number', ar: 'رقم الجوال' },
  'training.trainers.siteAddress': { en: 'Site Address', ar: 'عنوان الموقع' },
  'training.trainers.uploadPhoto': { en: 'Upload Photo', ar: 'رفع صورة' },
  'training.trainers.deleteRecord': { en: 'Delete Record', ar: 'حذف السجل' },
  'training.trainers.saveAndNew': { en: 'Save and New', ar: 'حفظ وإضافة جديد' },
  'training.trainers.discard': { en: 'Discard', ar: 'تجاهل' },
  'training.trainers.record': { en: 'Record', ar: 'سجل' },
  'training.trainerAdded': { en: 'Trainer added successfully', ar: 'تم إضافة المدرب بنجاح' },
  'training.trainerUpdated': { en: 'Trainer updated successfully', ar: 'تم تحديث المدرب بنجاح' },
  'training.trainerDeleted': { en: 'Trainer deleted successfully', ar: 'تم حذف المدرب بنجاح' },
  'training.status.onJob': { en: 'On Job', ar: 'على رأس العمل' },
  'training.status.inactive': { en: 'Inactive', ar: 'غير نشط' },
  'training.status.active': { en: 'Active', ar: 'نشط' },
  // Syllabus
  'training.syllabus.title': { en: 'Course Syllabus', ar: 'منهج الدورة' },
  'training.syllabus.editedBy': { en: 'Edited By', ar: 'تم التعديل بواسطة' },
  'training.syllabus.courseCode': { en: 'Course Code', ar: 'كود الدورة' },
  'training.syllabus.courseInfo': { en: 'Course Information', ar: 'معلومات الدورة' },
  'training.syllabus.duration': { en: 'Course Duration', ar: 'مدة الدورة' },
  'training.syllabus.objective': { en: 'Course Objective', ar: 'هدف الدورة' },
  'training.syllabus.administration': { en: 'Course Administration', ar: 'إدارة الدورة' },
  'training.syllabus.exercises': { en: 'Exercises', ar: 'التمارين' },
  'training.syllabus.basicTopics': { en: 'Basic Topics', ar: 'المواضيع الأساسية' },
  'training.syllabus.intermediateTopics': { en: 'Intermediate Topics', ar: 'المواضيع المتوسطة' },
  'training.syllabus.advancedTopics': { en: 'Advanced Topics', ar: 'المواضيع المتقدمة' },
  'training.syllabus.reference': { en: 'Reference', ar: 'المراجع' },
  'training.syllabus.examination': { en: 'Examination', ar: 'الامتحان' },
  'training.syllabus.added': { en: 'Syllabus added successfully', ar: 'تم إضافة المنهج بنجاح' },
  'training.syllabus.updated': { en: 'Syllabus updated successfully', ar: 'تم تحديث المنهج بنجاح' },
  'training.syllabus.deleted': { en: 'Syllabus deleted successfully', ar: 'تم حذف المنهج بنجاح' },
  // Courses List
  'training.courses.search': { en: 'Search courses...', ar: 'بحث عن دورة...' },
  'training.courses.filterCategory': { en: 'Filter by Category', ar: 'تصفية حسب الفئة' },
  'training.courses.filterStatus': { en: 'Filter by Status', ar: 'تصفية حسب الحالة' },
  'training.courses.add': { en: 'Add Course', ar: 'إضافة دورة' },
  'training.courses.edit': { en: 'Edit Course', ar: 'تعديل الدورة' },
  'training.courses.view': { en: 'View Course', ar: 'عرض الدورة' },
  'training.courses.code': { en: 'Code', ar: 'الكود' },
  'training.courses.name': { en: 'Course Name', ar: 'اسم الدورة' },
  'training.courses.nameEn': { en: 'Name (English)', ar: 'الاسم (إنجليزي)' },
  'training.courses.nameAr': { en: 'Name (Arabic)', ar: 'الاسم (عربي)' },
  'training.courses.category': { en: 'Category', ar: 'الفئة' },
  'training.courses.duration': { en: 'Duration', ar: 'المدة' },
  'training.courses.method': { en: 'Method', ar: 'طريقة التدريب' },
  'training.courses.validity': { en: 'Validity Period', ar: 'فترة الصلاحية' },
  'training.courses.status': { en: 'Status', ar: 'الحالة' },
  'training.courses.description': { en: 'Description', ar: 'الوصف' },
  'training.courses.noResults': { en: 'No courses found', ar: 'لا توجد دورات' },
  'training.courses.methodsLegend': { en: 'Methods of Instructions', ar: 'طرق التدريب' },
  'training.courses.added': { en: 'Course added successfully', ar: 'تم إضافة الدورة بنجاح' },
  'training.courses.updated': { en: 'Course updated successfully', ar: 'تم تحديث الدورة بنجاح' },
  'training.courses.deleted': { en: 'Course deleted successfully', ar: 'تم حذف الدورة بنجاح' },
  'training.category.safety': { en: 'Safety', ar: 'السلامة' },
  'training.category.security': { en: 'Security', ar: 'الأمن' },
  'training.category.humanFactors': { en: 'Human Factors', ar: 'العوامل البشرية' },
  'training.category.technical': { en: 'Technical', ar: 'التقني' },
  // Training Plan
  'training.plan.addCourse': { en: 'Add New Course To Training Plan', ar: 'إضافة دورة جديدة لخطة التدريب' },
  'training.plan.viewPlan': { en: 'View Training Plan', ar: 'عرض خطة التدريب' },
  'training.plan.viewNextYear': { en: 'View Training Plan Next Year', ar: 'عرض خطة التدريب للعام القادم' },
  'training.plan.staffCourses': { en: 'Staff Planned Courses', ar: 'الدورات المخططة للموظفين' },
  'training.plan.staffReport': { en: 'Staff Planned Course Report', ar: 'تقرير الدورات المخططة للموظفين' },
  'training.plan.participants': { en: 'Participants', ar: 'المشاركين' },
  'training.plan.trainer': { en: 'Trainer', ar: 'المدرب' },
  'training.plan.scheduled': { en: 'Scheduled', ar: 'مجدول' },
  'training.plan.inProgress': { en: 'In Progress', ar: 'قيد التنفيذ' },
  'training.plan.completed': { en: 'Completed', ar: 'مكتمل' },
  'training.plan.cancelled': { en: 'Cancelled', ar: 'ملغي' },
  'training.plan.due': { en: 'Due', ar: 'مستحق' },
  'training.plan.overdue': { en: 'Overdue', ar: 'متأخر' },
  'training.plan.courseAdded': { en: 'Course added to plan successfully', ar: 'تم إضافة الدورة للخطة بنجاح' },
  'training.plan.employeeId': { en: 'Employee ID', ar: 'رقم الموظف' },
  'training.plan.employeeName': { en: 'Employee Name', ar: 'اسم الموظف' },
  'training.plan.department': { en: 'Department', ar: 'القسم' },
  'training.plan.dueDate': { en: 'Due Date', ar: 'تاريخ الاستحقاق' },
  'training.plan.totalPlanned': { en: 'Total Planned', ar: 'إجمالي المخطط' },
  'training.plan.totalStaff': { en: 'Total Staff', ar: 'إجمالي الموظفين' },
  'training.plan.coursesScheduled': { en: 'Scheduled', ar: 'مجدول' },
  'training.plan.coursesDue': { en: 'Due', ar: 'مستحق' },
  'training.plan.coursesOverdue': { en: 'Overdue', ar: 'متأخر' },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
