import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<string, Record<Language, string>> = {
  'app.title': { en: 'HR Management System', ar: 'نظام إدارة الموارد البشرية' },
  'nav.dashboard': { en: 'Dashboard', ar: 'لوحة التحكم' },
  'nav.employees': { en: 'Employees', ar: 'الموظفين' },
  'nav.departments': { en: 'Departments', ar: 'الأقسام' },
  'nav.attendance': { en: 'Attendance', ar: 'الحضور والانصراف' },
  'nav.missions': { en: 'Mission Requests', ar: 'طلبات المأمورية' },
  'nav.leaves': { en: 'Leaves', ar: 'الإجازات' },
  'nav.permissions': { en: 'Permissions', ar: 'الأذونات' },
  'nav.salaries': { en: 'Salaries', ar: 'الرواتب' },
  'nav.salaryReports': { en: 'Salary Reports', ar: 'تقارير الرواتب' },
  'nav.loans': { en: 'Loans', ar: 'القروض' },
  'nav.recruitment': { en: 'Recruitment', ar: 'التوظيف' },
  'nav.performance': { en: 'Performance', ar: 'تقييم الأداء' },
  'nav.assets': { en: 'Assets', ar: 'الأصول' },
  'nav.uniforms': { en: 'Uniforms', ar: 'يونيفورم الموظفين' },
  'nav.documents': { en: 'Documents', ar: 'المستندات' },
  'nav.reports': { en: 'Reports', ar: 'التقارير' },
  'nav.training': { en: 'Training', ar: 'التدريب' },
  'nav.configurations': { en: 'CONFIGURATIONS', ar: 'الإعدادات' },
  'nav.users': { en: 'Users', ar: 'المستخدمين' },
  'nav.groups': { en: 'Groups', ar: 'المجموعات' },
  'nav.roles': { en: 'Roles', ar: 'الأدوار' },
  'nav.settings': { en: 'Site Settings', ar: 'إعدادات الموقع' },
  'dashboard.title': { en: 'Dashboard', ar: 'لوحة التحكم' },
  'dashboard.totalEmployees': { en: 'Total Employees', ar: 'إجمالي الموظفين' },
  'dashboard.activeEmployees': { en: 'Active Employees', ar: 'موظفين نشطين' },
  'dashboard.departments': { en: 'Departments', ar: 'الأقسام' },
  'dashboard.todayAttendance': { en: 'Today Attendance', ar: 'الحضور اليوم' },
  'dashboard.openPositions': { en: 'Open Positions', ar: 'الوظائف المفتوحة' },
  'dashboard.pendingLeaves': { en: 'Pending Leave Requests', ar: 'طلبات الإجازة المعلقة' },
  'dashboard.assignedAssets': { en: 'Assigned Assets', ar: 'الأصول المعينة' },
  'dashboard.avgPerformance': { en: 'Avg Performance', ar: 'متوسط تقييم الأداء' },
  'chart.reportsStats': { en: 'Reports & Statistics', ar: 'التقارير والإحصائيات' },
  'chart.employeeGrowth': { en: 'Employee Growth (Last 6 Months)', ar: 'نمو الموظفين (آخر 6 أشهر)' },
  'chart.departmentDist': { en: 'Employees by Department', ar: 'توزيع الموظفين حسب القسم' },
  'chart.weeklyAttendance': { en: 'Weekly Attendance & Performance', ar: 'الحضور والأداء الأسبوعي' },
  'chart.advancedReports': { en: 'Advanced Reports', ar: 'لوحة التقارير المتقدمة' },
  'chart.refresh': { en: 'Refresh', ar: 'تحديث' },
  'dept.it': { en: 'IT', ar: 'تقنية المعلومات' },
  'dept.hr': { en: 'HR', ar: 'الموارد البشرية' },
  'dept.finance': { en: 'Finance', ar: 'المالية' },
  'dept.sales': { en: 'Sales', ar: 'المبيعات' },
  'dept.marketing': { en: 'Marketing', ar: 'التسويق' },
  'dept.operations': { en: 'Operations', ar: 'العمليات' },
  'legend.attendance': { en: 'Attendance', ar: 'الحضور' },
  'legend.completed': { en: 'Completed Tasks', ar: 'التقييمات المكتملة' },
  'legend.late': { en: 'Late', ar: 'التأخير' },
  'month.jan': { en: 'Jan', ar: 'يناير' },
  'month.feb': { en: 'Feb', ar: 'فبراير' },
  'month.mar': { en: 'Mar', ar: 'مارس' },
  'month.apr': { en: 'Apr', ar: 'أبريل' },
  'month.may': { en: 'May', ar: 'مايو' },
  'month.jun': { en: 'Jun', ar: 'يونيو' },
  // Employees page
  'employees.title': { en: 'Employee Management', ar: 'إدارة الموظفين' },
  'employees.search': { en: 'Search for employee...', ar: 'ابحث عن موظف...' },
  'employees.addEmployee': { en: 'Add Employee', ar: 'إضافة موظف' },
  'employees.refresh': { en: 'Refresh', ar: 'تحديث' },
  'employees.editEmployee': { en: 'Edit Employee', ar: 'تعديل الموظف' },
  'employees.save': { en: 'Save', ar: 'حفظ' },
  'employees.cancel': { en: 'Cancel', ar: 'إلغاء' },
  'employees.select': { en: 'Select', ar: 'اختر' },
  'employees.selectDepartment': { en: 'Select Department', ar: 'اختر القسم' },
  'employees.selectDegree': { en: 'Select Degree', ar: 'اختر الدرجة' },
  'employees.selectContractType': { en: 'Select Contract Type', ar: 'اختر نوع العقد' },
  'employees.addNewDepartment': { en: 'Add New Department', ar: 'إضافة قسم جديد' },
  'employees.clickToUpload': { en: 'Click on camera to upload photo', ar: 'انقر على أيقونة الكاميرا لتحميل صورة' },
  'employees.table.photo': { en: 'Photo', ar: 'الصورة' },
  'employees.table.employeeId': { en: 'Employee ID', ar: 'رقم الموظف' },
  'employees.table.name': { en: 'Name', ar: 'الاسم' },
  'employees.table.department': { en: 'Department', ar: 'القسم' },
  'employees.table.jobTitle': { en: 'Job Title', ar: 'المسمى الوظيفي' },
  'employees.table.phone': { en: 'Phone', ar: 'الهاتف' },
  'employees.table.status': { en: 'Status', ar: 'الحالة' },
  'employees.table.actions': { en: 'Actions', ar: 'الإجراءات' },
  'employees.status.active': { en: 'Active', ar: 'نشط' },
  'employees.status.inactive': { en: 'Inactive', ar: 'غير نشط' },
  'employees.status.resigned': { en: 'Resigned', ar: 'مستقيل' },
  'employees.tabs.basicInfo': { en: 'Basic Info', ar: 'معلومات أساسية' },
  'employees.tabs.contactInfo': { en: 'Contact Info', ar: 'معلومات الاتصال' },
  'employees.tabs.identity': { en: 'Identity & Documents', ar: 'الهوية والوثائق' },
  'employees.tabs.jobInfo': { en: 'Job Info', ar: 'معلومات الوظيفة' },
  'employees.tabs.insurance': { en: 'Insurance', ar: 'التأمينات' },
  'employees.tabs.permits': { en: 'Permits', ar: 'التصاريح' },
  'employees.tabs.certificates': { en: 'Certificates', ar: 'الشهادات والوثائق' },
  'employees.tabs.departments': { en: 'Departments', ar: 'الأقسام' },
  'employees.tabs.other': { en: 'Other', ar: 'أخرى' },
  'employees.tabs.leaveBalance': { en: 'Leave Balance', ar: 'رصيد الإجازات' },
  'employees.tabs.salary': { en: 'Salary & Allowances', ar: 'الرواتب والبدلات' },
  'employees.fields.employeeId': { en: 'Employee ID', ar: 'رقم الموظف' },
  'employees.fields.stationLocation': { en: 'Station/Location', ar: 'المحطة/الموقع' },
  'employees.fields.enterStation': { en: 'Enter Station', ar: 'ادخل المحطة' },
  'employees.fields.fullNameAr': { en: 'Full Name (Arabic)', ar: 'الاسم الكامل بالعربية' },
  'employees.fields.fullNameEn': { en: 'Full Name (English)', ar: 'الاسم الكامل بالإنجليزية' },
  'employees.fields.firstName': { en: 'First Name', ar: 'الاسم الأول' },
  'employees.fields.fatherName': { en: 'Father Name', ar: 'اسم الأب' },
  'employees.fields.familyName': { en: 'Family Name', ar: 'اسم العائلة' },
  'employees.fields.birthDate': { en: 'Birth Date', ar: 'تاريخ الميلاد' },
  'employees.fields.birthPlace': { en: 'Birth Place', ar: 'مكان الميلاد' },
  'employees.fields.birthGovernorate': { en: 'Birth Governorate', ar: 'محافظة الميلاد' },
  'employees.fields.gender': { en: 'Gender', ar: 'النوع' },
  'employees.fields.religion': { en: 'Religion', ar: 'الديانة' },
  'employees.fields.nationality': { en: 'Nationality', ar: 'الجنسية' },
  'employees.fields.maritalStatus': { en: 'Marital Status', ar: 'الحالة الاجتماعية' },
  'employees.fields.childrenCount': { en: 'Number of Children', ar: 'عدد الأطفال' },
  'employees.fields.educationAr': { en: 'Education (Arabic)', ar: 'المؤهل الدراسي بالعربية' },
  'employees.fields.graduationYear': { en: 'Graduation Year', ar: 'سنة التخرج' },
  'employees.fields.email': { en: 'Email', ar: 'البريد الإلكتروني' },
  'employees.fields.homePhone': { en: 'Home Phone', ar: 'هاتف المنزل' },
  'employees.fields.mobile': { en: 'Mobile', ar: 'الهاتف المحمول' },
  'employees.fields.address': { en: 'Address', ar: 'العنوان' },
  'employees.fields.city': { en: 'City', ar: 'المدينة' },
  'employees.fields.governorate': { en: 'Governorate', ar: 'المحافظة' },
  'employees.fields.nationalId': { en: 'National ID / Passport', ar: 'الرقم القومي/رقم جواز السفر' },
  'employees.fields.idIssueDate': { en: 'ID Issue Date', ar: 'تاريخ إصدار البطاقة' },
  'employees.fields.idExpiryDate': { en: 'ID Expiry Date', ar: 'تاريخ انتهاء البطاقة' },
  'employees.fields.issuingAuthority': { en: 'Issuing Authority', ar: 'جهة الإصدار' },
  'employees.fields.issuingGovernorate': { en: 'Issuing Governorate', ar: 'محافظة الإصدار' },
  'employees.fields.militaryStatus': { en: 'Military Status', ar: 'الحالة العسكرية' },
  'employees.fields.department': { en: 'Department', ar: 'القسم' },
  'employees.fields.jobTitleAr': { en: 'Job Title (Arabic)', ar: 'المسمى الوظيفي بالعربية' },
  'employees.fields.jobTitleEn': { en: 'Job Title (English)', ar: 'المسمى الوظيفي بالإنجليزية' },
  'employees.fields.jobLevel': { en: 'Job Level', ar: 'مستوى الوظيفة' },
  'employees.fields.jobDegree': { en: 'Job Degree', ar: 'الدرجة الوظيفية' },
  'employees.fields.hireDate': { en: 'Hire Date', ar: 'تاريخ التعيين' },
  'employees.fields.recruitedBy': { en: 'Recruited By', ar: 'طلب التوظيف بواسطة' },
  'employees.fields.employmentStatus': { en: 'Employment Status', ar: 'الحالة' },
  'employees.fields.resigned': { en: 'Resigned', ar: 'مستقيل' },
  'employees.fields.resignationDate': { en: 'Resignation Date', ar: 'تاريخ الاستقالة' },
  'employees.fields.resignationReason': { en: 'Resignation Reason', ar: 'سبب الاستقالة' },
  'employees.fields.socialInsuranceNo': { en: 'Social Insurance No.', ar: 'رقم التأمين الاجتماعي' },
  'employees.fields.socialInsuranceStartDate': { en: 'Social Insurance Start Date', ar: 'تاريخ بدء التأمين الاجتماعي' },
  'employees.fields.socialInsuranceEndDate': { en: 'Social Insurance End Date', ar: 'تاريخ انتهاء التأمين الاجتماعي' },
  'employees.fields.healthInsuranceCardNo': { en: 'Health Insurance Card No.', ar: 'رقم بطاقة التأمين الصحي' },
  'employees.fields.healthInsurance': { en: 'Health Insurance', ar: 'التأمين الصحي' },
  'employees.fields.govHealthInsurance': { en: 'Government Health Insurance', ar: 'التأمين الصحي الحكومي' },
  'employees.fields.socialInsurance': { en: 'Social Insurance', ar: 'التأمين الاجتماعي' },
  'employees.fields.contractType': { en: 'Contract Type', ar: 'نوع العقد' },
  'employees.fields.cairoAirportTempPermit': { en: 'Cairo Airport Temp Permit', ar: 'تصريح مطار القاهرة المؤقت' },
  'employees.fields.cairoAirportAnnualPermit': { en: 'Cairo Airport Annual Permit', ar: 'تصريح مطار القاهرة السنوي' },
  'employees.fields.tempPermitNo': { en: 'Temp Permit No.', ar: 'رقم التصريح المؤقت' },
  'employees.fields.annualPermitNo': { en: 'Annual Permit No.', ar: 'رقم التصريح السنوي' },
  'employees.fields.airportsTempPermit': { en: 'Airports Temp Permit', ar: 'تصريح المطارات المؤقت' },
  'employees.fields.airportsAnnualPermit': { en: 'Airports Annual Permit', ar: 'تصريح المطارات السنوي' },
  'employees.fields.airportsTempPermitNo': { en: 'Airports Temp Permit No.', ar: 'رقم تصريح المطارات المؤقت' },
  'employees.fields.airportsAnnualPermitNo': { en: 'Airports Annual Permit No.', ar: 'رقم تصريح المطارات السنوي' },
  'employees.fields.airportsPermitType': { en: 'Airports Permit Type', ar: 'نوع تصاريح المطارات' },
  'employees.fields.permitNameEn': { en: 'Permit Name (English)', ar: 'المسمى في التصريح بالإنجليزية' },
  'employees.fields.permitNameAr': { en: 'Permit Name (Arabic)', ar: 'المسمى في التصريح بالعربية' },
  'employees.fields.qualificationCert': { en: 'Qualification Certificate', ar: 'شهادة المؤهل' },
  'employees.fields.militaryServiceCert': { en: 'Military Service Certificate', ar: 'شهادة الخدمة العسكرية' },
  'employees.fields.birthCert': { en: 'Birth Certificate', ar: 'شهادة الميلاد' },
  'employees.fields.idCopy': { en: 'ID Copy', ar: 'صورة البطاقة' },
  'employees.fields.pledge': { en: 'Pledge', ar: 'التعهد' },
  'employees.fields.contract': { en: 'Contract', ar: 'العقد' },
  'employees.fields.receipt': { en: 'Receipt', ar: 'الفيش' },
  'employees.fields.attachments': { en: 'Attachments', ar: 'المرفقات' },
  'employees.fields.notes': { en: 'Notes', ar: 'ملاحظات' },
  'employees.fields.notesPlaceholder': { en: 'Enter any additional notes...', ar: 'أدخل أي ملاحظات إضافية...' },
  'employees.fields.annualLeaveBalance': { en: 'Annual Leave Balance', ar: 'رصيد الإجازات السنوية' },
  'employees.fields.sickLeaveBalance': { en: 'Sick Leave Balance', ar: 'رصيد الإجازات المرضية' },
  'employees.fields.casualLeaveBalance': { en: 'Casual Leave Balance', ar: 'رصيد الإجازات العارضة' },
  'employees.fields.usedLeave': { en: 'Used Leave', ar: 'الإجازات المستخدمة' },
  'employees.fields.basicSalary': { en: 'Basic Salary', ar: 'الراتب الأساسي' },
  'employees.fields.allowances': { en: 'Allowances', ar: 'البدلات' },
  'employees.fields.transportAllowance': { en: 'Transport Allowance', ar: 'بدل المواصلات' },
  'employees.fields.housingAllowance': { en: 'Housing Allowance', ar: 'بدل السكن' },
  'employees.fields.mealAllowance': { en: 'Meal Allowance', ar: 'بدل الوجبات' },
  'employees.fields.otherAllowances': { en: 'Other Allowances', ar: 'بدلات أخرى' },
  'employees.fields.deductions': { en: 'Deductions', ar: 'الاستقطاعات' },
  'employees.fields.netSalary': { en: 'Net Salary', ar: 'صافي الراتب' },
  'employees.gender.male': { en: 'Male', ar: 'ذكر' },
  'employees.gender.female': { en: 'Female', ar: 'أنثى' },
  'employees.religion.muslim': { en: 'Muslim', ar: 'مسلم' },
  'employees.religion.christian': { en: 'Christian', ar: 'مسيحي' },
  'employees.maritalStatus.single': { en: 'Single', ar: 'أعزب' },
  'employees.maritalStatus.married': { en: 'Married', ar: 'متزوج' },
  'employees.maritalStatus.divorced': { en: 'Divorced', ar: 'مطلق' },
  'employees.maritalStatus.widowed': { en: 'Widowed', ar: 'أرمل' },
  'employees.military.completed': { en: 'Completed', ar: 'أدى الخدمة' },
  'employees.military.exempt': { en: 'Exempt', ar: 'معفى' },
  'employees.military.postponed': { en: 'Postponed', ar: 'مؤجل' },
  'employees.contract.permanent': { en: 'Permanent', ar: 'دائم' },
  'employees.contract.temporary': { en: 'Temporary', ar: 'مؤقت' },
  'employees.contract.parttime': { en: 'Part-time', ar: 'جزئي' },
  // Leaves module
  'leaves.title': { en: 'Leave Management', ar: 'إدارة الإجازات' },
  'leaves.subtitle': { en: 'Manage employee leave requests and approvals', ar: 'إدارة طلبات إجازات الموظفين والموافقات' },
  'leaves.tabs.requests': { en: 'All Requests', ar: 'جميع الطلبات' },
  'leaves.tabs.newRequest': { en: 'New Request', ar: 'طلب جديد' },
  'leaves.tabs.approvals': { en: 'Approvals', ar: 'الموافقات' },
  'leaves.tabs.balance': { en: 'Balance', ar: 'الأرصدة' },
  'leaves.tabs.calendar': { en: 'Calendar', ar: 'التقويم' },
  'leaves.days': { en: 'days', ar: 'أيام' },
  'leaves.types.annual': { en: 'Annual', ar: 'سنوية' },
  'leaves.types.sick': { en: 'Sick', ar: 'مرضية' },
  'leaves.types.casual': { en: 'Casual', ar: 'عارضة' },
  'leaves.types.unpaid': { en: 'Unpaid', ar: 'بدون راتب' },
  'leaves.types.maternity': { en: 'Maternity', ar: 'أمومة' },
  'leaves.types.paternity': { en: 'Paternity', ar: 'أبوة' },
  'leaves.status.pending': { en: 'Pending', ar: 'قيد الانتظار' },
  'leaves.status.approved': { en: 'Approved', ar: 'موافق عليه' },
  'leaves.status.rejected': { en: 'Rejected', ar: 'مرفوض' },
  'leaves.form.title': { en: 'Submit Leave Request', ar: 'تقديم طلب إجازة' },
  'leaves.form.leaveType': { en: 'Leave Type', ar: 'نوع الإجازة' },
  'leaves.form.selectType': { en: 'Select leave type', ar: 'اختر نوع الإجازة' },
  'leaves.form.startDate': { en: 'Start Date', ar: 'تاريخ البداية' },
  'leaves.form.endDate': { en: 'End Date', ar: 'تاريخ النهاية' },
  'leaves.form.totalDays': { en: 'Total Days', ar: 'إجمالي الأيام' },
  'leaves.form.reason': { en: 'Reason', ar: 'السبب' },
  'leaves.form.reasonPlaceholder': { en: 'Enter reason for leave...', ar: 'أدخل سبب الإجازة...' },
  'leaves.form.pickDate': { en: 'Pick a date', ar: 'اختر تاريخ' },
  'leaves.form.submit': { en: 'Submit Request', ar: 'إرسال الطلب' },
  'leaves.form.error': { en: 'Error', ar: 'خطأ' },
  'leaves.form.fillAllFields': { en: 'Please fill all required fields', ar: 'يرجى ملء جميع الحقول المطلوبة' },
  'leaves.form.success': { en: 'Success', ar: 'نجاح' },
  'leaves.form.requestSubmitted': { en: 'Leave request submitted successfully', ar: 'تم تقديم طلب الإجازة بنجاح' },
  'leaves.list.title': { en: 'Leave Requests', ar: 'طلبات الإجازات' },
  'leaves.list.employee': { en: 'Employee', ar: 'الموظف' },
  'leaves.list.department': { en: 'Department', ar: 'القسم' },
  'leaves.list.type': { en: 'Type', ar: 'النوع' },
  'leaves.list.startDate': { en: 'Start Date', ar: 'تاريخ البداية' },
  'leaves.list.endDate': { en: 'End Date', ar: 'تاريخ النهاية' },
  'leaves.list.days': { en: 'Days', ar: 'الأيام' },
  'leaves.list.status': { en: 'Status', ar: 'الحالة' },
  'leaves.list.noRequests': { en: 'No leave requests found', ar: 'لا توجد طلبات إجازة' },
  'leaves.approvals.title': { en: 'Pending Approvals', ar: 'الموافقات المعلقة' },
  'leaves.approvals.noPending': { en: 'No pending requests to approve', ar: 'لا توجد طلبات معلقة للموافقة' },
  'leaves.approvals.approve': { en: 'Approve', ar: 'موافقة' },
  'leaves.approvals.reject': { en: 'Reject', ar: 'رفض' },
  'leaves.approvals.approved': { en: 'Approved', ar: 'تمت الموافقة' },
  'leaves.approvals.approvedMessage': { en: 'Leave request has been approved', ar: 'تمت الموافقة على طلب الإجازة' },
  'leaves.approvals.rejected': { en: 'Rejected', ar: 'تم الرفض' },
  'leaves.approvals.rejectedMessage': { en: 'Leave request has been rejected', ar: 'تم رفض طلب الإجازة' },
  'leaves.approvals.rejectTitle': { en: 'Reject Leave Request', ar: 'رفض طلب الإجازة' },
  'leaves.approvals.rejectReasonPlaceholder': { en: 'Enter reason for rejection...', ar: 'أدخل سبب الرفض...' },
  'leaves.approvals.confirmReject': { en: 'Confirm Rejection', ar: 'تأكيد الرفض' },
  'leaves.balance.annualLeave': { en: 'Annual Leave', ar: 'الإجازة السنوية' },
  'leaves.balance.sickLeave': { en: 'Sick Leave', ar: 'الإجازة المرضية' },
  'leaves.balance.casualLeave': { en: 'Casual Leave', ar: 'الإجازة العارضة' },
  'leaves.balance.used': { en: 'Used', ar: 'مستخدم' },
  'leaves.balance.remaining': { en: 'Remaining', ar: 'المتبقي' },
  'leaves.balance.detailedBalance': { en: 'Detailed Leave Balance', ar: 'تفاصيل رصيد الإجازات' },
  'leaves.balance.employee': { en: 'Employee', ar: 'الموظف' },
  'leaves.balance.department': { en: 'Department', ar: 'القسم' },
  'leaves.calendar.title': { en: 'Team Absence Calendar', ar: 'تقويم غياب الفريق' },
  'leaves.calendar.more': { en: 'more', ar: 'المزيد' },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
