ALTER TABLE public.employees
  ADD COLUMN IF NOT EXISTS avatar text,
  ADD COLUMN IF NOT EXISTS first_name text,
  ADD COLUMN IF NOT EXISTS father_name text,
  ADD COLUMN IF NOT EXISTS family_name text,
  ADD COLUMN IF NOT EXISTS birth_governorate text,
  ADD COLUMN IF NOT EXISTS issuing_governorate text,
  ADD COLUMN IF NOT EXISTS recruited_by text,
  ADD COLUMN IF NOT EXISTS resigned boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_cairo_airport_temp_permit boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS temp_permit_no text,
  ADD COLUMN IF NOT EXISTS has_cairo_airport_annual_permit boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS annual_permit_no text,
  ADD COLUMN IF NOT EXISTS has_airports_temp_permit boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_airports_annual_permit boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS airports_temp_permit_no text,
  ADD COLUMN IF NOT EXISTS airports_annual_permit_no text,
  ADD COLUMN IF NOT EXISTS airports_permit_type text,
  ADD COLUMN IF NOT EXISTS permit_name_en text,
  ADD COLUMN IF NOT EXISTS permit_name_ar text,
  ADD COLUMN IF NOT EXISTS has_qualification_cert boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_military_service_cert boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_birth_cert boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_id_copy boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_pledge boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_contract boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_receipt boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS attachments text;